//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC6WeChat11KaraProphet : _TtCs12_SwiftObject
{
    MISSING_TYPE *module;
    MISSING_TYPE *table;
    MISSING_TYPE *mmkv;
    MISSING_TYPE *timeIntervalThatBehaviorStabled;
    MISSING_TYPE *registrationInChina;
    MISSING_TYPE *clientVersion;
    MISSING_TYPE *model;
}

- (void)databaseDidRecover;

@end

