//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6WeChatP33_841B066D57CDD0B21C206388620843273Log : _TtCs12_SwiftObject
{
}

@end

