//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MISSING_TYPE;

@interface _TtC6WeChat42WSNativeHotListHotSearchItemFriendLikeView
{
    MISSING_TYPE *imgLength;
    MISSING_TYPE *textStr;
    MISSING_TYPE *avatarLength;
    MISSING_TYPE *$__lazy_storage_$_subtitleDescLabel;
    MISSING_TYPE *$__lazy_storage_$_userAvatarImgView;
    MISSING_TYPE *$__lazy_storage_$_optionalUserAvatarImgView;
    MISSING_TYPE *$__lazy_storage_$_userIconImgView;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

