//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6WeChat26MMLiveAIGCGiftProgressRing : UIView
{
    double progress;
    MISSING_TYPE *_progress;
    MISSING_TYPE *trackLayer;
    MISSING_TYPE *progressLayer;
    MISSING_TYPE *trackColor;
    MISSING_TYPE *progressColor;
    double lineWidth;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)hideProgressLayer;
- (void)showProgressLayer;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double lineWidth; // @synthesize lineWidth;
@property(nonatomic) double progress; // @synthesize progress;

@end

