//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MISSING_TYPE;

@interface _TtC6WeChat4Kara
{
    MISSING_TYPE *_prophets;
    MISSING_TYPE *_timeSeriesProphets;
}

- (void).cxx_destruct;
- (id)init;
- (void)onServiceClearData;
- (void)onServiceInit;

@end

