//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class AdDataReportReq, BaseRequest, NSMutableArray;

@interface AdReportForSnsReq : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) AdDataReportReq *adDataReportReq; // @dynamic adDataReportReq;
@property(retain, nonatomic) NSMutableArray *adDataReportReqList; // @dynamic adDataReportReqList;
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;

@end

