//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BeatTemplateDefaultTemplate, NSMutableArray;

@interface BeatTemplateTaskResult : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *bgmList; // @dynamic bgmList;
@property(retain, nonatomic) BeatTemplateDefaultTemplate *defaultTemplate; // @dynamic defaultTemplate;

@end

