//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface BizReportConfig : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int holdSecAfterUserLeaveForReport; // @dynamic holdSecAfterUserLeaveForReport;
@property(nonatomic) unsigned int reportArticleJumpPathDepth; // @dynamic reportArticleJumpPathDepth;
@property(nonatomic) unsigned int reportShowBatchSize; // @dynamic reportShowBatchSize;
@property(retain, nonatomic) NSString *reportShowStrategyInfo; // @dynamic reportShowStrategyInfo;

@end

