//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BlueAdapterSessionDelegate-Protocol.h"
#import "BlueProfilePedometerDelegate-Protocol.h"

@protocol BlueAdapterDelegate <BlueAdapterSessionDelegate, BlueProfilePedometerDelegate>
@end

