//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BoxAffBizDynamicCardMrgEventCallback, NSString;

@protocol BoxAffBizDynamicCardMrgEventBase <NSObject>

@optional
- (void)callOnDynamicCardInfoAsync:(int)arg1 dynamicCardType:(int)arg2 msgId:(unsigned long long)arg3 frameSetName:(NSString *)arg4 frameSetData:(NSString *)arg5;
- (void)callOnRecFeedsAdServerInfoAsync:(int)arg1 adInfo:(NSString *)arg2;
- (void)callOnAdServerInfoAsync:(int)arg1 adInfo:(NSString *)arg2;
- (void)setCallback:(BoxAffBizDynamicCardMrgEventCallback *)arg1;
@end

