//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIImageView, UIView;

@protocol CBTAsstBoardFoldableTitleBarButtonProtocol <NSObject>
- (void)onFoldableTitleBarButtonTapped;
- (UIImageView *)foldableTitleBarArrowView;
- (double)foldableTitleBarHeight;
- (UIView *)foldableTitleBarView;

@optional
- (double)foldableTitleBarButtonTrailingMargin;
- (_Bool)foldableTitleBarButtonHidden;
- (NSString *)foldableTitleBarButtonTitle;
@end

