//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class ContactSettingViewController, MMTableViewInfo, NSString;

@interface CBTAsstContactInfoAssist
{
    _Bool _isNickNameUnsafe;
    MMTableViewInfo *_tableViewInfo;
    NSString *_cpKeyForNickname;
    ContactSettingViewController *_settingViewController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ContactSettingViewController *settingViewController; // @synthesize settingViewController=_settingViewController;
@property(nonatomic) _Bool isNickNameUnsafe; // @synthesize isNickNameUnsafe=_isNickNameUnsafe;
@property(retain, nonatomic) NSString *cpKeyForNickname; // @synthesize cpKeyForNickname=_cpKeyForNickname;
@property(retain, nonatomic) MMTableViewInfo *tableViewInfo; // @synthesize tableViewInfo=_tableViewInfo;
- (void)onRestoreCPLabel:(id)arg1;
- (void)updateCPState;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onAction;
- (_Bool)shouldRemoveContactPopPreviousPage;
- (void)reloadNavigationBarItem;
- (void)sendMsgBtnCell:(id)arg1 CellInfo:(id)arg2;
- (void)addMsgActionView;
- (id)getSection;
- (void)showHDHeadViewImage;
- (void)onNewMessage:(id)arg1;
- (void)adjustmentProfileIntroViewTail:(double)arg1 andProfileIntroView:(id)arg2 andradiusCornerView:(id)arg3;
- (id)getProfileIntroView;
- (id)getProfileHeadView;
- (void)reloadTableView;
- (id)GetTableView;
- (void)initTableView;
- (id)initWithContact:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

