//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CBTCoopV2AsstBoardCommonCellContentView, NSString, TingCategoryCoverView, UILongPressGestureRecognizer, UITapGestureRecognizer, UIView;

@interface CBTCoopV2TingCategoryCellView
{
    _Bool _needsContentUpdate;
    UIView *_cardView;
    TingCategoryCoverView *_coverView;
    CBTCoopV2AsstBoardCommonCellContentView *_commonContentView;
    UITapGestureRecognizer *_tapGesture;
    UILongPressGestureRecognizer *_pressGesture;
    UIView *_highlightOverlayView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool needsContentUpdate; // @synthesize needsContentUpdate=_needsContentUpdate;
@property(retain, nonatomic) UIView *highlightOverlayView; // @synthesize highlightOverlayView=_highlightOverlayView;
@property(retain, nonatomic) UILongPressGestureRecognizer *pressGesture; // @synthesize pressGesture=_pressGesture;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) CBTCoopV2AsstBoardCommonCellContentView *commonContentView; // @synthesize commonContentView=_commonContentView;
@property(retain, nonatomic) TingCategoryCoverView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) UIView *cardView; // @synthesize cardView=_cardView;
- (_Bool)isBubbleRightAligned;
- (id)getBubbleColor;
- (_Bool)needsBubbleBackground;
- (void)onTapCategory;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)onPressGesture:(id)arg1;
- (_Bool)isCurrentPlayingCategory:(id)arg1;
- (void)applyAssistantPlayContextToModel:(id)arg1 categoryItem:(id)arg2;
- (void)playCategory:(id)arg1 listContext:(id)arg2 launchOptions:(id)arg3;
- (id)categoryItemForAutoPlay:(id)arg1;
- (void)playCategoryAutomatically;
- (void)layoutContentWithViewModel:(id)arg1;
- (void)applyViewModelIfNeeded;
- (void)ensureSubviews;
- (double)checkboxArrowHeight;
- (double)checkboxArrowTopMarginInBubbleView;
- (id)checkboxAlignmentBubbleView;
- (id)tingCardBusinessReportParams;
- (void)fillTingReportExtInfo2:(id)arg1;
- (unsigned long long)checkboxVerticalAlignment;
- (void)tingCategoryViewModelDidFillHostInfo;
- (void)triggerAutoPlay;
- (void)startAutoPlay;
- (void)layoutSubviews;
- (id)menuAnchorView;
- (void)setupCellWithViewModel:(id)arg1;
- (void)prepareForReuse;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

