//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIImageView, WCDataItem, WCImageView;

@interface CBTCoopV2TimelineVideoMediaView
{
    WCDataItem *_dataItem;
    WCImageView *_previewView;
    UIImageView *_playView;
}

+ (double)renderedHeightForDataItem:(id)arg1 contentWidth:(double)arg2;
+ (struct CGSize)videoPreviewSizeForMediaItem:(id)arg1;
+ (_Bool)isPortraitVideoMediaItem:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *playView; // @synthesize playView=_playView;
@property(retain, nonatomic) WCImageView *previewView; // @synthesize previewView=_previewView;
@property(retain, nonatomic) WCDataItem *dataItem; // @synthesize dataItem=_dataItem;
- (void)layoutSubviews;
- (void)ensureSubviews;
- (id)initWithDataItem:(id)arg1 contentWidth:(double)arg2;

@end

