//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CBTHalfScreenTingRoute : NSObject
{
}

+ (void)showFromVC:(id)arg1 options:(id)arg2 dismissCallback:(CDUnknownBlockType)arg3;
+ (id)optionsWithMultimodalWrapData:(id)arg1 shareType:(int)arg2 shareItemId:(id)arg3 srcInfoParams:(id)arg4;
+ (void)showFromVC:(id)arg1 multimodalWrapData:(id)arg2 shareType:(int)arg3 shareItemId:(id)arg4 query:(id)arg5 reverse:(_Bool)arg6 dismissCallback:(CDUnknownBlockType)arg7 didAppearCallback:(CDUnknownBlockType)arg8;
+ (void)showFromVC:(id)arg1 multimodalWrapData:(id)arg2 shareType:(int)arg3 shareItemId:(id)arg4 dismissCallback:(CDUnknownBlockType)arg5 didAppearCallback:(CDUnknownBlockType)arg6;
+ (void)showFromVC:(id)arg1 multimodalWrapData:(id)arg2 shareType:(int)arg3 shareItemId:(id)arg4 dismissCallback:(CDUnknownBlockType)arg5;
+ (_Bool)isExternalEntryEnabled;
+ (_Bool)isEntryEnabled;

@end

