//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CBTHalfScreenFinderRoute : NSObject
{
}

+ (void)showFromVC:(id)arg1 options:(id)arg2 dismissCallback:(CDUnknownBlockType)arg3;
+ (id)optionsWithImagePaths:(id)arg1 shareItemId:(id)arg2 sug:(id)arg3 srcInfoParams:(id)arg4;
+ (id)optionsWithMultimodalXml:(id)arg1 shareItemId:(id)arg2 sug:(id)arg3 srcInfoParams:(id)arg4;
+ (void)showFromVC:(id)arg1 imagePaths:(id)arg2 shareItemId:(id)arg3 sug:(id)arg4 dismissCallback:(CDUnknownBlockType)arg5;
+ (void)showFromVC:(id)arg1 imagePaths:(id)arg2 shareItemId:(id)arg3 dismissCallback:(CDUnknownBlockType)arg4;
+ (void)showFromVC:(id)arg1 multimodalXml:(id)arg2 shareItemId:(id)arg3 sug:(id)arg4 dismissCallback:(CDUnknownBlockType)arg5;
+ (void)showFromVC:(id)arg1 multimodalXml:(id)arg2 shareItemId:(id)arg3 dismissCallback:(CDUnknownBlockType)arg4;
+ (_Bool)isExternalEntryEnabled;
+ (id)fetchSugWithRouteType:(long long)arg1;
+ (_Bool)isEntryEnabled;

@end

