//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ContactProfileRecommendSelectView, NSString;

@protocol ContactProfileRecommendSelectViewDelegate <NSObject>

@optional
- (void)reportClieckContactProfileRecommendSelectView:(ContactProfileRecommendSelectView *)arg1 recommendText:(id)arg2 recommendSelectType:(unsigned int)arg3;
- (void)reportExposureContactProfileRecommendSelectView:(ContactProfileRecommendSelectView *)arg1 arrRecommendText:(id)arg2 recommendSelectType:(unsigned int)arg3;
- (void)onSelectedProfileRecommendText:(NSString *)arg1 recommendSelectType:(unsigned int)arg2;
@end

