//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FavoritesItem, MMUIViewController, NSArray, NSIndexPath, UIScrollView;

@protocol FavBaseTableDataControllerDelegate <NSObject>
- (MMUIViewController *)getCurrentViewController;

@optional
- (_Bool)isStarredOnlyFilterActive;
- (NSArray *)filterItemListByTabMode:(NSArray *)arg1;
- (void)onFoldButtonStatusDetermined;
- (int)getSortType;
- (_Bool)isWeNoteMode;
- (_Bool)isNewSearchMode;
- (_Bool)isOnSearch;
- (void)canNotSelecteDueToExceedCount;
- (long long)getSelectedType;
- (void)onLoadMore;
- (void)onHideEmptyView;
- (void)onShowEmptyView;
- (void)onUpdateUnexistItem:(FavoritesItem *)arg1;
- (void)onScrollViewWillBeginDragging:(UIScrollView *)arg1;
- (void)onScrollViewDidEndDragging:(UIScrollView *)arg1 willDecelerate:(_Bool)arg2;
- (void)onScrollViewDidScroll:(UIScrollView *)arg1;
- (void)onSelectRowAtIndexPath:(NSIndexPath *)arg1;
- (void)performAction:(SEL)arg1 forRowAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)canPerformAction:(SEL)arg1 forRowAtIndexPath:(NSIndexPath *)arg2;
- (void)commitEditingStyle:(long long)arg1 forRowAtIndexPath:(NSIndexPath *)arg2;
@end

