//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface FeedsPreviewLiveMultiStyleInfo_StyleSevenTeen_CycleStyleControl : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int showMillisecond; // @dynamic showMillisecond;
@property(nonatomic) unsigned int styleId; // @dynamic styleId;
@property(nonatomic) unsigned int waitMillisecond; // @dynamic waitMillisecond;

@end

