//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseResponse, InteractionWishConfig, NSMutableArray;

@interface FinderLiveGetInteractionWishConfigResp : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) InteractionWishConfig *curWishConfig; // @dynamic curWishConfig;
@property(retain, nonatomic) NSMutableArray *defaultWishConfigList; // @dynamic defaultWishConfigList;
@property(nonatomic) _Bool disableSetPerformanceName; // @dynamic disableSetPerformanceName;
@property(retain, nonatomic) NSMutableArray *enableConfigInteractionType; // @dynamic enableConfigInteractionType;
@property(nonatomic) _Bool hasValidRecommendWishConfig; // @dynamic hasValidRecommendWishConfig;
@property(nonatomic) _Bool hasValidWishConfig; // @dynamic hasValidWishConfig;
@property(retain, nonatomic) NSMutableArray *onlineMembers; // @dynamic onlineMembers;
@property(retain, nonatomic) InteractionWishConfig *recommendWishConfig; // @dynamic recommendWishConfig;

@end

