//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface FinderJoinliveMsgRecallInfos_MsgRecallInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *clientMsgId; // @dynamic clientMsgId;
@property(retain, nonatomic) NSString *displayContext; // @dynamic displayContext;
@property(retain, nonatomic) NSString *localClientMsgId; // @dynamic localClientMsgId;

@end

