//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderGetLiveMsgResp_HotWordFloatMsgConfig;

@interface FinderGetLiveMsgResp_ExtraClientConfig : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool enableCoverEnhance; // @dynamic enableCoverEnhance;
@property(retain, nonatomic) FinderGetLiveMsgResp_HotWordFloatMsgConfig *hotWordFloatMsgConfig; // @dynamic hotWordFloatMsgConfig;
@property(nonatomic) _Bool sysEnablePreviewLiveFloatMsg; // @dynamic sysEnablePreviewLiveFloatMsg;
@property(nonatomic) _Bool userEnablePreviewLiveFloatMsg; // @dynamic userEnablePreviewLiveFloatMsg;

@end

