//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class AggregateBulletcommentDisplayInfo, NSString;

@interface FollowAggregatedBulletCommentInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned long long aggCommentId; // @dynamic aggCommentId;
@property(nonatomic) unsigned long long buttonTimestampMs; // @dynamic buttonTimestampMs;
@property(nonatomic) unsigned int commentLineCountMax; // @dynamic commentLineCountMax;
@property(retain, nonatomic) NSString *content; // @dynamic content;
@property(retain, nonatomic) AggregateBulletcommentDisplayInfo *displayInfo; // @dynamic displayInfo;
@property(nonatomic) unsigned long long timestampBeginMs; // @dynamic timestampBeginMs;

@end

