//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface GameCenterMsgFloayLayerInfo : NSObject
{
    NSString *_url;
    long long _floatLayerType;
    NSArray *_wepkgIds;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *wepkgIds; // @synthesize wepkgIds=_wepkgIds;
@property(nonatomic) long long floatLayerType; // @synthesize floatLayerType=_floatLayerType;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;

@end

