//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface GetBizLastReadingResp_BizLastReadingInfoAppmsgInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int appmsgId; // @dynamic appmsgId;
@property(retain, nonatomic) NSString *bizImg; // @dynamic bizImg;
@property(retain, nonatomic) NSString *bizName; // @dynamic bizName;
@property(retain, nonatomic) NSString *bizTitle; // @dynamic bizTitle;
@property(retain, nonatomic) NSString *bizUin; // @dynamic bizUin;
@property(retain, nonatomic) NSString *bizUrl; // @dynamic bizUrl;
@property(nonatomic) unsigned int delType; // @dynamic delType;
@property(nonatomic) unsigned int itemId; // @dynamic itemId;
@property(nonatomic) unsigned int readTime; // @dynamic readTime;
@property(nonatomic) unsigned int type; // @dynamic type;

@end

