//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol IAdDynamicCanvasExt <NSObject>
- (void)publishEventToPage:(NSString *)arg1 event:(NSString *)arg2 params:(NSDictionary *)arg3;
- (void)publishEvent:(NSString *)arg1 params:(NSDictionary *)arg2;
@end

