//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class IlinkStreamChannel, NSHashTable;

@interface iLinkStreamChannelObj : NSObject
{
    int _businessType;
    NSHashTable *_observerList;
    IlinkStreamChannel *_channel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) IlinkStreamChannel *channel; // @synthesize channel=_channel;
@property(nonatomic) int businessType; // @synthesize businessType=_businessType;
@property(retain, nonatomic) NSHashTable *observerList; // @synthesize observerList=_observerList;
- (void)warmUp;
- (void)enumerateObserver:(CDUnknownBlockType)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)destroyStream:(id)arg1;
- (void)sendStreamFragment:(id)arg1;
- (id)createDownStream:(id)arg1 businessScene:(unsigned int)arg2 streamBusinessCtx:(id)arg3 streamTicket:(id)arg4;
- (id)createStream:(id)arg1 businessScene:(unsigned int)arg2 streamBusinessCtx:(id)arg3;
- (void)createChannel;
- (void)dealloc;
- (id)initWithBizType:(int)arg1;

@end

