//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol IMpWebEnvService <NSObject>
+ (unsigned int)clientVersion;
+ (float)layoutScale;
+ (unsigned int)webviewFontScale;
+ (unsigned int)webviewFontLevel;
@end

