//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol IWAHTMLWebVCDelegate <NSObject>
- (void)webviewControllerDidReceiveScriptMessage:(id)arg1 handler:(NSString *)arg2;
- (void)onTranslateRevertFinish:(_Bool)arg1;
- (void)onTranslateFinish:(_Bool)arg1;
- (void)webviewDidFinish:(NSDictionary *)arg1;
@end

