//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class EmoticonBoardView, FlutterMethodChannel, NSDictionary, NSString, UIView;

@interface LiteAppEmoticonPanelView : NSObject
{
    EmoticonBoardView *_emoticonBoardView;
    UIView *_containerView;
    FlutterMethodChannel *_channel;
    long long _viewId;
    NSDictionary *_creationParams;
    struct CGRect _frame;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) NSDictionary *creationParams; // @synthesize creationParams=_creationParams;
@property(nonatomic) long long viewId; // @synthesize viewId=_viewId;
@property(retain, nonatomic) FlutterMethodChannel *channel; // @synthesize channel=_channel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) EmoticonBoardView *emoticonBoardView; // @synthesize emoticonBoardView=_emoticonBoardView;
- (id)topViewController;
- (id)emoticonSelectedArgumentsFromEmoticon:(id)arg1 fromSearch:(_Bool)arg2;
- (void)checkAndCallSelectEmoticonMethod:(id)arg1 fromSearch:(_Bool)arg2;
- (void)onSearchEmoticonViewControllerSendEmoticon:(id)arg1;
- (void)didSelectorSelfDefinedEmotcion:(id)arg1;
- (void)deleteEmoticon;
- (void)didSelectorEmoticon:(id)arg1;
- (id)findMMViewControllerInResponderChain;
- (id)GetCurrentViewController;
- (void)onSendButtonClicked;
- (void)onEmoticonSearchIconClicked;
- (id)view;
- (void)traverseAndHideDivider:(id)arg1 depth:(long long)arg2;
- (void)hideCategoryDivider:(id)arg1;
- (void)clearAllBackgrounds:(id)arg1;
- (void)applyAppearance:(id)arg1 params:(id)arg2;
- (void)applyConfirmType:(id)arg1 confirmType:(id)arg2;
- (void)applyDefaultConfig:(id)arg1;
- (void)configureView:(id)arg1;
- (id)createEmoticonBoardView;
- (void)sendPlatformViewEvent:(id)arg1 data:(id)arg2;
- (void)handleJSEvent:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)setupMethodCallHandler;
- (id)initWithFrame:(struct CGRect)arg1 viewIdentifier:(long long)arg2 arguments:(id)arg3 methodChannel:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

