//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface MarsCdnQuotaStatus : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned long long leftBytes; // @dynamic leftBytes;
// Error: Property attributes should begin with the type ('T') attribute, property name: leftMsecs
// Property attributes: (null)


@end

