//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class CardMiniAppInfo, NSString;

@interface MedicareAndSocialSecurityCardTips : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int pageTicketJumpElementOpType; // @dynamic pageTicketJumpElementOpType;
@property(retain, nonatomic) NSString *pageUnderJumpElementIcon; // @dynamic pageUnderJumpElementIcon;
@property(retain, nonatomic) CardMiniAppInfo *pageUnderJumpElementMiniAppInfo; // @dynamic pageUnderJumpElementMiniAppInfo;
@property(retain, nonatomic) NSString *pageUnderJumpElementNativeUrl; // @dynamic pageUnderJumpElementNativeUrl;
@property(retain, nonatomic) NSString *pageUnderJumpElementSkipWording; // @dynamic pageUnderJumpElementSkipWording;
@property(retain, nonatomic) NSString *pageUnderJumpElementUrl; // @dynamic pageUnderJumpElementUrl;
@property(retain, nonatomic) NSString *pageUnderJumpElementWording; // @dynamic pageUnderJumpElementWording;

@end

