//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface MemberQAUserPagePreviewData : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int joinedMonths; // @dynamic joinedMonths;
@property(nonatomic) unsigned int joinedSeconds; // @dynamic joinedSeconds;

@end

