//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol MJComposingTextPageSheetViewControllerDelegate <NSObject>
- (void)textPageSheetViewControllerDidClose:(_Bool)arg1;
- (void)textPageSheetViewControllerWillClose:(_Bool)arg1;
@end

