//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MJImagePickerAssetInfo : NSObject
{
    _Bool _isAppleProResCodec;
    _Bool _isP3DisplayColorSpace;
    int _index;
    NSString *_assetID;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isP3DisplayColorSpace; // @synthesize isP3DisplayColorSpace=_isP3DisplayColorSpace;
@property(readonly, nonatomic) _Bool isAppleProResCodec; // @synthesize isAppleProResCodec=_isAppleProResCodec;
@property(readonly, nonatomic) int index; // @synthesize index=_index;
@property(readonly, nonatomic) NSString *assetID; // @synthesize assetID=_assetID;
- (id)initWithAssetID:(id)arg1 index:(int)arg2 isAppleProResCodec:(_Bool)arg3 isP3DisplayColorSpace:(_Bool)arg4;

@end

