//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MJShootComposingFaceManagerView;

@protocol MJShootComposingFaceManagerViewDelegate <NSObject>

@optional
- (void)faceManagerViewDidTapManageFaceID:(MJShootComposingFaceManagerView *)arg1;
- (void)faceManagerViewDidTapApplyFaceID:(MJShootComposingFaceManagerView *)arg1;
- (void)faceManagerViewDidTapCreatingFaceID:(MJShootComposingFaceManagerView *)arg1;
- (void)faceManagerViewDidTapCreateFaceID:(MJShootComposingFaceManagerView *)arg1;
@end

