//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MJShootComposingTemplatePanelView, MJShootingTemplateTabInfo, MMCameraTemplateItem;

@protocol MJShootComposingTemplatePanelViewDelegate <NSObject>

@optional
- (void)shootTemplatePanelView:(MJShootComposingTemplatePanelView *)arg1 didTapTemplateEntryItem:(MMCameraTemplateItem *)arg2;
- (void)shootTemplatePanelView:(MJShootComposingTemplatePanelView *)arg1 didSelectTab:(MJShootingTemplateTabInfo *)arg2 atIndex:(long long)arg3;
- (void)shootTemplatePanelView:(MJShootComposingTemplatePanelView *)arg1 didEndDisplayingTemplateItem:(MMCameraTemplateItem *)arg2 tabID:(unsigned long long)arg3 atIndex:(unsigned long long)arg4 isReloadingData:(_Bool)arg5;
- (void)shootTemplatePanelView:(MJShootComposingTemplatePanelView *)arg1 willDisplayTemplateItem:(MMCameraTemplateItem *)arg2 atIndex:(unsigned long long)arg3 tabID:(unsigned long long)arg4 tabAtIndex:(long long)arg5 isReloadingData:(_Bool)arg6;
- (void)shootTemplatePanelView:(MJShootComposingTemplatePanelView *)arg1 didSelectItem:(MMCameraTemplateItem *)arg2 atIndex:(unsigned long long)arg3 tabID:(unsigned long long)arg4 tabAtIndex:(long long)arg5;
- (void)shootTemplatePanelView:(MJShootComposingTemplatePanelView *)arg1 didReloadTabID:(unsigned long long)arg2 atIndex:(long long)arg3;
@end

