//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMFinderLiveRewardWishView;

@protocol MMFinderLiveRewardWishViewDelegate <NSObject>

@optional
- (void)onClearCurrentLiveRewardWish:(MMFinderLiveRewardWishView *)arg1;
- (void)onUpdateTargetRewardCount:(MMFinderLiveRewardWishView *)arg1;
- (void)onAddTargetRewardGift:(MMFinderLiveRewardWishView *)arg1;
@end

