//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface MMFinderLiveAnchorCouponsView
{
}

- (void)updateWithCoordinator;
- (void)onActionButtonClicked:(id)arg1 view:(id)arg2;
- (id)initWithTaskID:(id)arg1 shopShelfCoordinator:(id)arg2 delegate:(id)arg3;

@end

