//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class ForwardMessageLogicController, NSString;

@interface MMImgFullScreenLogic_Forward
{
    ForwardMessageLogicController *_forwardLogicController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ForwardMessageLogicController *forwardLogicController; // @synthesize forwardLogicController=_forwardLogicController;
- (void)OnForwardMessageSend:(id)arg1;
- (id)getCurrentViewController;
- (void)forwardMessageToContact:(id)arg1;
- (void)tryAddToActionSheet:(id)arg1;
- (id)actionSheetItem;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

