//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CMessageWrap;

@interface MMImgDataItem_Message
{
    CMessageWrap *_msgWrap;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CMessageWrap *msgWrap; // @synthesize msgWrap=_msgWrap;
- (_Bool)forbidDisplay;
- (long long)GetMsgPreviewOpType;
- (_Bool)isSending;
- (_Bool)isLoadingFromICloud;
- (id)mpScreenshotArticleInfo;
- (id)weappScreenshotContextInfo;
- (id)sourceImgInfo;
- (id)aesKey;
- (id)fileId;
- (id)generateWCDataItem;
- (id)generateFavItem;
- (id)generateForwardMsg;
- (id)attachedVideoTitle;
- (id)attachedVideoUrl;
- (unsigned int)attachedVideoType;
- (id)brandMPVideoItem;
- (id)brandMPVideoUrl;
- (id)brandMPVideoSourceDisplayName;
- (id)brandMPVideoSourceUsername;
- (id)brandMPVideoTitle;
- (_Bool)isBrandMPVideo;
- (unsigned int)videoDuration;
- (id)generateRawPlayerInfo;
- (id)generatePlayerInfo;
- (unsigned long long)rawVideoSize;
- (id)rawVideoPath;
- (_Bool)isRawVideo;
- (_Bool)isRawVideoPreviewing;
- (id)videoPath;
- (id)videoThumbImage;
- (_Bool)isFileVideo;
- (unsigned int)hdLivePhotoSize;
- (id)hdLivePhotoPath;
- (id)livePhotoPath;
- (_Bool)isLivePhoto;
- (id)hdImagePath;
- (unsigned int)hdImageSize;
- (id)hdImage;
- (_Bool)isHDImage;
- (id)imagePath;
- (id)image;
- (_Bool)isFileImg;
- (id)thumbImage;
- (id)uuid;
- (id)dataId;
- (unsigned int)type;
- (id)initWithMsgWrap:(id)arg1;

@end

