//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FinderLiveContact, NSString;

@interface MMLiveMentionContactItem : NSObject
{
    _Bool _isFinderRole;
    NSString *_userName;
    NSString *_displayName;
    NSString *_avatarURL;
    FinderLiveContact *_finderLiveContact;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FinderLiveContact *finderLiveContact; // @synthesize finderLiveContact=_finderLiveContact;
@property(nonatomic) _Bool isFinderRole; // @synthesize isFinderRole=_isFinderRole;
@property(copy, nonatomic) NSString *avatarURL; // @synthesize avatarURL=_avatarURL;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;

@end

