//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMLiveBubbleImageComponentInfo, MMWebImageView, NSString;

@interface MMLiveBubbleImageComponent : UIView
{
    MMWebImageView *_imageView;
    MMLiveBubbleImageComponentInfo *_info;
    NSString *_infoRawJSON;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *infoRawJSON; // @synthesize infoRawJSON=_infoRawJSON;
@property(retain, nonatomic) MMLiveBubbleImageComponentInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) MMWebImageView *imageView; // @synthesize imageView=_imageView;
- (void)layoutSubviews;
- (void)applyInfo;
- (void)updateWithJSONString:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

