//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface MMRTCMsgRecordMenuResponder
{
}

- (void)onTextFavorite:(id)arg1;
- (id)getSelectMenuItem;

@end

