//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class BrandTemplateMsgAuthSettingPageModel, NSMutableArray, NSString, TemplateMsgAuthScopesReportModel, WAContactGetter;

@interface MMTemplateMsgAuthScopesViewController
{
    NSMutableArray *_scopeList;
    WAContactGetter *_contactGetter;
    _Bool _hasFillOriginInfoAndReportEnterEvent;
    TemplateMsgAuthScopesReportModel *_templateMsgAuthScopesReportModel;
    _Bool _isGlobalRecv;
    _Bool _isHasGlobalSwitchFooter;
    _Bool _isHasB2CAuthList;
    NSString *_userName;
    NSString *_nickName;
    BrandTemplateMsgAuthSettingPageModel *_settingPageModel;
    unsigned long long _enterScene;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isHasB2CAuthList; // @synthesize isHasB2CAuthList=_isHasB2CAuthList;
@property(nonatomic) _Bool isHasGlobalSwitchFooter; // @synthesize isHasGlobalSwitchFooter=_isHasGlobalSwitchFooter;
@property(nonatomic) unsigned long long enterScene; // @synthesize enterScene=_enterScene;
@property(retain, nonatomic) BrandTemplateMsgAuthSettingPageModel *settingPageModel; // @synthesize settingPageModel=_settingPageModel;
@property(nonatomic) _Bool isGlobalRecv; // @synthesize isGlobalRecv=_isGlobalRecv;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void)reportTemplateMsgAuthScopesOpType:(id)arg1 scopeItem:(id)arg2 templateItems:(id)arg3;
- (id)generateReportTemplateItems;
- (void)fillTemplateMsgAuthScopesReportModelBaseInfo;
- (_Bool)isCurrentSceneNeedDataReporter;
- (_Bool)isWeAppUserName;
- (void)onStrangerContactUpdated:(id)arg1;
- (void)getWeappContactForUsername:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)getNickNameFromLocalOrServer;
- (void)onUpdateScopeGlobalRecv:(_Bool)arg1 forUser:(id)arg2;
- (void)onFetchShowInSettingScopeList:(id)arg1 forUser:(id)arg2 hasSettingEntry:(_Bool)arg3;
- (void)reloadUI;
- (void)tryUpdateKVReportInfo;
- (void)viewDidLoad;
- (void)viewDidBePoped:(_Bool)arg1;
- (id)init;
- (id)initWithConfigModel:(id)arg1;
- (id)initWithEnterScene:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

