//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface NewDesignContactQRCodeInfo : NSObject
{
    UIImage *_qrCodeImage;
    NSString *_qrCodeUrl;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *qrCodeUrl; // @synthesize qrCodeUrl=_qrCodeUrl;
@property(retain, nonatomic) UIImage *qrCodeImage; // @synthesize qrCodeImage=_qrCodeImage;

@end

