//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NewRevokeMsgExtCommontInfoModel, NewRevokeMsgRevokeContentModel;

@interface NewRevokeMsgContentModel : NSObject
{
    NSString *_type;
    NewRevokeMsgRevokeContentModel *_revokemsgcontent;
    NewRevokeMsgExtCommontInfoModel *_extcommoninfo;
}

+ (id)xmlAttributePropertylistForConfigTag:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NewRevokeMsgExtCommontInfoModel *extcommoninfo; // @synthesize extcommoninfo=_extcommoninfo;
@property(retain, nonatomic) NewRevokeMsgRevokeContentModel *revokemsgcontent; // @synthesize revokemsgcontent=_revokemsgcontent;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (id)init;

@end

