//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (AmoebaSafe)
+ (id)amb_safeStringWithString:(id)arg1;
- (id)amb_nonEmptyOrNil;
- (id)amb_safeStringByReplacingCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
@end

