//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (CXXExt)
+ (id)sc_stringWithSTDString:(const void *)arg1;
- (struct basic_string<char, std::char_traits<char>, std::allocator<char>>)sc_stdString;
@end

