//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class OMCTimeline;

@interface OMJDecorPackageParams : NSObject
{
    _Bool _isImageDigiZoomDisabled;
    OMCTimeline *_timeline;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isImageDigiZoomDisabled; // @synthesize isImageDigiZoomDisabled=_isImageDigiZoomDisabled;
@property(readonly, nonatomic) OMCTimeline *timeline; // @synthesize timeline=_timeline;
- (id)initWithTimeline:(id)arg1 isImageDigiZoomDisabled:(_Bool)arg2;

@end

