//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface PictureInfo_CoverInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *cdnUrl; // @dynamic cdnUrl;
@property(retain, nonatomic) NSString *cropInfo; // @dynamic cropInfo;
@property(nonatomic) unsigned int fileId; // @dynamic fileId;
@property(nonatomic) unsigned int height; // @dynamic height;
@property(nonatomic) unsigned int width; // @dynamic width;

@end

