//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class QGPColor;

@interface QGPSetMonoColorCommand
{
    QGPColor *_params;
}

- (void).cxx_destruct;
@property(retain, nonatomic) QGPColor *params; // @synthesize params=_params;

@end

