//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CMessageWrap;

@interface RecordTransferTask
{
    CMessageWrap *_messageWrap;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CMessageWrap *messageWrap; // @synthesize messageWrap=_messageWrap;

@end

