//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSMutableArray;

@interface RoamEncryptKey : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned long long enableEncryptKeyVersion; // @dynamic enableEncryptKeyVersion;
@property(retain, nonatomic) NSMutableArray *keyPair; // @dynamic keyPair;
@property(nonatomic) unsigned long long maxUserPasswordVersion; // @dynamic maxUserPasswordVersion;

@end

