//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSMutableArray;

@interface RTESearchResultInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool isFromDesc; // @dynamic isFromDesc;
@property(nonatomic) unsigned long long location; // @dynamic location;
@property(retain, nonatomic) NSMutableArray *subSearchResultInfos; // @dynamic subSearchResultInfos;
@property(nonatomic) int type; // @dynamic type;

@end

