//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface ScanAIImageIntentResult : NSObject
{
    _Bool _hasObject;
    _Bool _hasFace;
    _Bool _hasText;
    _Bool _hasTranslateIntent;
    long long _intentType;
    unsigned long long _faceCount;
    double _costMS;
    struct CGRect _intentRect;
}

@property(nonatomic) double costMS; // @synthesize costMS=_costMS;
@property(nonatomic) _Bool hasTranslateIntent; // @synthesize hasTranslateIntent=_hasTranslateIntent;
@property(nonatomic) _Bool hasText; // @synthesize hasText=_hasText;
@property(nonatomic) unsigned long long faceCount; // @synthesize faceCount=_faceCount;
@property(nonatomic) _Bool hasFace; // @synthesize hasFace=_hasFace;
@property(nonatomic) _Bool hasObject; // @synthesize hasObject=_hasObject;
@property(nonatomic) struct CGRect intentRect; // @synthesize intentRect=_intentRect;
@property(nonatomic) long long intentType; // @synthesize intentType=_intentType;

@end

