//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseRequest, NSData, NSString;

@interface SearchUserAuthReq : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(retain, nonatomic) NSString *keyword; // @dynamic keyword;
@property(nonatomic) _Bool newPage; // @dynamic newPage;
@property(retain, nonatomic) NSData *nextPageData; // @dynamic nextPageData;

@end

