//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MMHeadImageView;

@interface SharePreConfirmHeadCell : UITableViewCell
{
    _Bool _isFakeContact;
    MMHeadImageView *_headImageView;
    CDUnknownBlockType _onClickHeadImageOrUserName;
    CDUnknownBlockType _onViewMsgContent;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType onViewMsgContent; // @synthesize onViewMsgContent=_onViewMsgContent;
@property(copy, nonatomic) CDUnknownBlockType onClickHeadImageOrUserName; // @synthesize onClickHeadImageOrUserName=_onClickHeadImageOrUserName;
@property(nonatomic) _Bool isFakeContact; // @synthesize isFakeContact=_isFakeContact;
@property(retain, nonatomic) MMHeadImageView *headImageView; // @synthesize headImageView=_headImageView;
- (id)genHeadImageViewWithContract:(id)arg1;
- (void)updateWithContact:(id)arg1 showArrow:(_Bool)arg2 showLine:(_Bool)arg3;
- (void)layoutSubviews;

@end

