//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SightLocalViewSliderMaskView;

@protocol SightLocalViewSliderMaskViewDelegate <NSObject>

@optional
- (void)trackingWithTouch:(_Bool)arg1;
- (_Bool)canMoveStartAndEndFlag;
- (_Bool)queryIsCropAllowEnlarge;
- (_Bool)queryIsSystemCrop;
- (void)shouldSwitchToLargeMode:(_Bool)arg1;
- (void)thumbImagesCollectionViewContentInsetNeedChange;
- (void)sightLocalViewSliderMaskView:(SightLocalViewSliderMaskView *)arg1 didStopMovingAtPosition:(double)arg2 isStartFlag:(_Bool)arg3;
- (void)sightLocalViewSliderMaskViewPlayFlagDidChange:(SightLocalViewSliderMaskView *)arg1;
@end

