//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface SnsMusicInfo_SnsMusicLyricInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *lyricsContent; // @dynamic lyricsContent;
@property(nonatomic) unsigned int startPlayTime; // @dynamic startPlayTime;

@end

