//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSMutableDictionary;

@interface StreamInputResult
{
    NSMutableDictionary *_results;
}

+ (id)filterVoiceTransResult:(id)arg1 withVoiceId:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *results; // @synthesize results=_results;
- (id)GetKeywordTimeResult;
- (id)sortSteamInputResult;
- (id)GetResultString;
- (void)UpdateVoiceTransResult:(id)arg1;
- (id)init;

@end

