//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SysNewXml_ForBizUtility : NSObject
{
}

+ (id)parseNewSucceedContactWindowNode:(struct XmlReaderNode_t *)arg1;
+ (id)parseSucceedContactWindowNode:(struct XmlReaderNode_t *)arg1;

@end

