//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TencentLBSChinaRegion : NSObject
{
}

+ (_Bool)isInChinaWithLatitude:(double)arg1 longitude:(double)arg2;
+ (_Bool)isInChinaPolygonWithLatitude:(double)arg1 longitude:(double)arg2;

@end

