//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TextStateRealTimeReportRequest : NSObject
{
}

+ (void)reportDataWithSchemaId:(unsigned int)arg1 jsonString:(id)arg2;

@end

