//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TextLayoutDelegate <NSObject>
- (unsigned int)perferedLinkTextVisiableLength;
- (_Bool)shouldOpenNewLineAtY:(double)arg1 withLineHeight:(double)arg2;
- (double)lineWidthAtY:(double)arg1 lineIndex:(long long)arg2 lineHeight:(double)arg3;
- (double)originXForLineAtHeight:(double)arg1;
@end

