//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class UIImage;

@interface TextStateImagePickResult : NSObject
{
    UIImage *_image;
    long long _source;
}

- (void).cxx_destruct;
@property(nonatomic) long long source; // @synthesize source=_source;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;

@end

