//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AudioFrameMetaInfo, NSData, NSError, NSString, TPVideoFrameBuffer, TingBizPlayer, TingPlayerDisplayElement;

@protocol TingBizPlayerDelegate <NSObject>

@optional
- (void)tingBizPlayerGetAudioMetaInfo:(AudioFrameMetaInfo *)arg1 listenId:(NSString *)arg2 listenType:(int)arg3;
- (void)tingBizPlayerAudioFrameOut:(NSData *)arg1 metaInfo:(AudioFrameMetaInfo *)arg2;
- (void)tingBizPlayerOnDisplayViewMTKViewCreated:(TingBizPlayer *)arg1;
- (void)tingBizPlayer:(TingBizPlayer *)arg1 onDisplayFrameBufferOut:(TPVideoFrameBuffer *)arg2;
- (void)tingBizPlayer:(TingBizPlayer *)arg1 onDisplayElementAvailable:(TingPlayerDisplayElement *)arg2;
- (void)tingBizPlayer:(TingBizPlayer *)arg1 playRateChanged:(float)arg2;
- (void)tingBizPlayer:(TingBizPlayer *)arg1 onInfoEvent:(int)arg2 error:(NSString *)arg3;
- (void)tingBizPlayer:(TingBizPlayer *)arg1 onEvent:(int)arg2 error:(NSError *)arg3;
- (void)tingBizPlayer:(TingBizPlayer *)arg1 updateCurrentTime:(double)arg2 displayTime:(double)arg3 duration:(double)arg4;
@end

