//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@interface TingURTingImageUtilsCpp
{
}

+ (id)hsva2rgba:(id)arg1;
+ (id)rgba2hsva:(id)arg1;
+ (id)sharedInstance;
- (void)imageColorsAsync:(id)arg1 imageInfo:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)generateMinibarBackground:(id)arg1 imageInfo:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)generatePlayerBackground:(id)arg1 imageInfo:(id)arg2 isMusic:(_Bool)arg3 callback:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

