//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@interface UDRCryptoUtil
{
    NSString *ACCESS_RES_GROUP;
}

- (void).cxx_destruct;
- (int)AesGcmEncrypt:(id)arg1 nonce_size:(unsigned long long)arg2 key:(id)arg3 key_size:(unsigned long long)arg4 aad:(id)arg5 aad_size:(unsigned long long)arg6 input:(id)arg7 input_size:(unsigned long long)arg8 output:(void *)arg9 outtag:(void *)arg10;
- (int)AesGcmDecrypt:(id)arg1 nonce_size:(unsigned long long)arg2 key:(id)arg3 key_size:(unsigned long long)arg4 aad:(id)arg5 aad_size:(unsigned long long)arg6 input:(id)arg7 input_size:(unsigned long long)arg8 tag:(id)arg9 tag_size:(unsigned long long)arg10 output:(void *)arg11;
- (void)deleteAESKeyInKeyChain:(id)arg1 name:(id)arg2 version:(unsigned int)arg3;
- (void)saveAESKeyInKeyChain:(id)arg1 projectId:(id)arg2 name:(id)arg3 version:(unsigned int)arg4;
- (id)getAESKeyInKeyChain:(id)arg1 name:(id)arg2 version:(unsigned int)arg3;
- (void)dealloc;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

