//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSMutableArray, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface UDRLoginListener
{
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    _Bool _initialized;
    NSMutableArray *_pendingCallbacks;
}

- (void).cxx_destruct;
- (void)repeatCheckUDRUpdate;
- (void)waitForInitialization:(CDUnknownBlockType)arg1;
- (void)dealAccountIn;
- (void)dealLogout;
- (void)checkUDRUpdate;
- (void)dealloc;
- (void)onServiceClearData;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

