//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (GCExtendWidth)
- (void)extendWidthToFitWithMaxWidth:(double)arg1;
- (void)extendWidthToFit;
@end

