//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString, UnionTransferJumpInfo;

@interface UnionTransferTextInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) UnionTransferJumpInfo *jumpInfo; // @dynamic jumpInfo;
@property(retain, nonatomic) NSString *wording; // @dynamic wording;

@end

