//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface V2TXLiveAudioFrameObserverFormat : NSObject
{
    int _sampleRate;
    int _channel;
    int _samplesPerCall;
    long long _mode;
}

@property(nonatomic) long long mode; // @synthesize mode=_mode;
@property(nonatomic) int samplesPerCall; // @synthesize samplesPerCall=_samplesPerCall;
@property(nonatomic) int channel; // @synthesize channel=_channel;
@property(nonatomic) int sampleRate; // @synthesize sampleRate=_sampleRate;

@end

