//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface VoipInvitedUserInfoStruct : NSObject
{
    int _type;
    NSString *_username;
}

+ (id)initWithUserName:(id)arg1 type:(int)arg2;
- (void).cxx_destruct;
@property(nonatomic) int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;

@end

