//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface VoIPCallAvatarPlaceholderSet : NSObject
{
    struct __CVBuffer *_mainWindowBuffer;
    struct __CVBuffer *_subWindowBuffer;
    struct __CVBuffer *_splitHalfBuffer;
}

@property(nonatomic) struct __CVBuffer *splitHalfBuffer; // @synthesize splitHalfBuffer=_splitHalfBuffer;
@property(nonatomic) struct __CVBuffer *subWindowBuffer; // @synthesize subWindowBuffer=_subWindowBuffer;
@property(nonatomic) struct __CVBuffer *mainWindowBuffer; // @synthesize mainWindowBuffer=_mainWindowBuffer;
- (struct __CVBuffer *)bufferForStyle:(long long)arg1;
- (void)dealloc;

@end

