//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WAAgentExpiredCardInfo : NSObject
{
    unsigned int _containerId;
    NSString *_expiredText;
}

+ (id)infoWithContainerId:(unsigned int)arg1 expiredText:(id)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *expiredText; // @synthesize expiredText=_expiredText;
@property(nonatomic) unsigned int containerId; // @synthesize containerId=_containerId;
- (id)description;

@end

