//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MagicSclFrameSetView, NSString, UIImage;

@protocol WAAgentFrameSetViewObserver <NSObject>

@optional
- (void)onCardSnapshot:(unsigned int)arg1 image:(UIImage *)arg2;
- (void)onDismissHalfScreenCard:(unsigned int)arg1;
- (void)onPresentCardInHalfScreen:(NSString *)arg1 containerId:(unsigned int)arg2;
- (void)onUpdateCardRelatedPage:(unsigned int)arg1 appId:(NSString *)arg2 path:(NSString *)arg3 envVersion:(NSString *)arg4;
- (void)onCardExpired:(NSString *)arg1 containerId:(unsigned int)arg2;
- (void)onFrameSetViewDestroyedForContainerId:(unsigned int)arg1;
- (void)onFrameSetViewCreated:(MagicSclFrameSetView *)arg1 frameId:(unsigned int)arg2 containerId:(unsigned int)arg3;
@end

