//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WCUIAlertView;

@interface WAJSEventHandler_editTextWithPopForm
{
    WCUIAlertView *_editTextView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCUIAlertView *editTextView; // @synthesize editTextView=_editTextView;
- (void)onEditTextViewConfirmed;
- (void)onEditTextViewCancelled;
- (void)handleJSEvent:(id)arg1;

@end

