//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface WASinglePickerView
{
}

- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (void)updatePickerView:(id)arg1 current:(long long)arg2 column:(long long)arg3;
- (long long)numberOfComponentsInPickerView:(id)arg1;

@end

