//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class WCAdBiddingSliderCardStyleConfig;

@interface WCAdBiddingSliderCardFlowLayout : UICollectionViewFlowLayout
{
    _Bool _hasFooter;
    _Bool _isInitialized;
    WCAdBiddingSliderCardStyleConfig *_config;
    double _exposedWidthSlot1;
    double _exposedWidthSlot2;
    struct CGSize _topItemSizeInternal;
}

+ (Class)layoutAttributesClass;
- (void).cxx_destruct;
@property(nonatomic) _Bool isInitialized; // @synthesize isInitialized=_isInitialized;
@property(nonatomic) struct CGSize topItemSizeInternal; // @synthesize topItemSizeInternal=_topItemSizeInternal;
@property(nonatomic) _Bool hasFooter; // @synthesize hasFooter=_hasFooter;
@property(nonatomic) double exposedWidthSlot2; // @synthesize exposedWidthSlot2=_exposedWidthSlot2;
@property(nonatomic) double exposedWidthSlot1; // @synthesize exposedWidthSlot1=_exposedWidthSlot1;
@property(retain, nonatomic) WCAdBiddingSliderCardStyleConfig *config; // @synthesize config=_config;
- (id)footerAttributesWithLastCard:(id)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (double)slideXForVisibleIndex:(long long)arg1 progress:(double)arg2 sf:(double)arg3;
- (double)spacingOffsetForVisibleIndex:(long long)arg1 sf:(double)arg2;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;
- (struct CGSize)collectionViewContentSize;
@property(readonly, nonatomic) struct CGSize topItemSize;
- (void)prepareLayout;
- (id)init;

@end

