//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCAdConversionOnlineEventExtModel : NSObject
{
    int _enterScene;
    NSString *_canvasId;
    NSString *_adExtInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *adExtInfo; // @synthesize adExtInfo=_adExtInfo;
@property(nonatomic) int enterScene; // @synthesize enterScene=_enterScene;
@property(retain, nonatomic) NSString *canvasId; // @synthesize canvasId=_canvasId;

@end

