//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIImage;

@protocol WCFinderHeadImageViewLoadExtension <NSObject>

@optional
- (void)finderHeadImageLoadSuccessfulWithImage:(UIImage *)arg1 targetSize:(unsigned long long)arg2;
@end

