//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AVAsset, EditVideoAttr, NSArray, NSString, UIImage, WCFinderVideoQualityScoreModel;

@interface WCFinderGenOptionParams : NSObject
{
    _Bool _isSlowMotionVideo;
    WCFinderVideoQualityScoreModel *_videoScoreModel;
    EditVideoAttr *_editAttr;
    NSArray *_selectedAssetIDs;
    AVAsset *_fromAvAsset;
    NSString *_postFinderUsername;
    NSString *_originalVideoPath;
    UIImage *_specifiedCoverImage;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImage *specifiedCoverImage; // @synthesize specifiedCoverImage=_specifiedCoverImage;
@property(copy, nonatomic) NSString *originalVideoPath; // @synthesize originalVideoPath=_originalVideoPath;
@property(copy, nonatomic) NSString *postFinderUsername; // @synthesize postFinderUsername=_postFinderUsername;
@property(retain, nonatomic) AVAsset *fromAvAsset; // @synthesize fromAvAsset=_fromAvAsset;
@property(nonatomic) _Bool isSlowMotionVideo; // @synthesize isSlowMotionVideo=_isSlowMotionVideo;
@property(retain, nonatomic) NSArray *selectedAssetIDs; // @synthesize selectedAssetIDs=_selectedAssetIDs;
@property(retain, nonatomic) EditVideoAttr *editAttr; // @synthesize editAttr=_editAttr;
@property(retain, nonatomic) WCFinderVideoQualityScoreModel *videoScoreModel; // @synthesize videoScoreModel=_videoScoreModel;

@end

