//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol WCFinderVideoStatusExt <NSObject>

@optional
- (void)onFinderFeedVideoStopWithTid:(NSString *)arg1 stopPlaybackTime:(double)arg2;
@end

