//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderPostDirectUploadConfigBuilder : NSObject
{
}

+ (id)codecBlacklistFromString:(id)arg1;
+ (long long)millisecondsFromSeconds:(long long)arg1;
+ (long long)bytesFromMegaBytes:(long long)arg1;
+ (unsigned long long)experimentGroupFromRawValue:(long long)arg1;
+ (id)buildConfig;

@end

