//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WCFinderFeedImageView;

@protocol WCFinderFeedImageViewProtocol <NSObject>

@optional
- (void)feedImageViewLoadSuc:(WCFinderFeedImageView *)arg1;
- (void)loadingRetry;
@end

