//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, WCFinderBusinessCurrentRedDotInfo;

@interface WCFinderBusinessFeatureInfo : NSObject
{
    _Bool _isOpen;
    int _businessType;
    long long _locationIndex;
    long long _exitInterval;
    long long _consumeReddotInterval;
    long long _exposeReddotInterval;
    NSMutableArray *_clickWithReddotCountArray;
    NSMutableArray *_clickWithoutReddotCountArray;
    NSMutableArray *_clickStay3sCountArray;
    NSMutableArray *_stayDurationArray;
    NSMutableArray *_reddotExposeCountArray;
    NSMutableArray *_noneReddotExposeCountArray;
    NSMutableArray *_reddotCtrValueArray;
    NSMutableArray *_noneReddotCtrValueArray;
    NSMutableArray *_lastPeriodClickIntervalArray;
    NSMutableArray *_lastPeriodExposeIntervalArray;
    unsigned long long _last64ClickExposeSequence;
    WCFinderBusinessCurrentRedDotInfo *_currentRedDotInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderBusinessCurrentRedDotInfo *currentRedDotInfo; // @synthesize currentRedDotInfo=_currentRedDotInfo;
@property(nonatomic) unsigned long long last64ClickExposeSequence; // @synthesize last64ClickExposeSequence=_last64ClickExposeSequence;
@property(retain, nonatomic) NSMutableArray *lastPeriodExposeIntervalArray; // @synthesize lastPeriodExposeIntervalArray=_lastPeriodExposeIntervalArray;
@property(retain, nonatomic) NSMutableArray *lastPeriodClickIntervalArray; // @synthesize lastPeriodClickIntervalArray=_lastPeriodClickIntervalArray;
@property(retain, nonatomic) NSMutableArray *noneReddotCtrValueArray; // @synthesize noneReddotCtrValueArray=_noneReddotCtrValueArray;
@property(retain, nonatomic) NSMutableArray *reddotCtrValueArray; // @synthesize reddotCtrValueArray=_reddotCtrValueArray;
@property(retain, nonatomic) NSMutableArray *noneReddotExposeCountArray; // @synthesize noneReddotExposeCountArray=_noneReddotExposeCountArray;
@property(retain, nonatomic) NSMutableArray *reddotExposeCountArray; // @synthesize reddotExposeCountArray=_reddotExposeCountArray;
@property(retain, nonatomic) NSMutableArray *stayDurationArray; // @synthesize stayDurationArray=_stayDurationArray;
@property(retain, nonatomic) NSMutableArray *clickStay3sCountArray; // @synthesize clickStay3sCountArray=_clickStay3sCountArray;
@property(retain, nonatomic) NSMutableArray *clickWithoutReddotCountArray; // @synthesize clickWithoutReddotCountArray=_clickWithoutReddotCountArray;
@property(retain, nonatomic) NSMutableArray *clickWithReddotCountArray; // @synthesize clickWithReddotCountArray=_clickWithReddotCountArray;
@property(nonatomic) long long exposeReddotInterval; // @synthesize exposeReddotInterval=_exposeReddotInterval;
@property(nonatomic) long long consumeReddotInterval; // @synthesize consumeReddotInterval=_consumeReddotInterval;
@property(nonatomic) long long exitInterval; // @synthesize exitInterval=_exitInterval;
@property(nonatomic) long long locationIndex; // @synthesize locationIndex=_locationIndex;
@property(nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(nonatomic) int businessType; // @synthesize businessType=_businessType;
- (id)genReportFloatByContainerArray:(id)arg1;
- (id)genReportByContainerArray:(id)arg1;
- (id)genReportJson;
- (id)initWithBusinessType:(int)arg1;

@end

