//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMUIButton, NSMutableArray, NSString, UIButton, UILabel, WCFinderFeedHighlightStyle, WCFinderJumpInfoPanelView, WCFinderProgressBar, WCFinderProgressControlPanelConfigParamsModel, WCFinderProgressSpritesView, WCFinderSkipForwardBackwardButton, WCFinderTimeLabel;
@protocol WCFinderProgressPanelViewDelegate;

@interface WCFinderProgressPanelView : UIView
{
    id <WCFinderProgressPanelViewDelegate> _delegate;
    MMUIButton *_pauseButton;
    UIButton *_playRateButton;
    UIButton *_bulletButton;
    MMUIButton *_subtitleButton;
    MMUIButton *_backButton;
    WCFinderProgressBar *_progressBar;
    WCFinderJumpInfoPanelView *_leftJumpInfoPanelView;
    UILabel *_currentHighlightTitleLabel;
    WCFinderTimeLabel *_timeLabel;
    NSMutableArray *_leftJumpInfoArray;
    WCFinderFeedHighlightStyle *_highlightStyleInfo;
    WCFinderProgressControlPanelConfigParamsModel *_paramsModel;
    WCFinderProgressSpritesView *_progressPreviewView;
    WCFinderSkipForwardBackwardButton *_skipForwardBtn;
    WCFinderSkipForwardBackwardButton *_skipBackwardBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderSkipForwardBackwardButton *skipBackwardBtn; // @synthesize skipBackwardBtn=_skipBackwardBtn;
@property(retain, nonatomic) WCFinderSkipForwardBackwardButton *skipForwardBtn; // @synthesize skipForwardBtn=_skipForwardBtn;
@property(retain, nonatomic) WCFinderProgressSpritesView *progressPreviewView; // @synthesize progressPreviewView=_progressPreviewView;
@property(retain, nonatomic) WCFinderProgressControlPanelConfigParamsModel *paramsModel; // @synthesize paramsModel=_paramsModel;
@property(retain, nonatomic) WCFinderFeedHighlightStyle *highlightStyleInfo; // @synthesize highlightStyleInfo=_highlightStyleInfo;
@property(retain, nonatomic) NSMutableArray *leftJumpInfoArray; // @synthesize leftJumpInfoArray=_leftJumpInfoArray;
@property(retain, nonatomic) WCFinderTimeLabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *currentHighlightTitleLabel; // @synthesize currentHighlightTitleLabel=_currentHighlightTitleLabel;
@property(retain, nonatomic) WCFinderJumpInfoPanelView *leftJumpInfoPanelView; // @synthesize leftJumpInfoPanelView=_leftJumpInfoPanelView;
@property(retain, nonatomic) WCFinderProgressBar *progressBar; // @synthesize progressBar=_progressBar;
@property(retain, nonatomic) MMUIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) MMUIButton *subtitleButton; // @synthesize subtitleButton=_subtitleButton;
@property(retain, nonatomic) UIButton *bulletButton; // @synthesize bulletButton=_bulletButton;
@property(retain, nonatomic) UIButton *playRateButton; // @synthesize playRateButton=_playRateButton;
@property(retain, nonatomic) MMUIButton *pauseButton; // @synthesize pauseButton=_pauseButton;
@property(nonatomic) __weak id <WCFinderProgressPanelViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)finderJumpInfoPanelViewGetContentVM;
- (void)onFinderJumpInfoViewDidClick:(id)arg1;
- (_Bool)isNewLoading;
- (_Bool)isAnimating;
- (void)stopLoading;
- (void)startLoading;
- (void)onVoiceOverStatusChanged;
- (void)removeNotification;
- (void)setupNotification;
- (void)onClickSkipBackwardBtn:(id)arg1;
- (void)onClickSkipForwardBtn:(id)arg1;
- (void)onClickBackButton:(id)arg1;
- (void)onClickSubtitleButton:(id)arg1;
- (void)onClickBulletButton:(id)arg1;
- (void)onChangePlayRate:(id)arg1;
- (void)onClickPauseButton:(id)arg1;
- (id)dynamicWhiteColor;
- (id)fontOfSize:(double)arg1;
- (id)dynamicFontOfSize:(double)arg1;
- (id)lightWhiteColor;
- (void)updateProgressPreviewPercent:(double)arg1;
- (void)updateProgressPreviewHiddenStateIfNeeded:(_Bool)arg1;
- (void)onPlayerProgressBarCurPlayPrecent:(double)arg1 dragState:(unsigned long long)arg2;
- (id)genSkipButtonReportDictWithEventID:(id)arg1;
- (id)genReportDict;
- (void)debugSetProgressPreviewWithPrecent:(double)arg1;
@property(readonly, nonatomic) _Bool shouldIgnoreLeftJumpInfo;
@property(readonly, nonatomic) _Bool canShowLeftJumpInfoPanelView;
- (_Bool)isShowing;
- (void)resetUIViewState;
- (void)updateProgressBarValueWithCurrentPlayProgress:(double)arg1;
- (_Bool)isLandScapePanelView;
- (void)_handleClickSkipBackwardBtn;
- (void)_handleClickSkipForwardBtn;
- (void)layoutProgressBar;
- (void)checkProgressBarStatus;
- (void)_udpateProgressSubViewHiddenState;
- (void)updateProgressElementsWithCurrentPlayPosition:(double)arg1 videoDuration:(double)arg2 forbidProgressBarMovAnim:(_Bool)arg3 contentVM:(id)arg4 manual:(_Bool)arg5;
- (void)updateConfig;
- (void)updateHighlightTitleLabelWithCurrentPlayPos:(double)arg1;
- (void)updateTimeLabelWithCurrentPlayPos:(double)arg1 videoTotalTime:(double)arg2 layoutBlock:(CDUnknownBlockType)arg3;
- (void)refreshBulletButtonIcon;
- (id)currentBulletButtonIconName;
- (void)updateSubviewsStyle;
- (void)updateUIStateWithPaused:(_Bool)arg1;
- (void)configLeftJumpInfoPanelView;
- (void)checkAndUpdateHighlightStyleInfo;
- (void)globalUpdatePanelWithParams:(id)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)responseToHitGes:(struct CGPoint)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

