//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIColor, UIFont, WCFinderRichTextConfig, WCFinderRichTextStyleGroup, WCFinderSizingRichTextView;
@protocol WCFinderSizingRichTextDelegate;

@interface WCFinderSizingRichTextLayout : NSObject
{
    _Bool _showExpand;
    _Bool _trimContent;
    _Bool _alwaysDisplayExpand;
    _Bool _isExpanded;
    id <WCFinderSizingRichTextDelegate> _delegate;
    NSString *_content;
    NSString *_closureContent;
    NSString *_trailingLinkColor;
    long long _lineNumber;
    long long _expandLimitNumber;
    WCFinderRichTextConfig *_config;
    NSString *_expandWording;
    NSString *_expandedSuffix;
    WCFinderRichTextConfig *_suffixConfig;
    double _expandedSuffixPadding;
    WCFinderSizingRichTextView *_attachedView;
    unsigned long long _contentHash;
    WCFinderRichTextStyleGroup *_sizedStyle;
    WCFinderRichTextStyleGroup *_unboundedStyle;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderRichTextStyleGroup *unboundedStyle; // @synthesize unboundedStyle=_unboundedStyle;
@property(retain, nonatomic) WCFinderRichTextStyleGroup *sizedStyle; // @synthesize sizedStyle=_sizedStyle;
@property(nonatomic) unsigned long long contentHash; // @synthesize contentHash=_contentHash;
@property(nonatomic) __weak WCFinderSizingRichTextView *attachedView; // @synthesize attachedView=_attachedView;
@property(nonatomic) _Bool isExpanded; // @synthesize isExpanded=_isExpanded;
@property(nonatomic) double expandedSuffixPadding; // @synthesize expandedSuffixPadding=_expandedSuffixPadding;
@property(retain, nonatomic) WCFinderRichTextConfig *suffixConfig; // @synthesize suffixConfig=_suffixConfig;
@property(retain, nonatomic) NSString *expandedSuffix; // @synthesize expandedSuffix=_expandedSuffix;
@property(retain, nonatomic) NSString *expandWording; // @synthesize expandWording=_expandWording;
@property(retain, nonatomic) WCFinderRichTextConfig *config; // @synthesize config=_config;
@property(nonatomic) long long expandLimitNumber; // @synthesize expandLimitNumber=_expandLimitNumber;
@property(nonatomic) long long lineNumber; // @synthesize lineNumber=_lineNumber;
@property(retain, nonatomic) NSString *trailingLinkColor; // @synthesize trailingLinkColor=_trailingLinkColor;
@property(nonatomic) _Bool alwaysDisplayExpand; // @synthesize alwaysDisplayExpand=_alwaysDisplayExpand;
@property(retain, nonatomic) NSString *closureContent; // @synthesize closureContent=_closureContent;
@property(nonatomic) _Bool trimContent; // @synthesize trimContent=_trimContent;
@property(nonatomic) _Bool showExpand; // @synthesize showExpand=_showExpand;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) __weak id <WCFinderSizingRichTextDelegate> delegate; // @synthesize delegate=_delegate;
- (id)displayText;
- (void)_checkHeightChange:(CDUnknownBlockType)arg1;
- (void)_onClickClosure;
- (void)_onClickExpand;
- (id)trailLinkColorXML;
- (struct CGSize)intrinsicContentSize;
- (void)applyWidth:(double)arg1;
- (id)_trimText:(id)arg1;
- (id)styleForWidth:(double)arg1;
- (void)_updateContentHash;
- (void)_onAttrsChanged:(id)arg1 changes:(id)arg2;
- (void)updateSuffixTextConfig:(CDUnknownBlockType)arg1;
- (void)updateTextConfig:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) UIColor *dynamicIconDefaultColor;
@property(retain, nonatomic) UIFont *font;
@property(retain, nonatomic) UIColor *textColor;
@property(nonatomic) double lineSpacing;
@property(nonatomic) long long parserType;
@property(readonly, nonatomic) _Bool showExpandClosure;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

