//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WCFinderComment;

@protocol WCFinderCommentPostMgrDelegate <NSObject>

@optional
- (void)finderCommentPostSuccessfulWitComment:(WCFinderComment *)arg1;
- (void)finderCommentPostFailWithComment:(WCFinderComment *)arg1;
- (void)finderCommentStartPostWithComment:(WCFinderComment *)arg1;
@end

