//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSMutableArray;
@protocol WCMiddleImageTaskDelegate;

@interface WCMiddleImageTaskOperation
{
    NSMutableArray *_taskArray;
    id <WCMiddleImageTaskDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <WCMiddleImageTaskDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSMutableArray *taskArray; // @synthesize taskArray=_taskArray;
- (void)runLoop;
- (void)startOperation;
- (void)setDontPause;
- (id)initWithTaskArray:(id)arg1;

@end

