//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WCMomentsPlayerSourceController;

@protocol WCMomentsPlayerSourceControllerDelegate <NSObject>

@optional
- (void)playerSourceController:(WCMomentsPlayerSourceController *)arg1 didChangeSourceStatus:(long long)arg2;
@end

