//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class ContactTagData, MMUILabel, UIButton, UIColor, UIImageView, UIView;

@interface WCMomentsContactTagCombinedCell
{
    _Bool _hideDetailButton;
    UIColor *_checkboxSelectedColor;
    UIImageView *_leftCheckMark;
    UIButton *_rightDetailBtn;
    UIView *_seperatorLine;
    MMUILabel *_nameLabel;
    MMUILabel *_memberLabel;
    MMUILabel *_memberCountLabel;
    ContactTagData *_tagData;
}

+ (id)cellIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) ContactTagData *tagData; // @synthesize tagData=_tagData;
@property(retain, nonatomic) MMUILabel *memberCountLabel; // @synthesize memberCountLabel=_memberCountLabel;
@property(retain, nonatomic) MMUILabel *memberLabel; // @synthesize memberLabel=_memberLabel;
@property(retain, nonatomic) MMUILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *seperatorLine; // @synthesize seperatorLine=_seperatorLine;
@property(retain, nonatomic) UIButton *rightDetailBtn; // @synthesize rightDetailBtn=_rightDetailBtn;
@property(retain, nonatomic) UIImageView *leftCheckMark; // @synthesize leftCheckMark=_leftCheckMark;
@property(nonatomic) _Bool hideDetailButton; // @synthesize hideDetailButton=_hideDetailButton;
@property(retain, nonatomic) UIColor *checkboxSelectedColor; // @synthesize checkboxSelectedColor=_checkboxSelectedColor;
- (void)onClickDetail:(id)arg1;
- (void)layoutSubviews;
- (void)setupViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)updateCheckState:(_Bool)arg1;
- (void)updateContactTag:(id)arg1 checked:(_Bool)arg2 query:(id)arg3 dicSearchMatchTip:(id)arg4 clickedDetail:(CDUnknownBlockType)arg5;
- (void)updateContactTag:(id)arg1 checked:(_Bool)arg2 query:(id)arg3 clickedDetail:(CDUnknownBlockType)arg4;
- (void)updateContactTag:(id)arg1 checked:(_Bool)arg2 clickedDetail:(CDUnknownBlockType)arg3;

@end

