//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DrawLotteryResponse, NSString;

@protocol WCPayF2FDrawLotteryCgiDelegate <NSObject>
- (void)OnF2FDrawLotteryRepsonseError:(NSString *)arg1 errorCode:(unsigned int)arg2;
- (void)OnF2FDrawLotteryRepsonseOK:(DrawLotteryResponse *)arg1;
@end

