//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCPayThirdC2CMsgCenter : NSObject
{
}

+ (_Bool)handleThirdC2CRouteInfo:(id)arg1;
+ (_Bool)handleClickMessage:(id)arg1;

@end

