//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCShareItemUtils : NSObject
{
}

+ (void)jumpToOtherApp:(long long)arg1 scene:(long long)arg2 objects:(id)arg3 params:(id)arg4 completionHandler:(CDUnknownBlockType)arg5 cleanupHandler:(CDUnknownBlockType)arg6;
+ (void)jumpToOtherApp:(long long)arg1 scene:(long long)arg2 objects:(id)arg3 params:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
+ (void)jumpToYuanbaoWithScene:(long long)arg1 objects:(id)arg2 params:(id)arg3 completionHandler:(CDUnknownBlockType)arg4 cleanupHandler:(CDUnknownBlockType)arg5;
+ (void)jumpToYuanbaoWithScene:(long long)arg1 objects:(id)arg2 params:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
+ (id)getMagicAdPosIdWithScene:(long long)arg1;
+ (id)getGVersionWithScene:(long long)arg1;
+ (id)getUrlParamsWithScene:(long long)arg1;
+ (void)jumpToYuanbaoWithFileMessage:(id)arg1 reportParams:(id)arg2;
+ (void)jumpToYuanbaoWithCDNFileMessage:(id)arg1 scene:(long long)arg2 params:(id)arg3;
+ (void)jumpToYuanbaoWithFileName:(id)arg1 filePath:(id)arg2 scene:(long long)arg3 params:(id)arg4;
+ (void)jumpToYuanbaoWithContent:(id)arg1 scene:(long long)arg2 params:(id)arg3;
+ (void)jumpToOtherApp:(long long)arg1 arrMsgWraps:(id)arg2 scene:(long long)arg3 params:(id)arg4 isMergedForward:(_Bool)arg5 completionHandler:(CDUnknownBlockType)arg6;
+ (void)jumpToOtherApp:(long long)arg1 arrMsgWraps:(id)arg2 scene:(long long)arg3 params:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;
+ (void)jumpToOtherApp:(long long)arg1 scene:(long long)arg2 provider:(id)arg3 legacyObjects:(id)arg4 params:(id)arg5 completionHandler:(CDUnknownBlockType)arg6 cleanupHandler:(CDUnknownBlockType)arg7;
+ (_Bool)isUseNewForwardToOtherAppUI;
+ (_Bool)isFoldWeWorkToOtherApp;
+ (_Bool)isOpenSessionSelectForwardYuanbao;
+ (_Bool)isOpenSessionSelectForwardYuanbaoForNewUI;
+ (_Bool)isOpenSessionSelectForwardYuanbaoForOldUI;
+ (void)tryPreloadYuanbaoAdInfoWithMMKVThrottle:(_Bool)arg1;
+ (void)tryPreloadYuanbaoAdInfo;
+ (_Bool)isSystemShareAvailable;
+ (unsigned long long)maxPasteItemCount;
+ (_Bool)isRecordExpandEnabled;
+ (_Bool)isOpenWorkBuddyForward;
+ (_Bool)isOpenQQMailForward;
+ (_Bool)isOpenQQForward;
+ (_Bool)isForwardAllowedByPromotionQuotaForAppType:(long long)arg1;
+ (_Bool)isSystemShareOpenExptEnabledForAppType:(long long)arg1;
+ (_Bool)isYuanbaoPromotionQuotaCheckEnabled;
+ (_Bool)isForwardOpenExptEnabledForAppType:(long long)arg1;
+ (_Bool)isRegInChinaOrHKMO;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

