//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, UIButton;
@protocol WeDropConfirmFooterDelegate;

@interface WeDropConfirmFooterView
{
    id <WeDropConfirmFooterDelegate> _delegate;
    NSString *_confirmTitle;
    UIButton *_confirmBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) NSString *confirmTitle; // @synthesize confirmTitle=_confirmTitle;
@property(nonatomic) __weak id <WeDropConfirmFooterDelegate> delegate; // @synthesize delegate=_delegate;
- (void)onConfirm;
- (void)initSubviews;

@end

