//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSMutableArray;

@interface WeNoteEditorGenerateHtmlReq : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *attachmentIdList; // @dynamic attachmentIdList;
@property(nonatomic) _Bool ignoreEditStatus; // @dynamic ignoreEditStatus;
@property(nonatomic) _Bool saveAsMarkdown; // @dynamic saveAsMarkdown;

@end

