//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6WeChatP33_68F694ED4F81F8D980587F65A49C022A40FinderFavoriteLinkStyleConfigurationView : UIView
{
    MISSING_TYPE *appliedConfiguration;
    MISSING_TYPE *backgroundView;
    MISSING_TYPE *highlightMask;
    MISSING_TYPE *titleLabel;
    MISSING_TYPE *feedCountLabel;
    MISSING_TYPE *channelIconImageView;
    MISSING_TYPE *nicknameLabel;
    MISSING_TYPE *coverImageView;
    MISSING_TYPE *dateLabel;
    MISSING_TYPE *deleteButton;
    MISSING_TYPE *panGesture;
    MISSING_TYPE *longPressGesture;
    MISSING_TYPE *viewElementStartOffset;
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

