//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol _TtP6WeChat27ViewSkeletonUserInteraction_
- (void)ls_recoverUserAction;
- (void)ls_interuptUserAction;
@end

