//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString, ResultCommContent;

@interface BizResult : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *bizUserAttrInfo; // @dynamic bizUserAttrInfo;
@property(retain, nonatomic) ResultCommContent *commContent; // @dynamic commContent;

@end

