//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class BrandFansContactProfileController;

@protocol BrandFansContactProfileControllerDelegate <NSObject>
- (void)clickViewProfileInController:(BrandFansContactProfileController *)arg1;
- (void)clickUnblockContactInController:(BrandFansContactProfileController *)arg1;
- (void)clickBlockContactInController:(BrandFansContactProfileController *)arg1;
- (void)clickViewDetailInController:(BrandFansContactProfileController *)arg1;
@end

