//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class CdnBackupUploadResult, CdnBaseResult, CdnC2cResult, CdnCost, CdnHitCheckResult, CdnNetworkProfile, CdnSnsResult, CdnTransforProfile, NSMutableArray;

@interface CdnUploadResult : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) CdnBackupUploadResult *backup; // @dynamic backup;
@property(retain, nonatomic) CdnBaseResult *base; // @dynamic base;
@property(retain, nonatomic) CdnC2cResult *c2C; // @dynamic c2C;
@property(retain, nonatomic) CdnCost *cost; // @dynamic cost;
@property(retain, nonatomic) NSMutableArray *files; // @dynamic files;
@property(retain, nonatomic) CdnHitCheckResult *hit; // @dynamic hit;
@property(retain, nonatomic) CdnNetworkProfile *network; // @dynamic network;
@property(retain, nonatomic) CdnSnsResult *sns; // @dynamic sns;
@property(retain, nonatomic) CdnTransforProfile *transfor; // @dynamic transfor;

@end

