//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CommonUtility : NSObject
{
}

+ (id)GetRootPathOfTrash;
+ (id)GetRandomPathOfTrash;
+ (unsigned long long)genCurrentTimeInMsFrom1970;
+ (unsigned long long)genCurrentTimeInMs;
+ (id)GetTmpPath;
+ (id)SafeUnarchive:(id)arg1;

@end

