//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface ContactsCommon : NSObject
{
}

+ (_Bool)getContactVerifySwitchOpen;
+ (id)fixContactFullPyAndParseContactKey:(id)arg1;
+ (void)fixContactFullPy:(id)arg1;
+ (id)parseContactKey:(id)arg1 chatRoom:(id)arg2;
+ (id)parseContactKey:(id)arg1;
+ (void)initialize;

@end

