//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class CustomSwitchState, NSString;

@interface CustomSwitchViewData : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool checked; // @dynamic checked;
@property(retain, nonatomic) CustomSwitchState *checkedState; // @dynamic checkedState;
@property(retain, nonatomic) CustomSwitchState *uncheckedState; // @dynamic uncheckedState;
@property(retain, nonatomic) NSString *viewId; // @dynamic viewId;

@end

