//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface EcsCardUtil : NSObject
{
}

+ (id)encryptUserNameForSceneNote:(id)arg1;
+ (unsigned int)getCardReqTypeWithMessage:(id)arg1 isClick:(_Bool)arg2;

@end

