//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class EditImageAttr;

@protocol EditImageForwardAndEditLogicDelegate <NSObject>

@optional
- (void)onEditImageForwardAndEditResult:(EditImageAttr *)arg1;
- (void)onSaveImageSuccessInEditView;
- (void)onSaveImageBeginInEditView;
- (void)onAddFavoritesSuccessInEditView;
- (void)onForwardMessageCancelInEditView;
- (void)onForwardMessageSendOKInEditView;
- (void)onDismissEditView;
- (void)onShowingEditView;
@end

