//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseResponse, FinderLiveErrorPage, FinderRealNameVerifyPrepareInfo, NSString;

@interface FinderRealNameVerifyResponse : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) FinderLiveErrorPage *errPage; // @dynamic errPage;
@property(retain, nonatomic) NSString *faceVerifyUrl; // @dynamic faceVerifyUrl;
@property(nonatomic) unsigned int lastVerifyResult; // @dynamic lastVerifyResult;
@property(nonatomic) unsigned int needFaceVerify; // @dynamic needFaceVerify;
@property(retain, nonatomic) FinderRealNameVerifyPrepareInfo *prepareInfo; // @dynamic prepareInfo;
@property(retain, nonatomic) NSString *verifyUrl; // @dynamic verifyUrl;

@end

