//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface FinderTfLiteSinglePredictResModel : NSObject
{
    _Bool _useCache;
    NSArray *_resArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *resArray; // @synthesize resArray=_resArray;
@property(nonatomic) _Bool useCache; // @synthesize useCache=_useCache;

@end

