//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderWindowProductInfo_DetailPage, NSMutableArray;

@interface FinderLiveShopVipInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) FinderWindowProductInfo_DetailPage *clickPage; // @dynamic clickPage;
@property(retain, nonatomic) NSMutableArray *pagAnimationInfo; // @dynamic pagAnimationInfo;
@property(nonatomic) unsigned int showFlag; // @dynamic showFlag;

@end

