//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface FinderRingtoneConfig : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int notifyFrequencyLimit; // @dynamic notifyFrequencyLimit;
@property(nonatomic) unsigned int setRingtoneFrequencyLimit; // @dynamic setRingtoneFrequencyLimit;
@property(nonatomic) unsigned int showRingtoneDailyMaxcount; // @dynamic showRingtoneDailyMaxcount;
@property(nonatomic) unsigned int showRingtoneDailyMaxcountLessFrequent; // @dynamic showRingtoneDailyMaxcountLessFrequent;
@property(nonatomic) unsigned int thresholdWithName; // @dynamic thresholdWithName;
@property(nonatomic) unsigned int thresholdWithoutName; // @dynamic thresholdWithoutName;
@property(nonatomic) _Bool userpageShowRingtone; // @dynamic userpageShowRingtone;

@end

