//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSData, NSString;

@interface FinderLiveMilestoneLotteryStatusResult_CouponInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *buttonText; // @dynamic buttonText;
@property(retain, nonatomic) NSString *couponExpireTime; // @dynamic couponExpireTime;
@property(retain, nonatomic) NSString *couponId; // @dynamic couponId;
@property(retain, nonatomic) NSData *jumpInfo; // @dynamic jumpInfo;
@property(retain, nonatomic) NSString *relatedProductId; // @dynamic relatedProductId;

@end

