//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class BrandTLExptConfig, CMessageWrap, NSString;

@interface FlutterBizPublishViewController
{
    _Bool isShowRedDotInMainFrameSession;
    unsigned int redDotCount;
    unsigned int enterSessionInfoNotifyType;
    BrandTLExptConfig *exptConfig;
    unsigned long long source;
    unsigned long long enterRowIndexInMainFrameSession;
    CMessageWrap *enterMsgInMainFrameSession;
    CDUnknownBlockType _finishCallback;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType finishCallback; // @synthesize finishCallback=_finishCallback;
@property(nonatomic) unsigned int enterSessionInfoNotifyType; // @synthesize enterSessionInfoNotifyType;
@property(retain, nonatomic) CMessageWrap *enterMsgInMainFrameSession; // @synthesize enterMsgInMainFrameSession;
@property(nonatomic) unsigned int redDotCount; // @synthesize redDotCount;
@property(nonatomic) _Bool isShowRedDotInMainFrameSession; // @synthesize isShowRedDotInMainFrameSession;
@property(nonatomic) unsigned long long enterRowIndexInMainFrameSession; // @synthesize enterRowIndexInMainFrameSession;
@property(nonatomic) unsigned long long source; // @synthesize source;
@property(retain, nonatomic) BrandTLExptConfig *exptConfig; // @synthesize exptConfig;
- (_Bool)shouldUpdatePageStateWhenPreRenderStart;
- (id)entryPoint;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillBePushed:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setupPlugins;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithPublishLaunchInfo:(id)arg1 finishCallback:(CDUnknownBlockType)arg2;
- (id)initWithExptConfig:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

