//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FlutterEmbedderKeyResponder;

@interface FlutterKeyPendingResponse : NSObject
{
    FlutterEmbedderKeyResponder *_responder;
    unsigned long long _responseId;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long responseId; // @synthesize responseId=_responseId;
@property(readonly) __weak FlutterEmbedderKeyResponder *responder; // @synthesize responder=_responder;
- (id)initWithHandler:(id)arg1 responseId:(unsigned long long)arg2;

@end

