//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class FWFNSHttpCookieData;

@protocol FWFWKHttpCookieStoreHostApi
- (void)setCookieForStoreWithIdentifier:(long long)arg1 cookie:(FWFNSHttpCookieData *)arg2 completion:(void (^)(FlutterError *))arg3;
- (void)createFromWebsiteDataStoreWithIdentifier:(long long)arg1 dataStoreIdentifier:(long long)arg2 error:(id *)arg3;
@end

