//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FWFInstanceManager;
@protocol FlutterBinaryMessenger;

@interface FWFWebViewConfigurationHostApiImpl : NSObject
{
    id <FlutterBinaryMessenger> _binaryMessenger;
    FWFInstanceManager *_instanceManager;
}

- (void).cxx_destruct;
@property(nonatomic) __weak FWFInstanceManager *instanceManager; // @synthesize instanceManager=_instanceManager;
@property(nonatomic) __weak id <FlutterBinaryMessenger> binaryMessenger; // @synthesize binaryMessenger=_binaryMessenger;
- (void)setMediaTypesRequiresUserActionForConfigurationWithIdentifier:(long long)arg1 forTypes:(id)arg2 error:(id *)arg3;
- (void)setLimitsNavigationsToAppBoundDomainsForConfigurationWithIdentifier:(long long)arg1 isLimited:(_Bool)arg2 error:(id *)arg3;
- (void)setAllowsInlineMediaPlaybackForConfigurationWithIdentifier:(long long)arg1 isAllowed:(_Bool)arg2 error:(id *)arg3;
- (void)createFromWebViewWithIdentifier:(long long)arg1 webViewIdentifier:(long long)arg2 error:(id *)arg3;
- (void)createWithIdentifier:(long long)arg1 error:(id *)arg2;
- (id)webViewConfigurationForIdentifier:(long long)arg1;
- (id)initWithBinaryMessenger:(id)arg1 instanceManager:(id)arg2;

@end

