//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class MISSING_TYPE, NSString;

@interface GameLiveJumpInfo_FinderLiveWeappJumpInfo : WXPBGeneratedMessage
{
}

+ (MISSING_TYPE *)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *appid; // @dynamic appid;
@property(retain, nonatomic) NSString *gameLiveInfo; // @dynamic gameLiveInfo;
@property(retain, nonatomic) NSString *path; // @dynamic path;
@property(nonatomic) unsigned int versionType; // @dynamic versionType;

@end

