//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionView.h>

@interface GCCollectionView : UICollectionView
{
    _Bool _disableChildViewEvent;
}

@property(nonatomic) _Bool disableChildViewEvent; // @synthesize disableChildViewEvent=_disableChildViewEvent;
- (void)relayoutAndReload;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

