//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSData, NSString;

@interface GOGItemType : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSData *blob; // @dynamic blob;
@property(nonatomic) double dbtype; // @dynamic dbtype;
@property(nonatomic) int int32; // @dynamic int32;
@property(nonatomic) long long int64; // @dynamic int64;
@property(retain, nonatomic) NSString *str; // @dynamic str;
@property(nonatomic) int type; // @dynamic type;
@property(nonatomic) unsigned int uint32; // @dynamic uint32;
@property(nonatomic) unsigned long long uint64; // @dynamic uint64;

@end

