//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class CMessageWrap, HistoryMsgUploadTask;

@protocol HistoryMsgUploadTaskDelegate <NSObject>
- (void)onUploadTaskFailWithMsg:(CMessageWrap *)arg1 uploadTask:(HistoryMsgUploadTask *)arg2;
- (void)onUploadTaskSuccessWithMsg:(CMessageWrap *)arg1 uploadTask:(HistoryMsgUploadTask *)arg2;
@end

