//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class UIViewController, WATimelineData;

@protocol IWATimelineCommitDelegate <NSObject>
- (void)onDoneForwardForForwardView:(UIViewController *)arg1 timelineData:(WATimelineData *)arg2;
- (void)onCancelForwardForForwardView:(UIViewController *)arg1 timelineData:(WATimelineData *)arg2;
@end

