//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, WebviewAuthorizationInfo;

@protocol IWebviewAskAuthorizationLogicExt

@optional
- (void)OnAskAuthorizationFailure:(NSString *)arg1 ForAuthInfo:(WebviewAuthorizationInfo *)arg2;
- (void)OnAskAuthorizationSuccessForAuthInfo:(WebviewAuthorizationInfo *)arg1;
@end

