//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class LinkInfo_WeReadInfo_ShowInfo;

@interface LinkInfo_WeReadInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) LinkInfo_WeReadInfo_ShowInfo *showInfo; // @dynamic showInfo;

@end

