//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class LiveWeCoinConsumeErrorTypeBox;

@interface LiveWeCoinConsumeError : NSObject
{
    LiveWeCoinConsumeErrorTypeBox *_type;
}

+ (id)nullableFromList:(id)arg1;
+ (id)fromList:(id)arg1;
+ (id)makeWithType:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) LiveWeCoinConsumeErrorTypeBox *type; // @synthesize type=_type;
- (id)toList;

@end

