//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol MatrixAdapterDelegate;

@interface MatrixAdapter : NSObject
{
    id <MatrixAdapterDelegate> _delegate;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) __weak id <MatrixAdapterDelegate> delegate; // @synthesize delegate=_delegate;

@end

