//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MessageSourceInfoHandler_Live
{
}

+ (_Bool)canCreateWithMsgWrap:(id)arg1;
- (void)handleClickWithViewController:(id)arg1;
- (_Bool)canClick;
- (id)sourceTitle;
- (id)sourceIcon:(struct CGSize)arg1 color:(id)arg2;

@end

