//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MMCheckBox
{
}

- (void)onCheckBoxClick:(id)arg1;
- (id)init;

@end

