//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MMUILabel;

@interface MMFinderLiveKTVSongSmartBoxCell
{
    MMUILabel *_actionLabel;
}

+ (id)identifier;
- (void).cxx_destruct;
@property(retain, nonatomic) MMUILabel *actionLabel; // @synthesize actionLabel=_actionLabel;
- (void)onClickedSmartBox;
- (void)customLayoutUI;

@end

