//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MMFinderLiveSqareInLiveListPopAnimiatedTransitioning
{
}

- (void)finderLiveSquareAnimateTransition:(id)arg1;
- (double)finderLiveSquareAnimationTransitionDuration:(id)arg1;
- (void)initailFinderLiveSquareAnimationWithViewController:(id)arg1;
- (_Bool)isSpecialState;

@end

