//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MMUILabel;

@interface MMFinderLiveOnlineStateRewardCountView : UIView
{
    MMUILabel *_label;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMUILabel *label; // @synthesize label=_label;
- (void)updateRewardAmount:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

