//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MMFinderLiveKSKitMusicNote;

@interface MMFinderLiveKSKitMusicNoteHitLine : UIView
{
    MMFinderLiveKSKitMusicNote *_rootMusicNote;
    struct _NSRange _hitRange;
}

- (void).cxx_destruct;
@property(nonatomic) struct _NSRange hitRange; // @synthesize hitRange=_hitRange;
@property(nonatomic) __weak MMFinderLiveKSKitMusicNote *rootMusicNote; // @synthesize rootMusicNote=_rootMusicNote;
- (void)updateSelfLeftAndWidth;
- (_Bool)checkHitRangeIsContinuous:(struct _NSRange)arg1;
- (_Bool)addHitRange:(struct _NSRange)arg1;
- (id)initWithRootMusicNote:(id)arg1;

@end

