//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSArray, UIImageView, UIView;

@protocol MMFinderFriendLikeShootingAnimationTargetProtocol <NSObject>
- (struct CGRect)friendLikeShootingAinmationTargetGetFrame;
- (UIView *)friendLikeShootingAinmationTargetCreateSnapshotView;

@optional
- (_Bool)removedOnCompletion;
- (void)friendLikeEndLongPressAction;
- (void)friendLikeStartLongPressAction;
- (UIImageView *)selfLikeIconView;
- (UIView *)selfNameLabel;
- (UIView *)likeHeaderContainerView;
- (_Bool)supportNewStyle;
- (void)friendLikeSuperLikeAnimationEnd;
- (void)friendLikeAvatorViewLayout;
- (void)friendLikeTitleRefreshLayoutWithSuperLikeFlag:(_Bool)arg1;
- (NSArray *)friendLikeShowingHeaderViews;
- (void)friendLikeStartPerformAnimation;
@end

