//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class UIColor;

@interface MMFinderLiveKSKitLyricStyle : NSObject
{
    _Bool _isVertical;
    UIColor *_lyricColor;
    double _lyricInset;
    unsigned long long _lyricAlignment;
}

+ (id)defaultStyle;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long lyricAlignment; // @synthesize lyricAlignment=_lyricAlignment;
@property(nonatomic) double lyricInset; // @synthesize lyricInset=_lyricInset;
@property(retain, nonatomic) UIColor *lyricColor; // @synthesize lyricColor=_lyricColor;
@property(nonatomic) _Bool isVertical; // @synthesize isVertical=_isVertical;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

