//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@protocol MMFinderLiveReplayMessageCacheDelegate <NSObject>
- (void)onPageStarvingForTimeOffsetAt:(unsigned int)arg1;

@optional
- (void)onPagePrefetchSuggestedForTimeOffsetAt:(unsigned int)arg1;
@end

