//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class RichTextView;

@interface MMFinderLiveCreateNoticePolicyIntroView
{
    RichTextView *_descLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) RichTextView *descLabel; // @synthesize descLabel=_descLabel;
- (double)contentViewHeight;
- (void)updateDescLabel;
- (void)layoutCurrentUI;
- (void)changMode;
- (void)initUI;

@end

