//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface MMLiveFeedStreamStyleableUIActionBaseModel : NSObject
{
    int _type;
    NSString *_eid;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *eid; // @synthesize eid=_eid;
@property(nonatomic) int type; // @synthesize type=_type;

@end

