//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIImageView.h>

@class MISSING_TYPE, MMLiveLikeAnimationRoute;

@interface MMLiveLikeImageView : UIImageView
{
    MISSING_TYPE *_animationRoute;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMLiveLikeAnimationRoute *animationRoute; // @synthesize animationRoute=_animationRoute;

@end

