//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol MMLimitedModeSetPasswordLogicDelegate <NSObject>

@optional
- (void)onLimitedModeSetPasswordRetType:(unsigned int)arg1 ticket:(NSString *)arg2 success:(_Bool)arg3 errMsg:(NSString *)arg4;
@end

