//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol MMMenuWindowDelegate;

@interface MMMenuWindow
{
    _Bool _blockBackgroundTouches;
    id <MMMenuWindowDelegate> _delegate;
    struct CGRect _menuFrame;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool blockBackgroundTouches; // @synthesize blockBackgroundTouches=_blockBackgroundTouches;
@property(nonatomic) struct CGRect menuFrame; // @synthesize menuFrame=_menuFrame;
@property(nonatomic) __weak id <MMMenuWindowDelegate> delegate; // @synthesize delegate=_delegate;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

