//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "AudioPlayerProtocol-Protocol.h"

@class AudioPlayerUserData;
@protocol MsgAudioPlayerDelegate;

@protocol MsgAudioPlayerProtocol <AudioPlayerProtocol>
@property(nonatomic) _Bool stopInBackground;
@property(nonatomic) double playRate;
- (void)switchToEarMode:(_Bool)arg1;
- (void)stopAndNotifyUI;
- (void)setDelegate:(id <MsgAudioPlayerDelegate>)arg1;
- (AudioPlayerUserData *)getUserData;
- (void)setUserData:(AudioPlayerUserData *)arg1;
- (void)setAutoMode;
- (void)setEarpieceMode;
@end

