//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface NewLifeFollowUserReq : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int enhanceFollowBtn; // @dynamic enhanceFollowBtn;
@property(nonatomic) unsigned int enterScene; // @dynamic enterScene;
@property(nonatomic) unsigned int enterType; // @dynamic enterType;
@property(nonatomic) _Bool isFollow; // @dynamic isFollow;
@property(retain, nonatomic) NSString *referenceFeedId; // @dynamic referenceFeedId;
@property(nonatomic) unsigned int scene; // @dynamic scene;
@property(retain, nonatomic) NSString *searchClickId; // @dynamic searchClickId;
@property(nonatomic) unsigned int userType; // @dynamic userType;
@property(retain, nonatomic) NSString *username; // @dynamic username;

@end

