//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderEventInfo;

@interface NewLifePostEventClickReq : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool allowCreateEvent; // @dynamic allowCreateEvent;
@property(retain, nonatomic) FinderEventInfo *currentSelectEvent; // @dynamic currentSelectEvent;

@end

