//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSString.h>

@interface NSString (strup)
- (id)formatChinaPhoneString:(id)arg1;
- (_Bool)isEmailAddress;
- (_Bool)isCurrectPhoneNum;
- (_Bool)isNumericStr;
- (id)XXXString;
- (_Bool)checkIsLegalMobile:(unsigned short *)arg1 bufLen:(int)arg2;
- (id)getTelPhoneNumbersWithComma;
- (id)GetTelPhoneNumber;
@end

