//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSString.h>

@interface NSString (RTE)
- (struct _NSRange)paragraphRangeAtIndex:(unsigned long long)arg1;
- (_Bool)isEndOfParagraphAtIndex:(unsigned long long)arg1;
- (unsigned long long)numOfParagraph;
@end

