//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface OMCDecibelHeightCalculator : NSObject
{
    struct SharedPtr<XMFDecibelHeightCalcF32> _backingCalc;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)calculateHeightsWithDecibels:(const void *)arg1 outputHeights:(void *)arg2;
- (id)initWithMaxHeight:(float)arg1 minDecibel:(float)arg2 powerRatio:(float)arg3;

@end

