//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class OMJAssetInfo;

@interface OMJClip : NSObject
{
    OMJAssetInfo *_assetInfo;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) OMJAssetInfo *assetInfo; // @synthesize assetInfo=_assetInfo;
- (id)initWithAssetInfo:(id)arg1;

@end

