//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface QBBeaconUtil : NSObject
{
}

+ (id)base64Encode:(id)arg1;
+ (id)addParamWithSIdForUploadUrl:(id)arg1 sessionId:(id)arg2;
+ (id)generateAesKey;
+ (id)getIDFA;
+ (id)getIDFV;
+ (id)getFilePathWithName:(id)arg1;

@end

