//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface SettingVCReportData : NSObject
{
    unsigned char _uiVersion;
    unsigned char _settingFromScource;
    NSString *_sessionId;
    unsigned long long _enterTime;
    unsigned long long _sessionEnterTime;
    NSMutableDictionary *_pageEnterTime;
    NSString *_searchSessionId;
    NSString *_searchWord;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *searchWord; // @synthesize searchWord=_searchWord;
@property(retain, nonatomic) NSString *searchSessionId; // @synthesize searchSessionId=_searchSessionId;
@property(retain, nonatomic) NSMutableDictionary *pageEnterTime; // @synthesize pageEnterTime=_pageEnterTime;
@property(nonatomic) unsigned long long sessionEnterTime; // @synthesize sessionEnterTime=_sessionEnterTime;
@property(nonatomic) unsigned long long enterTime; // @synthesize enterTime=_enterTime;
@property(nonatomic) unsigned char settingFromScource; // @synthesize settingFromScource=_settingFromScource;
@property(nonatomic) unsigned char uiVersion; // @synthesize uiVersion=_uiVersion;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
- (id)init;

@end

