//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface SportGoalUpload : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) double current; // @dynamic current;
@property(nonatomic) double goal; // @dynamic goal;
@property(nonatomic) unsigned int showIndex; // @dynamic showIndex;
@property(nonatomic) unsigned int showType; // @dynamic showType;
@property(nonatomic) unsigned int sportGoalTypeId; // @dynamic sportGoalTypeId;
@property(nonatomic) unsigned int timestamp; // @dynamic timestamp;

@end

