//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface StatisticsBrandVideoAdInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;
- (_Bool)isVaild;

// Remaining properties
@property(retain, nonatomic) NSString *jsReportArgs; // @dynamic jsReportArgs;

@end

