//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIAccessibilityElement.h>

@class UIView;

@interface TempAccessibilityElement : UIAccessibilityElement
{
    UIView *_view;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIView *view; // @synthesize view=_view;
- (_Bool)accessibilityActivate;
- (id)initWithView:(id)arg1;

@end

