//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class TingItem, TingNowPlayingInfoCenter;
@protocol TingFlowPlayerProtocol;

@protocol TingNowPlayingInfoCenterDelegate <NSObject>

@optional
- (void)nowPlayingBase:(TingNowPlayingInfoCenter *)arg1 flowPlayer:(id <TingFlowPlayerProtocol>)arg2 onItemLoaded:(TingItem *)arg3;
@end

