//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class TPMTKView;

@protocol TPMTKViewDelegate <NSObject>
- (void)render:(TPMTKView *)arg1;
- (void)reshape:(TPMTKView *)arg1;
@end

