//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@interface UIView (WeChat)
- (void)setNoHeroModifiers;
- (void)setTranslateAnimeWithX:(double)arg1 y:(double)arg2 z:(double)arg3;
- (void)setHeroDuration:(double)arg1;
- (void)setFadeAnimation;
- (void)setHeroSnapShotType:(unsigned long long)arg1;
- (void)setHeroEnabled:(_Bool)arg1;
- (void)setLayerSnapshotMagicAnimeId:(id)arg1;
- (void)setNoSnapshotMagicAnimeId:(id)arg1;
- (void)setMagicAnimeId:(id)arg1;
@end

