//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITapGestureRecognizer.h>

@interface VoIPMPUIv2TapGestureRecognizer : UITapGestureRecognizer
{
    CDUnknownBlockType _event;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType event; // @synthesize event=_event;
- (void)handleAction:(id)arg1;
- (id)initWithEvent:(CDUnknownBlockType)arg1;

@end

