//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface WAJSEventHandler_getUserAutoFillData
{
}

- (void)onCgiResponse:(id)arg1 forEvent:(unsigned int)arg2;
- (void)getAutoFillInfo:(id)arg1 getAllInfo:(_Bool)arg2 clientVersion:(unsigned int)arg3;
- (void)handleJSEvent:(id)arg1;

@end

