//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class WAMapAnnotationView;

@protocol WAMapAnnotationViewDelegate <NSObject>
- (void)onMapLabelClick:(WAMapAnnotationView *)arg1;
- (void)onMapAnnotationViewTap:(WAMapAnnotationView *)arg1;

@optional
- (void)onAnnotationZIndexChangeTo:(int)arg1;
@end

