//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class WANativeViewPointerEvent, WANativeViewTexture;

@protocol WANativeViewTextureInterface <NSObject>
@property(retain) WANativeViewTexture *nativeViewTexture;
@property(nonatomic) _Bool nativeViewUseTexture;

@optional
- (void)handleNativeViewPointerEvent:(WANativeViewPointerEvent *)arg1;
- (void)refreshNativeViewTexture;
@end

