//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface WARootScrollViewInfo : NSObject
{
    long long _windowId;
    struct CGPoint _contentOffset;
    struct CGRect _scrollFrame;
}

@property(nonatomic) struct CGPoint contentOffset; // @synthesize contentOffset=_contentOffset;
@property(nonatomic) struct CGRect scrollFrame; // @synthesize scrollFrame=_scrollFrame;
@property(nonatomic) long long windowId; // @synthesize windowId=_windowId;

@end

