//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MMTableView, UIView, WeToast, ZZFLEXAngel;

@interface WASMPageSheetListView
{
    MMTableView *_tableView;
    ZZFLEXAngel *_angel;
    WeToast *_weakCurrentToast;
    UIView *_bottomGradientView;
}

+ (double)viewHeightByDataModel:(id)arg1 hostView:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *bottomGradientView; // @synthesize bottomGradientView=_bottomGradientView;
@property(nonatomic) __weak WeToast *weakCurrentToast; // @synthesize weakCurrentToast=_weakCurrentToast;
@property(retain, nonatomic) ZZFLEXAngel *angel; // @synthesize angel=_angel;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
- (void)updateBottomGradientLayer;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setViewDataModel:(id)arg1;

@end

