//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSString, WCAccountPasswordInputViewController;

@protocol WCAccountPasswordInputViewControllerDelegate <NSObject>

@optional
- (void)onPasswordInputViewControllerLoginWithPassword:(NSString *)arg1;
- (void)onPasswordInputViewControllerBack:(WCAccountPasswordInputViewController *)arg1;
@end

