//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol WCAccountMainLoginViewControllerDelegate <NSObject>

@optional
- (void)onMainLoginGoToRegister;
- (_Bool)shouldShowBackBtnForMainLogin;
- (void)onMainLoginPasskeyConnectWithAutoLogin:(_Bool)arg1;
- (void)onMainLoginUseBothDevice;
- (void)onMainLoginAppleConnect;
- (void)onMainLoginFacebookConnect;
- (void)onMainLoginProblem;
- (void)onMainLoginGotoChatLogMigration;
- (void)onMainLoginGoToFeedback;
- (void)onMainLoginGoToFreeze;
- (void)onMainLoginGoToHelpCenter;
- (void)onMainLoginGotoSecurityCenter;
- (void)onMainLoginBack:(unsigned long long)arg1;
- (void)onMainLoginUserName:(NSString *)arg1 Pwd:(NSString *)arg2;
- (void)onMainLoginNext:(NSString *)arg1 phoneNumber:(NSString *)arg2;
@end

