//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray, NSRecursiveLock, NSString, WCPlayerPlayArgs, WCPlayerPlaybackInfo, WCPlayerReporter, WCResourceLoaderMoniter;
@protocol WCAssetDataLoaderProxyDelegate;

@interface WCAssetDataLoaderProxy
{
    int _loadingRequestSeq;
    long long _resourceType;
    WCPlayerReporter *_reporter;
    WCPlayerPlayArgs *_playerArgs;
    WCPlayerPlaybackInfo *_playbackInfo;
    id <WCAssetDataLoaderProxyDelegate> _delegate;
    WCResourceLoaderMoniter *_loadingRequestMoniter;
    NSMutableArray *_arrLoadingRequest;
    NSRecursiveLock *_lock;
    unsigned long long _responseTotalData;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long responseTotalData; // @synthesize responseTotalData=_responseTotalData;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableArray *arrLoadingRequest; // @synthesize arrLoadingRequest=_arrLoadingRequest;
@property(retain, nonatomic) WCResourceLoaderMoniter *loadingRequestMoniter; // @synthesize loadingRequestMoniter=_loadingRequestMoniter;
@property(nonatomic) __weak id <WCAssetDataLoaderProxyDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WCPlayerPlaybackInfo *playbackInfo; // @synthesize playbackInfo=_playbackInfo;
@property(retain, nonatomic) WCPlayerPlayArgs *playerArgs; // @synthesize playerArgs=_playerArgs;
@property(retain, nonatomic) WCPlayerReporter *reporter; // @synthesize reporter=_reporter;
@property(nonatomic) long long resourceType; // @synthesize resourceType=_resourceType;
@property(nonatomic) int loadingRequestSeq; // @synthesize loadingRequestSeq=_loadingRequestSeq;
- (id)getVideoData:(id)arg1 range:(struct _NSRange)arg2;
- (unsigned long long)getAvaibleLength:(id)arg1;
- (unsigned long long)fileLength:(id)arg1;
- (id)getCurrentLoadingRequest;
- (void)removeAllLoadingRequest;
- (_Bool)respondDataWithLoadingRequest:(id)arg1;
- (void)processLoadingRequest;
- (void)onReceiveDelLoadingRequest:(id)arg1;
- (void)onReceiveNewLoadingRequest:(id)arg1;
- (void)requestFirstSliceDataForLoadingRequest:(id)arg1;
- (void)removeLoadingRequests:(id)arg1;
- (void)onNotAnyLoadingRequest;
- (_Bool)fillInformationForRequest:(id)arg1;
- (id)downloader:(id)arg1;
- (struct _NSRange)getRequestDataRangeWithSec:(double)arg1;
- (id)initWithPlayerArgs:(id)arg1 playbackInfo:(id)arg2 reporter:(id)arg3 delegate:(id)arg4;

// Remaining properties
@property(retain, nonatomic) NSString *logTag;

@end

