//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@protocol WCCardPkgBackTableViewDelegate <NSObject>
- (void)WXCardPkgTableViewHeight:(double)arg1 scrollEnabled:(_Bool)arg2;
- (double)WXCardPkgTableViewMaxHeight;
@end

