//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class UIView;

@interface WCEdgeList : NSObject
{
    UIView *_view;
}

- (void).cxx_destruct;
- (id)right;
- (id)hCenter;
- (id)left;
- (id)bottom;
- (id)vCenter;
- (id)top;
- (id)initWithView:(id)arg1;

@end

