//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class PrepareFinder, UIButton, UILabel, UIScrollView, UIView;

@interface WCFinderGuardNowViewController
{
    PrepareFinder *_prepare;
    UIScrollView *_scrollView;
    UIView *_contentView;
    UILabel *_titleLabel;
    UILabel *_summaryLabel;
    UIView *_descContainer;
    UIButton *_confirmButton;
}

+ (id)newWithPrepare:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UIView *descContainer; // @synthesize descContainer=_descContainer;
@property(retain, nonatomic) UILabel *summaryLabel; // @synthesize summaryLabel=_summaryLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) PrepareFinder *prepare; // @synthesize prepare=_prepare;
- (void);
- (void)onClickConfirmButton;
- (void)_updateSummary:(id)arg1;
- (void)updateViews;
- (void)setupViews;
- (void)viewDidLoad;
- (id)navigationBarBackgroundColor;
- (id)initWithPrepare:(id)arg1;
- (id)init;

@end

