//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CAShapeLayer, MMTableView, NSMutableArray, NSString, UIView;
@protocol MMFinderLiveSimpleVersionChooseViewDelegate;

@interface WCFinderLiveSimpleVersionChooseView
{
    _Bool _isSimpleVersion;
    id <MMFinderLiveSimpleVersionChooseViewDelegate> _delegate;
    NSMutableArray *_dataArray;
    CAShapeLayer *_shapeLayer;
    UIView *_contentView;
    MMTableView *_tableView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(copy, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(nonatomic) __weak id <MMFinderLiveSimpleVersionChooseViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isSimpleVersion; // @synthesize isSimpleVersion=_isSimpleVersion;
- (void)pageSheetDidDisappear;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)getTableHeight;
- (double)contentViewHeight;
- (void)leftButtonAction;
- (void)setupPageSheetConfig;
- (void)layoutUI;
- (void)createUI;
- (void)layoutSubviews;
- (void)updateWithSimpleVersion:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

