//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol WCFinderCollectionViewReportableItem <NSObject>
@property(readonly, copy, nonatomic) NSDictionary *params;
@property(readonly, nonatomic) unsigned long long reportPolicy;
@property(readonly, copy, nonatomic) NSString *viewID;
@end

