//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class WCFinderFeedPickerParams;

@interface WCFinderChooseFeedTabControllerConfig : NSObject
{
    _Bool _isPlanePickerStyle;
    WCFinderFeedPickerParams *_params;
    double _cellHeightRatio;
}

- (void).cxx_destruct;
@property(nonatomic) double cellHeightRatio; // @synthesize cellHeightRatio=_cellHeightRatio;
@property(retain, nonatomic) WCFinderFeedPickerParams *params; // @synthesize params=_params;
@property(nonatomic) _Bool isPlanePickerStyle; // @synthesize isPlanePickerStyle=_isPlanePickerStyle;
- (id)init;

@end

