//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class AVAsset, NSURL, UIImage, UIView, WCFinderCropRectModel, WCFinderPreviewEditVideoCompositionTask;

@protocol WCFinderCoverVideoPreviewProtocol <NSObject>
- (void)loadPreviewViewByVideoURL:(NSURL *)arg1 compositionTask:(WCFinderPreviewEditVideoCompositionTask *)arg2 specialImage:(UIImage *)arg3 cropRectModel:(WCFinderCropRectModel *)arg4;
- (double)videoDuration;
- (UIView *)playerContainerView;
- (AVAsset *)playerAVAsset;
- (double)keyFrameRate;
@end

