//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface WCFinderConvertImageModel : NSObject
{
    NSArray *_imageAssetArray;
    NSArray *_imagesArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *imagesArray; // @synthesize imagesArray=_imagesArray;
@property(retain, nonatomic) NSArray *imageAssetArray; // @synthesize imageAssetArray=_imageAssetArray;

@end

