//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class WCFinderNativeDramaIAAFeedViewController;

@protocol WCFinderNativeDramaIAAFeedViewControllerDelegate <NSObject>
- (void)nativeDramaIAAFeedController:(WCFinderNativeDramaIAAFeedViewController *)arg1 didUnlockEpisode:(unsigned long long)arg2;
@end

