//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, WCFinderStreamLoadingState;

@interface WCFinderHistoryPageModel : NSObject
{
    int _tabType;
    int _searchTabType;
    int _scene;
    int _supportItemFlag;
    NSString *_title;
    NSString *_iconName;
    NSString *_selectedItemName;
    WCFinderStreamLoadingState *_loadingState;
    unsigned long long _requestId;
    NSString *_noMoreTips;
    CDUnknownBlockType _historyRecordDayUpdateBlock;
}

+ (void)requestFeedForList:(id)arg1 feedArray:(id)arg2 page:(id)arg3;
+ (id)formatHistoryTime:(long long)arg1;
- (void).cxx_destruct;
@property(nonatomic) int supportItemFlag; // @synthesize supportItemFlag=_supportItemFlag;
@property(copy, nonatomic) CDUnknownBlockType historyRecordDayUpdateBlock; // @synthesize historyRecordDayUpdateBlock=_historyRecordDayUpdateBlock;
@property(retain, nonatomic) NSString *noMoreTips; // @synthesize noMoreTips=_noMoreTips;
@property(nonatomic) unsigned long long requestId; // @synthesize requestId=_requestId;
@property(retain, nonatomic) WCFinderStreamLoadingState *loadingState; // @synthesize loadingState=_loadingState;
@property(nonatomic) int scene; // @synthesize scene=_scene;
@property(nonatomic) int searchTabType; // @synthesize searchTabType=_searchTabType;
@property(nonatomic) int tabType; // @synthesize tabType=_tabType;
@property(retain, nonatomic) NSString *selectedItemName; // @synthesize selectedItemName=_selectedItemName;
@property(retain, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)dispatchRequest:(CDUnknownBlockType)arg1 complete:(CDUnknownBlockType)arg2;
- (void)onDeleteFeed:(id)arg1;
- (void)onClear;
- (void)requestNextPage:(CDUnknownBlockType)arg1;
- (void)requestFirstPage:(CDUnknownBlockType)arg1;
- (void)doRequestNextPage:(CDUnknownBlockType)arg1;
- (void)doRequestFirstPage:(CDUnknownBlockType)arg1;
- (_Bool)hasContent;
- (id)initWithTitle:(id)arg1 icon:(id)arg2 selectedIcon:(id)arg3 scene:(int)arg4 tabType:(int)arg5 searchTabTab:(int)arg6 supportItemFlag:(int)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

