//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString, UINavigationController;
@protocol WCFinderMyTabSectionControllerDelegate;

@interface WCFinderMyTabSectionController : NSObject
{
    _Bool _display;
    NSString *_displayTitle;
    id <WCFinderMyTabSectionControllerDelegate> _delegate;
    NSMutableArray *_didBePopCallbackList;
}

+ (long long)mapAccountType:(_Bool)arg1 brandState:(long long)arg2;
+ (id)generateReportInfoFromCombines:(id)arg1;
+ (Class)paramsClass;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *didBePopCallbackList; // @synthesize didBePopCallbackList=_didBePopCallbackList;
@property(nonatomic) __weak id <WCFinderMyTabSectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *displayTitle; // @synthesize displayTitle=_displayTitle;
@property(nonatomic) _Bool display; // @synthesize display=_display;
- (id)combineReportInfo;
- (void)updateReportInfo:(id)arg1;
@property(readonly, nonatomic) UINavigationController *navigationController;
- (void)setCardNeedsLayout;
- (void)addPageDidBePopCallback:(CDUnknownBlockType)arg1;
- (void)onViewDidPopOrDismiss;
- (void)onViewWillPopOrDismiss;
- (void)onViewDidPushOrPresent;
- (void)onViewWillPushOrPresent;
- (void)onViewDidBePopOrDismiss;
- (void)onViewWillBePopOrDismiss;
- (void)onViewDidBePushOrPresent;
- (void)onViewWillBePushOrPresent;
- (void)onViewDidDisappear;
- (void)onViewWillDisappear;
- (void)onViewDidAppear;
- (void)onViewWillAppear;
- (id)createDisplayCard;
- (id)initWithParams:(id)arg1;
- (id)init;

@end

