//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MMBadgeView, MMUIButton, NSDictionary, UIButton;
@protocol WCFinderPersonalCenterCameraActionHandle, WCFinderPersonalCenterLiveActionHandle;

@interface WCFinderPersonalCenterPostActionView : UIView
{
    _Bool _showFinder;
    _Bool _forceButtonVerticalLayout;
    int _commentScene;
    id <WCFinderPersonalCenterCameraActionHandle> _cameraHandle;
    id <WCFinderPersonalCenterLiveActionHandle> _liveHandle;
    unsigned long long _cameraRedDotShowType;
    unsigned long long _liveRedDotShowType;
    MMUIButton *_cameraBtn;
    MMUIButton *_liveBtn;
    UIView *_postSeparatorLine;
    MMBadgeView *_liveRedDotLabel;
    MMBadgeView *_cameraRedDotLabel;
    NSDictionary *_reportInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *reportInfo; // @synthesize reportInfo=_reportInfo;
@property(retain, nonatomic) MMBadgeView *cameraRedDotLabel; // @synthesize cameraRedDotLabel=_cameraRedDotLabel;
@property(retain, nonatomic) MMBadgeView *liveRedDotLabel; // @synthesize liveRedDotLabel=_liveRedDotLabel;
@property(retain, nonatomic) UIView *postSeparatorLine; // @synthesize postSeparatorLine=_postSeparatorLine;
@property(retain, nonatomic) MMUIButton *liveBtn; // @synthesize liveBtn=_liveBtn;
@property(retain, nonatomic) MMUIButton *cameraBtn; // @synthesize cameraBtn=_cameraBtn;
@property(nonatomic) unsigned long long liveRedDotShowType; // @synthesize liveRedDotShowType=_liveRedDotShowType;
@property(nonatomic) unsigned long long cameraRedDotShowType; // @synthesize cameraRedDotShowType=_cameraRedDotShowType;
@property(nonatomic) _Bool forceButtonVerticalLayout; // @synthesize forceButtonVerticalLayout=_forceButtonVerticalLayout;
@property(nonatomic) _Bool showFinder; // @synthesize showFinder=_showFinder;
@property(nonatomic) int commentScene; // @synthesize commentScene=_commentScene;
@property(retain, nonatomic) id <WCFinderPersonalCenterLiveActionHandle> liveHandle; // @synthesize liveHandle=_liveHandle;
@property(retain, nonatomic) id <WCFinderPersonalCenterCameraActionHandle> cameraHandle; // @synthesize cameraHandle=_cameraHandle;
- (void)updateReportInfo:(id)arg1;
- (void)configLiveButton:(_Bool)arg1 enable:(_Bool)arg2;
- (void)_updateRedDotLabel:(id *)arg1 forButton:(id)arg2 showType:(unsigned long long)arg3;
- (void)_layoutRedDot;
- (void)layoutSubviews;
- (void)layoutElements;
- (id)createPostSeparatorLine;
- (id)createActionButton:(id)arg1 iconName:(id)arg2;
- (id)createLiveBtn;
- (id)createCameraBtn;
@property(readonly, nonatomic) UIButton *cameraButton;
- (void)didMoveToWindow;
- (void)setupCommentScene:(int)arg1 needPercentPostReport:(_Bool)arg2;
- (void)_setupExpose;
- (id)initWithFrame:(struct CGRect)arg1;

@end

