//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CEmoticonWrap, MMImage, NSString;

@interface WCInputTextCacheItem : NSObject
{
    NSString *_text;
    MMImage *_image;
    CEmoticonWrap *_emoji;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CEmoticonWrap *emoji; // @synthesize emoji=_emoji;
@property(retain, nonatomic) MMImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

