//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, UIView, WCImageFullScreenTagView, WCMediaImageViewModel, WCMediaItemWrap, WCPhotoMutipleImageHeadView;

@interface WCMediaImageScrollView
{
    _Bool _useNewInteraction;
    WCMediaImageViewModel *_viewModel;
    WCMediaItemWrap *_mediaItemWrap;
    UIView *_imageTagSuperView;
    WCImageFullScreenTagView *_imageTagView;
    WCPhotoMutipleImageHeadView *_headView;
    struct UIEdgeInsets _imageTagSafeArea;
    struct UIEdgeInsets _imageTagPadding;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCPhotoMutipleImageHeadView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) WCImageFullScreenTagView *imageTagView; // @synthesize imageTagView=_imageTagView;
@property(nonatomic) _Bool useNewInteraction; // @synthesize useNewInteraction=_useNewInteraction;
@property(nonatomic) __weak UIView *imageTagSuperView; // @synthesize imageTagSuperView=_imageTagSuperView;
@property(nonatomic) struct UIEdgeInsets imageTagPadding; // @synthesize imageTagPadding=_imageTagPadding;
@property(nonatomic) struct UIEdgeInsets imageTagSafeArea; // @synthesize imageTagSafeArea=_imageTagSafeArea;
@property(retain, nonatomic) WCMediaItemWrap *mediaItemWrap; // @synthesize mediaItemWrap=_mediaItemWrap;
@property(retain, nonatomic) WCMediaImageViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void)reportLivePhotoPlayData:(long long)arg1;
- (void)reportLivePhotoExposeData;
- (void)ecsButtonClickedInImageTagView:(id)arg1;
- (void)detailButtonClickedInImageTagView:(id)arg1;
- (void)livePhotoButtonClickedInImageTagView:(id)arg1;
- (void)onFullScreenDragCancel;
- (void)onFullScreenDragEnd;
- (void)onFullScreenDragBegin;
- (void)scrollViewDidZoom:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidChangeAdjustedContentInset:(id)arg1;
- (void)playableImageView:(id)arg1 didChangePlayerState:(unsigned long long)arg2;
- (void)internalDisplayImageMaterial:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)updateVisibleForImageTagView:(_Bool)arg1;
- (void)updateMainTitle:(id)arg1 subTitle:(id)arg2;
- (void)layoutImageHeadView;
- (void)reloadImageHeadView;
- (void)layoutImageTagView;
- (void)layoutSubviews;
- (void)updateImageTagSafeArea;
- (void)reloadImageTagView;
- (void)bringImageTagViewToFront;
- (void)removeFromSuperview;
- (void)dealloc;
- (void)changeShowUhdImage:(id)arg1;
- (void)displayViewModel:(id)arg1 withImage:(id)arg2 frame:(struct CGRect)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

