//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface WCMomentsPlayerTester : NSObject
{
}

+ (void)setHDVideoURLString:(id)arg1;
+ (id)HDVideoURLString;
+ (void)setLDVideoURLString:(id)arg1;
+ (id)LDVideoURLString;

@end

