//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIImageView, UILabel, WCPayBaseMessageViewModel;

@interface WCPayBaseMessageCellView
{
    UILabel *m_descLabel;
    UILabel *m_titleLabel;
    UIImageView *m_iconView;
}

- (void).cxx_destruct;
- (_Bool)disableImplicitAnimations;
- (void)onTouchUpInside;
- (void)initIconView;
- (void)initDescLabel;
- (void)initTitleLabel;
- (_Bool)canAdjustsFontSizeToFitWidth;
- (void)layoutContentView;

// Remaining properties
@property(retain, nonatomic) WCPayBaseMessageViewModel *viewModel; // @dynamic viewModel;

@end

