//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "WCPayBaseCgiDelegate-Protocol.h"

@class GetHoneyPayCardResp, WCPayBaseNetworkingError, WCPayGetHoneyPayCardCgi;

@protocol WCPayGetHoneyPayCardCgiDelegate <WCPayBaseCgiDelegate>
- (void)getHoneyPayCardCgi:(WCPayGetHoneyPayCardCgi *)arg1 didFailWithError:(WCPayBaseNetworkingError *)arg2;
- (void)getHoneyPayCardCgi:(WCPayGetHoneyPayCardCgi *)arg1 didGetResponse:(GetHoneyPayCardResp *)arg2;
@end

