//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class WCDataItem;

@protocol WCSnsABTestMgrExt

@optional
- (void)onHideUrlFeedComfirmSuccess:(WCDataItem *)arg1;
- (void)onHideUrlFeedComfirmFail:(WCDataItem *)arg1;
- (void)onHideUrlFeedComfirmBegin:(WCDataItem *)arg1;
@end

