//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@interface WCStoryTimelineEntranceCollectionViewLayout : UICollectionViewFlowLayout
{
    struct CGSize _minimumSize;
}

@property(nonatomic) struct CGSize minimumSize; // @synthesize minimumSize=_minimumSize;
- (struct CGSize)collectionViewContentSize;

@end

