//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class JSEvent;

@interface WebviewJSEventHandler_jumpWCPayCardListLogic
{
    JSEvent *_m_jsEvent;
}

- (void).cxx_destruct;
@property(retain, nonatomic) JSEvent *m_jsEvent; // @synthesize m_jsEvent=_m_jsEvent;
- (void)failToOpen;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;

@end

