//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface WSReddotUtil : NSObject
{
}

+ (void)configNumberRedDotForEntry:(struct stEntryRow *)arg1 number:(long long)arg2 fromPath:(id)arg3 overwriteOtherBadgeReddot:(_Bool)arg4;
+ (void)configNumberRedDotForEntry:(struct stEntryRow *)arg1 number:(long long)arg2 fromPath:(id)arg3;

@end

