//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSNumber;

@interface WxaLiteAppWidgetDestroyMessage : NSObject
{
    NSNumber *_appUuid;
}

+ (id)nullableFromList:(id)arg1;
+ (id)fromList:(id)arg1;
+ (id)makeWithAppUuid:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *appUuid; // @synthesize appUuid=_appUuid;
- (id)toList;

@end

