//
//     Generated by classdump-c 5.0.1.
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class GamePbRequestMsgInfo;

@interface WXPBGeneratedMessage (CgiService)
- (_Bool)isRespSuccess;
@property(retain, nonatomic) GamePbRequestMsgInfo *pbRequestMsgInfo;
- (id)getAndCreateMsgInfoIfNeed;
- (id)gcToJsonStr;
@end

