//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9WeAppCoreP33_5632F048872A42CF2E020F607C02416117WACustomDrmPlayer : _TtCs12_SwiftObject
{
    MISSING_TYPE *URLAsset;
    MISSING_TYPE *playerItem;
    MISSING_TYPE *player;
    MISSING_TYPE *playerView;
    MISSING_TYPE *resourceLoader;
}

@end

