//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC6WeChat24WSHomePageLiteAppManager : NSObject
{
}

+ (void)preloadSearchTeachDataWithScene:(unsigned long long)arg1;
+ (void)releaseSearchPageWithScene:(unsigned long long)arg1;
+ (void)preloadLiteAppSearchPageWithScene:(unsigned long long)arg1;
+ (void)preloadMainSearchPageWithScene:(unsigned long long)arg1 forceDarkMode:(_Bool)arg2;
+ (id)routeItemFor:(unsigned long long)arg1;
- (void).cxx_destruct;
- (id)init;

@end

