//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MISSING_TYPE;

@interface _TtC6WeChat32WSNativeHotListVerticalEntryLine
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *verticalEntryLineDelegate;
    MISSING_TYPE *$__lazy_storage_$_scrollView;
    MISSING_TYPE *$__lazy_storage_$_contentView;
    MISSING_TYPE *$__lazy_storage_$_maxItemWidth;
    MISSING_TYPE *$__lazy_storage_$_oneWordWidth;
    MISSING_TYPE *list;
    MISSING_TYPE *row;
    MISSING_TYPE *canReportExpose;
    MISSING_TYPE *needScrollToBn;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

