//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIView;

@protocol _TtP6WeChat28FinderBulletFollowButtonHost_
@property(readonly, nonatomic) struct CGPoint followButtonBulletButtonCenter;
- (void)layoutFollowButton:(UIView *)arg1;
- (void)attachFollowButton:(UIView *)arg1;
@end

