//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BoxLinkInfo_AppMsgInfo, BoxLinkInfo_GameInfo, BoxLinkInfo_ProductInfo, BoxLinkInfo_WeAppInfo, BoxLinkInfo_WeReadInfo;

@interface BoxLinkInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BoxLinkInfo_AppMsgInfo *appmsgInfo; // @dynamic appmsgInfo;
@property(retain, nonatomic) BoxLinkInfo_GameInfo *gameInfo; // @dynamic gameInfo;
@property(nonatomic) unsigned int linkType; // @dynamic linkType;
@property(retain, nonatomic) BoxLinkInfo_ProductInfo *productInfo; // @dynamic productInfo;
@property(retain, nonatomic) BoxLinkInfo_WeAppInfo *weappInfo; // @dynamic weappInfo;
@property(retain, nonatomic) BoxLinkInfo_WeReadInfo *wereadInfo; // @dynamic wereadInfo;

@end

