//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CMessageWrap;

@protocol BrandTimelineNotifyLogicDelegate <NSObject>
- (void)onNewNotification:(CMessageWrap *)arg1;
- (void)onCreationCenterNotifyCountChange:(long long)arg1;
- (void)onNotifyMsgCountChange:(unsigned int)arg1;
@end

