//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@interface BrandPluginTemplateMsgReportModel
{
    unsigned int _opType;
    unsigned int _jumpType;
    unsigned int _location;
    unsigned int _msgType;
    NSString *_userName;
    NSString *_templateId;
    NSString *_msgTitle;
    NSString *_msgContent;
    NSString *_templateUniqueMsgId;
    NSString *_sessionId;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned int msgType; // @synthesize msgType=_msgType;
@property(nonatomic) unsigned int location; // @synthesize location=_location;
@property(nonatomic) unsigned int jumpType; // @synthesize jumpType=_jumpType;
@property(nonatomic) unsigned int opType; // @synthesize opType=_opType;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(retain, nonatomic) NSString *templateUniqueMsgId; // @synthesize templateUniqueMsgId=_templateUniqueMsgId;
@property(retain, nonatomic) NSString *msgContent; // @synthesize msgContent=_msgContent;
@property(retain, nonatomic) NSString *msgTitle; // @synthesize msgTitle=_msgTitle;
@property(retain, nonatomic) NSString *templateId; // @synthesize templateId=_templateId;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;

@end

