//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BRSPlayerIdHelper : NSObject
{
    long long _currentId;
}

+ (id)sharedInstance;
@property(nonatomic) long long currentId; // @synthesize currentId=_currentId;
- (void)resetIdCounter;
- (long long)nextUniqueId;
- (id)init;

@end

