//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol CBTAsstBoardThinkingViewModelUIDelegate <NSObject>
- (void)onThinkingTitleUpdated;
- (void)onStopThinkingWithCompletion:(void (^)(void))arg1;
- (void)onToggleExpanded;
@end

