//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMHeadImageView, MMImageView, NSString, UILabel;

@interface CBTContactRowView : UIView
{
    NSString *_username;
    long long _options;
    CDUnknownBlockType _onTapped;
    MMHeadImageView *_avatarView;
    UILabel *_usernameLabel;
    MMImageView *_checkMarkView;
    UIView *_separatorView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *separatorView; // @synthesize separatorView=_separatorView;
@property(retain, nonatomic) MMImageView *checkMarkView; // @synthesize checkMarkView=_checkMarkView;
@property(retain, nonatomic) UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(retain, nonatomic) MMHeadImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(copy, nonatomic) CDUnknownBlockType onTapped; // @synthesize onTapped=_onTapped;
@property(nonatomic) long long options; // @synthesize options=_options;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
- (void)setGrayed:(_Bool)arg1;
- (void)layoutSubviews;
- (void)layoutSeparatorView;
- (void)layoutCheckMarkView;
- (void)layoutUsernameLabel;
- (void)layoutAvatarView;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1 username:(id)arg2 options:(long long)arg3;

@end

