//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface CBTFootnoteDefinition : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool isFromMp; // @dynamic isFromMp;
@property(retain, nonatomic) NSString *jumpUrl; // @dynamic jumpUrl;
@property(retain, nonatomic) NSString *label; // @dynamic label;
@property(retain, nonatomic) NSString *rawContent; // @dynamic rawContent;
@property(nonatomic) unsigned int refType; // @dynamic refType;
@property(retain, nonatomic) NSString *title; // @dynamic title;

@end

