//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@interface CCardContact
{
    NSString *_m_nsCardDesc;
    NSString *_m_nsCardDescIcon;
}

+ (id)contactFromShareCardMsgContentForFTS:(id)arg1;
+ (id)contactFromShareCardMsgContent:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *m_nsCardDescIcon; // @synthesize m_nsCardDescIcon=_m_nsCardDescIcon;
@property(retain, nonatomic) NSString *m_nsCardDesc; // @synthesize m_nsCardDesc=_m_nsCardDesc;
- (void)genContactFromShareCardMsgWrapContent:(id)arg1;

@end

