//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface CheckExternalFinderOpenFeedActionBuffer : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int commentScene; // @dynamic commentScene;
@property(nonatomic) unsigned int entryCardType; // @dynamic entryCardType;
@property(nonatomic) unsigned int entryScene; // @dynamic entryScene;
@property(retain, nonatomic) NSString *exportId; // @dynamic exportId;
@property(nonatomic) int feedActionType; // @dynamic feedActionType;
@property(nonatomic) int notGetReleatedlist; // @dynamic notGetReleatedlist;
@property(nonatomic) unsigned int requestScene; // @dynamic requestScene;

@end

