//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseRequest, NSData, NSMutableArray, NSString;

@interface ColdStartFetchDataRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned long long appVersion; // @dynamic appVersion;
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(nonatomic) unsigned int fetchMode; // @dynamic fetchMode;
@property(nonatomic) unsigned int fetchType; // @dynamic fetchType;
@property(retain, nonatomic) NSString *libVersion; // @dynamic libVersion;
@property(retain, nonatomic) NSData *reqData; // @dynamic reqData;
@property(retain, nonatomic) NSMutableArray *reqItemList; // @dynamic reqItemList;
@property(retain, nonatomic) NSString *username; // @dynamic username;
@property(nonatomic) unsigned int versionType; // @dynamic versionType;

@end

