//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class LensInfo, NSString;

@protocol EmoticonLensInfoBatchCgiDelegate <NSObject>
- (void)onEmoticonLensInfoInvalid:(NSString *)arg1 errType:(long long)arg2;
- (void)onEmoticonLensInfoSuccess:(LensInfo *)arg1 forLensId:(NSString *)arg2 finish:(_Bool)arg3;
- (void)onEmoticonLensInfoFail:(NSString *)arg1;
@end

