//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView;

@interface EmoticonCustomManageMultiImagePreviewCell : UICollectionViewCell
{
    UIImageView *_imgView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

