//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSString;

@interface FindFriendRedDotEventSender : NSObject
{
    _Bool _active;
    NSMutableSet *_observingPaths;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *observingPaths; // @synthesize observingPaths=_observingPaths;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
- (void)finderRedDotDataChangedActionType:(unsigned long long)arg1 subReasonType:(unsigned long long)arg2 fromCtrlInfo:(id)arg3 toCtrlInfo:(id)arg4 disposePath:(id)arg5;
- (void)addObservingRedDotPaths:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

