//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface FinderLiveAppMsgCommentHotWordInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *content; // @dynamic content;
@property(nonatomic) unsigned int count; // @dynamic count;
@property(nonatomic) unsigned int fromCount; // @dynamic fromCount;
@property(nonatomic) unsigned int postTime; // @dynamic postTime;
@property(nonatomic) unsigned int toCount; // @dynamic toCount;

@end

