//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface FinderModFeedConfig : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int coverUrlWordMaxDiffCnt; // @dynamic coverUrlWordMaxDiffCnt;
@property(nonatomic) unsigned int descriptionMaxDiffCnt; // @dynamic descriptionMaxDiffCnt;

@end

