//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSMutableArray, NSString;

@interface FinderLiveSyncEcCouponInfoResp_WidgetInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *firstPagUrl; // @dynamic firstPagUrl;
@property(retain, nonatomic) NSMutableArray *replaceItemList; // @dynamic replaceItemList;
@property(retain, nonatomic) NSString *reportJson; // @dynamic reportJson;
@property(retain, nonatomic) NSString *secondPagUrl; // @dynamic secondPagUrl;
@property(nonatomic) unsigned int seq; // @dynamic seq;
@property(retain, nonatomic) NSString *wording; // @dynamic wording;

@end

