//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface FinderLiveGetShopShelfResponse_ShopWindowProfileInfo_ShopIconInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int shopIconType; // @dynamic shopIconType;
@property(retain, nonatomic) NSString *shopIconUrlDark; // @dynamic shopIconUrlDark;
@property(retain, nonatomic) NSString *shopIconUrlLight; // @dynamic shopIconUrlLight;

@end

