//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderContact, FinderLiveAgreementInfo;

@interface FinderCoLiveSelectGoFlagBuffer : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) FinderLiveAgreementInfo *agreementInfo; // @dynamic agreementInfo;
@property(retain, nonatomic) FinderContact *initiatorContact; // @dynamic initiatorContact;
@property(nonatomic) unsigned long long invitationId; // @dynamic invitationId;
@property(nonatomic) unsigned int settlementMode; // @dynamic settlementMode;

@end

