//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSMutableArray;

@interface FinderReddotFreqConfig_XStrategy : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *businessTypePriorities; // @dynamic businessTypePriorities;
@property(nonatomic) unsigned int historyRecordUpdateTime; // @dynamic historyRecordUpdateTime;
@property(retain, nonatomic) NSMutableArray *historyRecords; // @dynamic historyRecords;
@property(nonatomic) _Bool isResetClientRecord; // @dynamic isResetClientRecord;
@property(retain, nonatomic) NSMutableArray *pathPriorities; // @dynamic pathPriorities;

@end

