//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FLTStatusPlatformMediaSize, NSString;

@interface FLTStatusPlatformMediaItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int mediaType; // @dynamic mediaType;
@property(retain, nonatomic) NSString *originPath; // @dynamic originPath;
@property(retain, nonatomic) FLTStatusPlatformMediaSize *originSize; // @dynamic originSize;
@property(retain, nonatomic) NSString *thumbPath; // @dynamic thumbPath;
@property(retain, nonatomic) FLTStatusPlatformMediaSize *thumbSize; // @dynamic thumbSize;

@end

