//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GameHaowanUploadTask, NSArray, NSError;

@protocol GameHaowanUploadTaskDelegate <NSObject>

@optional
- (void)uploadTask:(GameHaowanUploadTask *)arg1 willRetryWithCount:(unsigned long long)arg2;
- (void)uploadTask:(GameHaowanUploadTask *)arg1 didProgressChanged:(float)arg2;
- (_Bool)uploadTask:(GameHaowanUploadTask *)arg1 didFailedWithError:(NSError *)arg2 canRetry:(_Bool)arg3;
- (void)uploadTask:(GameHaowanUploadTask *)arg1 didSucceedWithResIds:(NSArray *)arg2;
@end

