//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIScrollView;

@protocol GameCenterBannerManagerDelegate <NSObject>
- (void)bannerStateDidChanged;
- (_Bool)isNoAutoExpand;
- (double)visiableHeight;
- (double)viewHeight;
- (void)viewNeedsLayout;
- (double)navigationAreaHeight;
- (UIScrollView *)anotherPartScrollView;
- (UIScrollView *)bannerContainerView;
@end

