//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "WCPayBaseCgiDelegate-Protocol.h"

@class GetMCreditLineTokenSignResp, HoneyPayGetMCreditLineTokenCgi, WCPayBaseNetworkingError;

@protocol HoneyPayGetMCreditLineTokenCgiDelegate <WCPayBaseCgiDelegate>
- (void)getMCreditLineTokenCgi:(HoneyPayGetMCreditLineTokenCgi *)arg1 didFailWithError:(WCPayBaseNetworkingError *)arg2;
- (void)getMCreditLineTokenCgi:(HoneyPayGetMCreditLineTokenCgi *)arg1 didGetResponse:(GetMCreditLineTokenSignResp *)arg2;
@end

