//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MMUIImageView, MMUILabel;

@interface IntelligentMsgImgFigureHeaderView
{
    MMUILabel *m_titleLabel;
    MMUIImageView *m_figureImageView;
    MMUILabel *m_figureCountLabel;
}

- (void).cxx_destruct;
- (double)calculationHeight;
- (void)updateFigureImageView:(id)arg1 figureCount:(unsigned int)arg2;
- (void)layoutSubviews;
- (void)layoutFigureCountLabel;
- (void)layoutFigureImageView;
- (void)layoutTitleLabel;
- (void)layoutView;
- (id)init;

@end

