//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;

@protocol IRadarSearchExt <NSObject>

@optional
- (void)OnRetrieveLocationOk;
- (void)OnRetrieveLocationTimeout;
- (void)OnRetrieveLocationError:(int)arg1;
- (void)OnVerifyUsr:(NSString *)arg1 ErrCode:(int)arg2;
- (void)OnAddFriend:(NSString *)arg1 ErrCode:(int)arg2;
- (void)OnRadarSearch:(NSArray *)arg1 ErrCode:(int)arg2;
@end

