//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol ITPPlayerAdapterHandler <NSObject>
- (_Bool)handleStop;
- (_Bool)handleOnPrepared;
@end

