//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSMutableArray, NSString;

@interface JSAPIPreVerifyResponse_JSAPIWebCompt : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int clientReportId; // @dynamic clientReportId;
@property(retain, nonatomic) NSString *configJson; // @dynamic configJson;
@property(nonatomic) unsigned int frontendReportId; // @dynamic frontendReportId;
@property(retain, nonatomic) NSString *md5; // @dynamic md5;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) NSMutableArray *tags; // @dynamic tags;
@property(retain, nonatomic) NSString *url; // @dynamic url;

@end

