//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FlutterStandardTypedData, NSNumber, NSString;

@interface LiveForwardServiceFinderObject : NSObject
{
    FlutterStandardTypedData *_buff;
    NSNumber *_ignoreOneTimeFlag;
    NSString *_lastGMsgID;
}

+ (id)nullableFromList:(id)arg1;
+ (id)fromList:(id)arg1;
+ (id)makeWithBuff:(id)arg1 ignoreOneTimeFlag:(id)arg2 lastGMsgID:(id)arg3;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *lastGMsgID; // @synthesize lastGMsgID=_lastGMsgID;
@property(retain, nonatomic) NSNumber *ignoreOneTimeFlag; // @synthesize ignoreOneTimeFlag=_ignoreOneTimeFlag;
@property(retain, nonatomic) FlutterStandardTypedData *buff; // @synthesize buff=_buff;
- (id)toList;

@end

