//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MagicRewardBridging : NSObject
{
}

+ (id)getLocalDataWithKey:(id)arg1;
+ (void)checkPkgUpdate:(id)arg1 projectId:(id)arg2;

@end

