//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMCameraTemplatePanelReportObj : NSObject
{
    unsigned long long _captureScene;
    unsigned long long _finderPostEnterScene;
}

@property(nonatomic) unsigned long long finderPostEnterScene; // @synthesize finderPostEnterScene=_finderPostEnterScene;
@property(nonatomic) unsigned long long captureScene; // @synthesize captureScene=_captureScene;

@end

