//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface MMFinderLiveExitSqaurePanGestureHandler
{
    struct CGRect _originRecognizerViewFrame;
}

@property(nonatomic) struct CGRect originRecognizerViewFrame; // @synthesize originRecognizerViewFrame=_originRecognizerViewFrame;
- (double)progressFromCurGesturer:(id)arg1;
- (void)finishGestureRecognizer:(double)arg1;
- (void)updateGestureRecognizer:(double)arg1;
- (void)startGestureRecognizer;
- (void)setupGestureHandlerTarget:(id)arg1;
- (void)onHandleGesture:(id)arg1;
- (id)init;

@end

