//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMFinderLiveStickerItemBase;

@protocol MMFinderLiveStickerContentPickerDelegate <NSObject>

@optional
- (void)onStickerContentPickingCanceled;
- (void)onStickerContentConfirmed:(MMFinderLiveStickerItemBase *)arg1;
@end

