//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIImageView;

@interface MMFinderLiveNotifyStyleCommentPubbleAudienceShoppingCell
{
    UIImageView *_imageView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (void)updateCommentLabelOrigin;
- (void)updateNickLabelOrigin;
- (void)updateImageViewOrigin;
- (void)layoutImageView;
- (_Bool)isUITypeValid;
- (void)layoutUI;
- (id)initWithCellFrame:(id)arg1;

@end

