//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MMFinderLiveConnectMicUser;

@interface MMFinderLiveKTVSingerUserInfo : NSObject
{
    MMFinderLiveConnectMicUser *_micUser;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MMFinderLiveConnectMicUser *micUser; // @synthesize micUser=_micUser;
- (_Bool)isValid;

@end

