//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMFinderLiveStickerEditingActivatorContainerView, MMFinderLiveStickerItemBase;

@protocol MMFinderLiveStickerEditingActivatorContainerViewDelegate <NSObject>
- (void)onStickerEditingActivatorViewDoubleTappedForStickerItem:(MMFinderLiveStickerItemBase *)arg1 inContainerView:(MMFinderLiveStickerEditingActivatorContainerView *)arg2;
- (void)onStickerEditingActivatorViewTappedForStickerItem:(MMFinderLiveStickerItemBase *)arg1 inContainerView:(MMFinderLiveStickerEditingActivatorContainerView *)arg2;
@end

