//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMFinderLiveFeedCoverPreloader : NSObject
{
}

+ (void)_preloadDataItemCoverIfNeeded:(id)arg1 commentScene:(int)arg2;
+ (void)preloadDataItemsCovers:(id)arg1 commentScene:(int)arg2;

@end

