//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FinderLiveNoticeInfo, MMFinderLiveNoticeDetailsViewController;

@protocol MMFinderLiveNoticeDetailsViewControllerDelegate <NSObject>

@optional
- (void)didFinishModLiveNoticeFromViewController:(MMFinderLiveNoticeDetailsViewController *)arg1 noticeInfo:(FinderLiveNoticeInfo *)arg2;
- (void)noticeQRCodePreviewViewControllerNoticeTopChanged:(MMFinderLiveNoticeDetailsViewController *)arg1 noticeInfo:(FinderLiveNoticeInfo *)arg2;
- (void)noticeQRCodePreviewViewControllerNoticeStatusChanged:(MMFinderLiveNoticeDetailsViewController *)arg1;
- (void)noticeQRCodePreviewViewControllerDidRevokeNotice:(MMFinderLiveNoticeDetailsViewController *)arg1;
@end

