//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMUIButton, MMUILabel, MMWebImageView, NSString;

@interface MMFinderAnchorReplaySettingContainerView : UIView
{
    _Bool _canGenerateReplay;
    _Bool _isChargableLive;
    _Bool _isMemberLive;
    _Bool _replayCanBeCancelled;
    unsigned int;
    CDUnknownBlockType _actionBlock;
    MMWebImageView *_coverImageView;
    MMUILabel *_titleLabel;
    MMUILabel *_detailLabel;
    MMUIButton *_createButton;
    MMUILabel *_creatingLabel;
    MMUIButton *_completedButton;
    MMUIButton *_creatingButton;
    MMUILabel *_cannotCreateLabel;
    NSString *_liveCoverUrl;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool replayCanBeCancelled; // @synthesize replayCanBeCancelled=_replayCanBeCancelled;
@property(retain, nonatomic) NSString *liveCoverUrl; // @synthesize liveCoverUrl=_liveCoverUrl;
@property(nonatomic) _Bool isMemberLive; // @synthesize isMemberLive=_isMemberLive;
@property(nonatomic) _Bool isChargableLive; // @synthesize isChargableLive=_isChargableLive;
@property(nonatomic) _Bool canGenerateReplay; // @synthesize canGenerateReplay=_canGenerateReplay;
@property(nonatomic) unsigned int replayState; // @synthesize replayState=_replayState;
@property(retain, nonatomic) MMUILabel *cannotCreateLabel; // @synthesize cannotCreateLabel=_cannotCreateLabel;
@property(retain, nonatomic) MMUIButton *creatingButton; // @synthesize creatingButton=_creatingButton;
@property(retain, nonatomic) MMUIButton *completedButton; // @synthesize completedButton=_completedButton;
@property(retain, nonatomic) MMUILabel *creatingLabel; // @synthesize creatingLabel=_creatingLabel;
@property(retain, nonatomic) MMUIButton *createButton; // @synthesize createButton=_createButton;
@property(retain, nonatomic) MMUILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MMWebImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
- (void)createReplayAction;
- (void)layoutUI;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)createUI;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateData:(unsigned int)arg1 canGenerateReplay:(_Bool)arg2 isMemberLive:(_Bool)arg3 isChargableLive:(_Bool)arg4 liveCoverUrl:(id)arg5 replayCanBeCancelled:(_Bool)arg6 subscribedCount:(unsigned int)arg7;

@end

