//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMKEditTextOnEditorActionCallback : NSObject
{
    struct Handle<std::shared_ptr<kinda::KEditTextOnEditorActionCallback>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onEditorAction:(long long)arg1;
- (id)initWithCpp:(const void *)arg1;

@end

