//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMITransmitKvData, MMVoidCallback, MMVoidITransmitKvDataCallback, NSString;

@protocol MMKindaWalletMixManager <NSObject>
- (void)startWalletMixUseCaseImpl:(NSString *)arg1 data:(MMITransmitKvData *)arg2 successCallback:(MMVoidITransmitKvDataCallback *)arg3 cancelCallback:(MMVoidCallback *)arg4 failCallback:(MMVoidCallback *)arg5;
@end

