//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MMLiveGradientLayerView, MMLiveTaskId, NSMutableArray, NSString, UIButton;
@protocol MMLiveBeautyUnifiedOperationPanelDelegate;

@interface MMLiveBeautyUnifiedOperationPanel : UIView
{
    id <MMLiveBeautyUnifiedOperationPanelDelegate> _delegate;
    MMLiveTaskId *_taskId;
    NSMutableArray *_providerStack;
    UIView *_lightDismissView;
    UIView *_containerView;
    MMLiveGradientLayerView *_backgroundView;
    UIButton *_closeButton;
    UIButton *_settingsButton;
    UIButton *_backButton;
    UIButton *_resetButton;
    UIView *_controlPanelContainerView;
    UIView *_navigatorContainerView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *navigatorContainerView; // @synthesize navigatorContainerView=_navigatorContainerView;
@property(retain, nonatomic) UIView *controlPanelContainerView; // @synthesize controlPanelContainerView=_controlPanelContainerView;
@property(retain, nonatomic) UIButton *resetButton; // @synthesize resetButton=_resetButton;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UIButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) MMLiveGradientLayerView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *lightDismissView; // @synthesize lightDismissView=_lightDismissView;
@property(retain, nonatomic) NSMutableArray *providerStack; // @synthesize providerStack=_providerStack;
@property(retain, nonatomic) MMLiveTaskId *taskId; // @synthesize taskId=_taskId;
@property(nonatomic) __weak id <MMLiveBeautyUnifiedOperationPanelDelegate> delegate; // @synthesize delegate=_delegate;
- (id)controlPanelProviderForPage:(unsigned long long)arg1;
- (void)initializeComponents;
- (void)replaceControlPanel:(id)arg1;
- (void)popControlPanel;
- (void)pushControlPanel:(id)arg1;
- (void)onResetButtonTapped;
- (void)onBackButtonTapped;
- (void)onCloseButtonTapped;
- (void)layoutSubviews;
- (void)close;
- (void)openWithInitialPage:(unsigned long long)arg1;
@property(readonly, nonatomic) struct CGRect freeAreaFrame;
- (id)initWithLiveTaskId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

