//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTMathListMeasure : NSObject
{
}

+ (struct CGSize)sizeForLatex:(id)arg1 fontSize:(double)arg2 style:(unsigned int)arg3;

@end

