//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, OMJCDNBridgeService, OMJCDNDownloadRequest, OMJCDNUploadRequest;

@protocol OMJCDNBridgeServiceDelegate <NSObject>
- (void)cdnBridgeService:(OMJCDNBridgeService *)arg1 cancelUpload:(NSString *)arg2;
- (void)cdnBridgeService:(OMJCDNBridgeService *)arg1 beginUpload:(OMJCDNUploadRequest *)arg2;
- (void)cdnBridgeService:(OMJCDNBridgeService *)arg1 cancelDownload:(NSString *)arg2;
- (void)cdnBridgeService:(OMJCDNBridgeService *)arg1 beginDownload:(OMJCDNDownloadRequest *)arg2;
@end

