//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class LiteAppDynamicModuleCallback, MISSING_TYPE, NSDictionary, UIViewController;

@interface RealNameVerifyImpl : NSObject
{
    LiteAppDynamicModuleCallback *_callBack;
    UIViewController *_vc;
    MISSING_TYPE *_option;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *option; // @synthesize option=_option;
@property(nonatomic) __weak UIViewController *vc; // @synthesize vc=_vc;
@property(retain, nonatomic) LiteAppDynamicModuleCallback *callBack; // @synthesize callBack=_callBack;
- (void)dealloc;
- (void)handleCancelNotification:(id)arg1;
- (void)handleSuccessNotification:(id)arg1;
- (void)startRealNameVerify:(id)arg1 currentVc:(id)arg2 resultCallback:(id)arg3;

@end

