//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class IamBizBaseResponse, MISSING_TYPE, NSString, RewardUserFriendInfo, RewardUserInteractiveInfo;

@interface RewardUserInfoResp : WXPBGeneratedMessage
{
}

+ (MISSING_TYPE *)initialize;

// Remaining properties
@property(retain, nonatomic) IamBizBaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) NSString *city; // @dynamic city;
@property(retain, nonatomic) NSString *cityCode; // @dynamic cityCode;
@property(retain, nonatomic) NSString *country; // @dynamic country;
@property(retain, nonatomic) NSString *countryCode; // @dynamic countryCode;
@property(retain, nonatomic) RewardUserFriendInfo *friendInfo; // @dynamic friendInfo;
@property(nonatomic) _Bool inBlacklist; // @dynamic inBlacklist;
@property(retain, nonatomic) RewardUserInteractiveInfo *interactiveInfo; // @dynamic interactiveInfo;
@property(retain, nonatomic) NSString *province; // @dynamic province;
@property(retain, nonatomic) NSString *provinceCode; // @dynamic provinceCode;
@property(retain, nonatomic) NSString *renderMpappUrl; // @dynamic renderMpappUrl;
@property(nonatomic) unsigned int sex; // @dynamic sex;
@property(retain, nonatomic) NSString *signature; // @dynamic signature;

@end

