//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseResponse, NSData;

@interface SnsGetCdnDistanceResponse : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(nonatomic) unsigned int cityId; // @dynamic cityId;
@property(retain, nonatomic) NSData *data; // @dynamic data;
@property(nonatomic) unsigned int provinceId; // @dynamic provinceId;
@property(nonatomic) unsigned int version; // @dynamic version;

@end

