//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface SportRecordUpload : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int duration; // @dynamic duration;
@property(nonatomic) unsigned int sportCalorie; // @dynamic sportCalorie;
@property(nonatomic) unsigned int sportDistance; // @dynamic sportDistance;
@property(nonatomic) unsigned int sportNumber; // @dynamic sportNumber;
@property(nonatomic) unsigned int sportTime; // @dynamic sportTime;
@property(nonatomic) unsigned int sportTypeId; // @dynamic sportTypeId;
@property(retain, nonatomic) NSString *sportUrl; // @dynamic sportUrl;
@property(nonatomic) unsigned int startTime; // @dynamic startTime;

@end

