//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class StatisticsAppInfo, StatisticsBrandVideoAdInfo, StatisticsSnsAdInfo;

@interface StatisticsExtInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) StatisticsBrandVideoAdInfo *brandVideoAdInfo; // @dynamic brandVideoAdInfo;
@property(retain, nonatomic) StatisticsSnsAdInfo *snsAdInfo; // @dynamic snsAdInfo;
@property(retain, nonatomic) StatisticsAppInfo *sourceAppInfo; // @dynamic sourceAppInfo;

@end

