//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMListenMusicChatPlayResponse, NSData, NSString;

@protocol TingAIChatControllerListener <NSObject>
- (void)onPlayTtsProgressUpdate:(int)arg1 duration:(int)arg2 loudness:(double)arg3;
- (void)onBizEvent:(int)arg1 extraData:(NSData *)arg2;
- (void)onLevelMeterChange:(NSString *)arg1 peakPower:(float)arg2;
- (void)onStatusChanged:(NSString *)arg1 status:(int)arg2;
- (void)onResposne:(MMListenMusicChatPlayResponse *)arg1 errorCode:(long long)arg2 extraData:(NSData *)arg3;
@end

