//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;
@protocol TingDiscoverTapesListener;

@protocol TingDiscoverTapesService <NSObject>
- (void)opLike:(unsigned int)arg1 scene:(int)arg2 listenId:(NSString *)arg3 isCancel:(_Bool)arg4;
- (void)getListenCommentInfo:(unsigned int)arg1 listenIds:(NSArray *)arg2;
- (_Bool)discoverMusicTapes:(unsigned int)arg1;
- (void)removeListener:(id <TingDiscoverTapesListener>)arg1;
- (void)addListener:(id <TingDiscoverTapesListener>)arg1;
@end

