//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface TingDownloadInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *audioPath; // @dynamic audioPath;
@property(retain, nonatomic) NSString *coverPath; // @dynamic coverPath;
@property(retain, nonatomic) NSString *lyricsText; // @dynamic lyricsText;
@property(nonatomic) unsigned int type; // @dynamic type;

@end

