//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AIChatASRResult;

@protocol TingAIChatASRListener <NSObject>
- (void)onASRDetectUserSpoken;
- (void)onASRResult:(AIChatASRResult *)arg1;
@end

