//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TingObjcFeatureConfigObjcStatic : NSObject
{
}

+ (int)getHearingAidDevice;
+ (int)getHearingAidType;
+ (_Bool)isHearingAidModeEnable;
+ (_Bool)enableFinderAudioPreferPlayMv;
+ (int)preferSourceType:(id)arg1;
+ (_Bool)isTPPlayerEnableForTingItem:(id)arg1;
+ (_Bool)isEncryptExptEnable;
+ (_Bool)isEncryptEnableForTingItem:(id)arg1;
+ (_Bool)isLimitedMode;

@end

