//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIGestureRecognizer.h>

@interface UIGestureRecognizer (WCBlock)
+ (void)hookUIGestureRecognizer;
+ (id)recognizerWithHandler:(CDUnknownBlockType)arg1;
- (_Bool)swizzle_isEnabled;
@property(nonatomic) _Bool forceDisable;
- (id)getStateDesc;
@property(copy, nonatomic, setter=setHandler:) CDUnknownBlockType handler;
- (void)handleAction:(id)arg1;
- (id)initWithHandler:(CDUnknownBlockType)arg1;
@end

