//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface UnitRCObjcBaseProxyClass
{
}

- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isUnitRCProxy;
- (id)toObjc:(const void *)arg1 rcType:(unsigned int)arg2;
- (id)weakRC;
- (id)strongRC;

@end

