//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FaceRecogAVRecorder;

@interface VideoRecorderInfo : NSObject
{
    _Bool _isRecording;
    FaceRecogAVRecorder *_avRecorder;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isRecording; // @synthesize isRecording=_isRecording;
@property(retain, nonatomic) FaceRecogAVRecorder *avRecorder; // @synthesize avRecorder=_avRecorder;

@end

