//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface VoiceMessageEnhancementSessionState : NSObject
{
    _Bool _snackBarShown;
    _Bool _temporaryEnhancementEnabled;
    _Bool _systemMessageShown;
}

@property(nonatomic) _Bool systemMessageShown; // @synthesize systemMessageShown=_systemMessageShown;
@property(nonatomic) _Bool temporaryEnhancementEnabled; // @synthesize temporaryEnhancementEnabled=_temporaryEnhancementEnabled;
@property(nonatomic) _Bool snackBarShown; // @synthesize snackBarShown=_snackBarShown;

@end

