//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSMutableArray, NSMutableDictionary, NSObject, NSString, VoIPCallRecordingTask;
@protocol OS_dispatch_queue;

@interface VoIPCallRecordingService
{
    _Bool _audioBypassRegistered;
    _Bool _isProcessingTask;
    long long _state;
    NSObject<OS_dispatch_queue> *_recordingQueue;
    unsigned long long _screenShotMomentNs;
    unsigned long long _recordingOutputDurationNs;
    long long _recordingWindowMode;
    CDUnknownBlockType _pendingFutureSaveBlock;
    NSMutableArray *_pendingTasks;
    VoIPCallRecordingTask *_deferredTask;
    NSMutableDictionary *_screenShotSnapshots;
    NSMutableDictionary *_screenShotBlocks;
    double _pipelineStartTime;
    struct CGSize _recordingCanvasSize;
}

+ (unsigned long long)nowPtsNs;
+ (_Bool)isInRecordingTalking;
+ (_Bool)isEnabled;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) double pipelineStartTime; // @synthesize pipelineStartTime=_pipelineStartTime;
@property(retain, nonatomic) NSMutableDictionary *screenShotBlocks; // @synthesize screenShotBlocks=_screenShotBlocks;
@property(retain, nonatomic) NSMutableDictionary *screenShotSnapshots; // @synthesize screenShotSnapshots=_screenShotSnapshots;
@property(retain, nonatomic) VoIPCallRecordingTask *deferredTask; // @synthesize deferredTask=_deferredTask;
@property(nonatomic) _Bool isProcessingTask; // @synthesize isProcessingTask=_isProcessingTask;
@property(retain, nonatomic) NSMutableArray *pendingTasks; // @synthesize pendingTasks=_pendingTasks;
@property(copy, nonatomic) CDUnknownBlockType pendingFutureSaveBlock; // @synthesize pendingFutureSaveBlock=_pendingFutureSaveBlock;
@property(nonatomic) long long recordingWindowMode; // @synthesize recordingWindowMode=_recordingWindowMode;
@property(nonatomic) unsigned long long recordingOutputDurationNs; // @synthesize recordingOutputDurationNs=_recordingOutputDurationNs;
@property(nonatomic) unsigned long long screenShotMomentNs; // @synthesize screenShotMomentNs=_screenShotMomentNs;
@property(nonatomic) _Bool audioBypassRegistered; // @synthesize audioBypassRegistered=_audioBypassRegistered;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *recordingQueue; // @synthesize recordingQueue=_recordingQueue;
@property(nonatomic) struct CGSize recordingCanvasSize; // @synthesize recordingCanvasSize=_recordingCanvasSize;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void)p_scheduleScreenShotSnapshotCaptureWithAnchor:(unsigned long long)arg1;
- (void)p_captureScreenShotSnapshotWithAnchor:(unsigned long long)arg1;
- (void)p_doClearScreenShotPreservation;
- (void)markScreenShotPreservationEndRequested;
- (void)beginScreenShotPreservation;
- (void)onFinishScreenShot;
- (void)onMMScreenShotWillShowWithButtonHeight:(double *)arg1;
- (void)p_callCompletionOnMain:(CDUnknownBlockType)arg1 path:(id)arg2 error:(id)arg3;
- (void)p_releaseReencodedSamples:(id)arg1;
- (void)p_releaseComposedFrames:(id)arg1;
- (void)p_releaseDecodedFrames:(id)arg1;
- (id)p_generateOutputPathWithFormat:(unsigned long long)arg1;
- (void)p_writeAudioSnapshot:(id)arg1 isLocal:(_Bool)arg2 writer:(id)arg3;
- (id)p_audioConfigFromSnapshot:(id)arg1;
- (id)p_clipAudioSnapshot:(id)arg1 startNs:(unsigned long long)arg2 endNs:(unsigned long long)arg3 label:(id)arg4;
- (void)p_failPipelineWithCode:(long long)arg1 message:(id)arg2 outputPath:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)p_runRecordingPipelineWithLocalAudioSnap:(id)arg1 remoteAudioSnap:(id)arg2 uiStateSnap:(id)arg3 canvasSize:(struct CGSize)arg4 sdkVideoSnap:(id)arg5 freezeTimestampNs:(unsigned long long)arg6 localPlaceholders:(id)arg7 remotePlaceholders:(id)arg8 completion:(CDUnknownBlockType)arg9;
- (_Bool)p_placeholderSetHasAnyBuffer:(id)arg1;
- (struct CGSize)p_placeholderSizeForStyle:(long long)arg1 subSize:(struct CGSize)arg2 canvasSize:(struct CGSize)arg3;
- (void)p_collectPlaceholderNeedsForState:(id)arg1 localNeeds:(_Bool [3])arg2 remoteNeeds:(_Bool [3])arg3 localSubSize:(struct CGSize *)arg4 remoteSubSize:(struct CGSize *)arg5;
- (void)p_generateAvatarPlaceholdersWithSdkVideoSnap:(id)arg1 uiStateSnap:(id)arg2 anchorNs:(unsigned long long)arg3 canvasSize:(struct CGSize)arg4 requireLocalPlaceholder:(_Bool)arg5 requireRemotePlaceholder:(_Bool)arg6 completion:(CDUnknownBlockType)arg7;
- (_Bool)p_isCameraClosedForLocal:(_Bool)arg1 throughoutWindowStartNs:(unsigned long long)arg2 endNs:(unsigned long long)arg3 uiStateSnap:(id)arg4;
- (void)p_executeTask:(id)arg1;
- (void)p_cancelPendingFutureSaveIfNeededWithReason:(id)arg1;
- (void)p_processNextTaskIfNeeded;
- (void)p_stopRecordingOnQueue;
- (void)p_startRecordingOnQueueWithCanvasSize:(struct CGSize)arg1 completion:(CDUnknownBlockType)arg2;
- (void)saveLast5SecondsWithViewController:(id)arg1;
- (void)stopRecordingForCallEnd;
- (void)startRecordingWithCanvasSize:(struct CGSize)arg1 completion:(CDUnknownBlockType)arg2;
- (void)p_refreshRecordingWindowModeFromExpt;
- (long long)p_recordingWindowModeFromExpt;
- (void)p_refreshRecordingOutputDurationFromExpt;
- (unsigned long long)p_recordingOutputDurationSecondsFromExpt;
- (void)onServiceClearData;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

