//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class WAAgentContainerItem;

@interface WAAgentContainerCell : UICollectionViewCell
{
    WAAgentContainerItem *_containerItem;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WAAgentContainerItem *containerItem; // @synthesize containerItem=_containerItem;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

