//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AVAudioPCMBuffer, AVAudioTime;

@protocol WAAudioPlayBackDelegate <NSObject>

@optional
- (void)onWxAudioPlayBackWithSessionId:(int)arg1 data:(char *)arg2 size:(unsigned int)arg3 channels:(unsigned int)arg4 samplerate:(unsigned int)arg5 fmt:(unsigned long long)arg6;
- (void)onAudioPlayBack:(AVAudioPCMBuffer *)arg1 when:(AVAudioTime *)arg2;
@end

