//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDictionary, NSMutableArray;

@interface WAJSEventHandler_shareAppMessageToSpecificContactDirectly
{
    NSDictionary *_dic;
    NSMutableArray *_batchConvertedUsernames;
    NSMutableArray *_batchFailedOpenIds;
    unsigned long long _batchTotalCount;
    unsigned long long _batchFinishedCount;
    _Bool _forNativeWeApp;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool forNativeWeApp; // @synthesize forNativeWeApp=_forNativeWeApp;
- (void)onBatchTransferAllFinished;
- (void)onBatchCgiResponse:(id)arg1 openId:(id)arg2;
- (void)batchTransferOpenIds:(id)arg1 appId:(id)arg2;
- (void)shareWithParams:(id)arg1 username:(id)arg2;
- (void)handleShareTransID:(id)arg1;
- (void)onCgiResponse:(id)arg1 forEvent:(unsigned int)arg2;
- (void)transferOpenId:(id)arg1 appId:(id)arg2;
- (void)doShareLogicWith:(id)arg1 forNativeWeApp:(_Bool)arg2;
- (void)handleJSEvent:(id)arg1;

@end

