//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WAMainFrameTaskBarSectionOtherViewCell;

@protocol WAMainFrameTaskBarSectionOtherViewCellDelegate <NSObject>
- (void)onClickDelete:(WAMainFrameTaskBarSectionOtherViewCell *)arg1;
@end

