//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WAPlateItem : NSObject
{
    NSString *_plateStr;
}

+ (id)fromProto:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *plateStr; // @synthesize plateStr=_plateStr;
- (id)init;

@end

