//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CheckQRCodeLoginCGI, MMUIViewController, NSNumber, NSString, WCAccountFastSwitchLoginViewController, WCAccountLoginLastUserViewController, WCAccountManualAuthControlLogic;

@interface WCAccountFastSwitchLogic
{
    _Bool _isDoingAuth;
    _Bool _isCancel;
    int _loginType;
    MMUIViewController *_currentViewController;
    WCAccountFastSwitchLoginViewController *_fastSwitchViewController;
    WCAccountLoginLastUserViewController *_lastUserViewController;
    WCAccountManualAuthControlLogic *_m_manualAuthLogic;
    CheckQRCodeLoginCGI *_checkQRCodeCgi;
    NSString *_userName;
    NSString *_password;
    NSNumber *_loadingType;
}

+ (void)reportLoginAssistEnd:(id)arg1 login_assist_device_type:(int)arg2 login_assist_result:(int)arg3 login_assist_cancel_type:(int)arg4 login_assist_error_code:(int)arg5;
+ (void)reportLoginAssistSend:(id)arg1 login_assist_device_type:(int)arg2;
+ (void)reportComfirmPageClk:(id)arg1 has_sync_chat_login:(int)arg2;
+ (void)reportComfirmPageIn:(id)arg1;
+ (void)reportLoginAssistTipsAgreePageIn;
+ (void)reportLoginUseOtherDevice:(int)arg1 eventId:(int)arg2;
+ (id)getLoginTicketId;
+ (void)updateLoginTicketId:(id)arg1;
+ (id)getLoginPageSessionId;
+ (void)updateLoginPageSessionId;
+ (id)getFSBaseReportParam;
+ (void)checkFastSwitchLoginStateWithCompletionBlock:(CDUnknownBlockType)arg1;
+ (void)onCheckPushLoginURLReturnWithResponse:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
+ (void)blockFastSwitchLogin;
+ (_Bool)canFastSwitchLogin;
- (void).cxx_destruct;
@property(nonatomic) NSNumber *loadingType; // @synthesize loadingType=_loadingType;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) int loginType; // @synthesize loginType=_loginType;
@property(nonatomic) _Bool isCancel; // @synthesize isCancel=_isCancel;
@property(nonatomic) _Bool isDoingAuth; // @synthesize isDoingAuth=_isDoingAuth;
@property(retain, nonatomic) CheckQRCodeLoginCGI *checkQRCodeCgi; // @synthesize checkQRCodeCgi=_checkQRCodeCgi;
@property(retain, nonatomic) WCAccountManualAuthControlLogic *m_manualAuthLogic; // @synthesize m_manualAuthLogic=_m_manualAuthLogic;
@property(nonatomic) __weak WCAccountLoginLastUserViewController *lastUserViewController; // @synthesize lastUserViewController=_lastUserViewController;
@property(nonatomic) __weak WCAccountFastSwitchLoginViewController *fastSwitchViewController; // @synthesize fastSwitchViewController=_fastSwitchViewController;
@property(nonatomic) __weak MMUIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
- (void)stopManualAuthLoading;
- (void)startManualAuthLoading;
- (void)stopPushLoading;
- (void)startPushLoading;
- (id)OnCheckQRCodeLogicGetCurrentViewController;
- (void)onPushLoginURLConfrimed;
- (void)doAuthWithType:(int)arg1;
- (void)onPushLoginURLSuccess;
- (void)onPushLoginURLFailedWithError:(id)arg1 showToast:(_Bool)arg2 blockFastSwtich:(_Bool)arg3 needDispatch:(_Bool)arg4;
- (_Bool)onManualAuthControlLogicError:(id)arg1;
- (void)onManualAuthControlLogicStop:(unsigned long long)arg1 response:(id)arg2;
- (void)cancelLoginByOther;
- (void)cancelLoginByMyself;
- (void)stopRequest;
- (void)cancelLogin;
- (void)onPushLoginURLReturnWithResponse:(id)arg1;
- (void)startRequest;
- (void)startLogin;
- (void)dealloc;
- (id)init;
- (void)onTimeCheckExpired;
- (void)stopExpiredTimeCheck;
- (void)OnCheckQRCodeLoginScaned:(id)arg1 nickName:(id)arg2 authUrl:(id)arg3;
- (void)OnCheckQRCodeLoginConfirmedWithUserName:(id)arg1 pwd:(id)arg2 nickName:(id)arg3 headImageURL:(id)arg4;
- (void)OnCheckQRCodeLoginCancel;
- (void)OnCheckQRCodeLoginExpried;
- (void)OnCheckQRCodeLoginFail;
- (void)OnCheckQRCodeLoginUUIDExpired;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

