//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCAudioPlayerSeekingContext : NSObject
{
    double _seekTime;
}

@property(nonatomic) double seekTime; // @synthesize seekTime=_seekTime;

@end

