//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WCCanvasComponentReportUrlInfo;

@interface WCCanvasComponentReportPureImageInfo
{
    WCCanvasComponentReportUrlInfo *_imgUrlInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCCanvasComponentReportUrlInfo *imgUrlInfo; // @synthesize imgUrlInfo=_imgUrlInfo;
- (id)dictionaryRepresentation;

@end

