//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@interface WCCanvasComponentReportHalfRandomCardInfo
{
    NSString *_cardId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *cardId; // @synthesize cardId=_cardId;
- (id)dictionaryRepresentation;

@end

