//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCChatRecordZipExportHelper : NSObject
{
}

+ (id)itemProviderForZipFileName:(id)arg1 filePath:(id)arg2;
+ (id)deduplicateFileName:(id)arg1 filePath:(id)arg2 nameCountMap:(id)arg3;
+ (void)updateLatestMediaFileName:(id)arg1 toFileName:(id)arg2 inTextContent:(id)arg3;
+ (void)collectMediaProvider:(id)arg1 txtContent:(id)arg2 mediaFiles:(id)arg3 nameCountMap:(id)arg4;
+ (_Bool)createZipAtPath:(id)arg1 txtPath:(id)arg2 txtFileName:(id)arg3 mediaFiles:(id)arg4 cancelChecker:(CDUnknownBlockType)arg5 progressHandler:(CDUnknownBlockType)arg6;
+ (_Bool)createZipAtPath:(id)arg1 txtPath:(id)arg2 txtFileName:(id)arg3 mediaFiles:(id)arg4;
+ (id)zipFileName;
+ (id)textFileName;
+ (_Bool)validateDiskSpaceBeforeZipWithMediaFiles:(id)arg1;
+ (_Bool)estimateMediaFilesSize:(id)arg1 estimatedSize:(unsigned long long *)arg2;
+ (void)removeExportDirectoryForZipPath:(id)arg1;
+ (void)removeExportTempDirectory:(id)arg1;
+ (id)createTempDirectory;
+ (void)appendTextProvider:(id)arg1 toContent:(id)arg2;
+ (_Bool)msgWrap:(id)arg1 isInPointerSet:(id)arg2;
+ (id)msgWrapPointerSetWithMsgList:(id)arg1;
+ (id)generateSeparateRecordShareItemsWithMsgList:(id)arg1;
+ (id)generateMergedRecordShareItemsWithMsgList:(id)arg1;
+ (_Bool)isValidRecordMsgWrap:(id)arg1;
+ (id)buildSeparateZipPathWithMsgList:(id)arg1 zipFileName:(id)arg2 cancelChecker:(CDUnknownBlockType)arg3 progressHandler:(CDUnknownBlockType)arg4;
+ (id)buildSeparateZipPathWithMsgList:(id)arg1 cancelChecker:(CDUnknownBlockType)arg2 progressHandler:(CDUnknownBlockType)arg3;
+ (id)buildSeparateZipPathWithMsgList:(id)arg1;
+ (id)buildMergedZipPathWithMsgList:(id)arg1 zipFileName:(id)arg2 cancelChecker:(CDUnknownBlockType)arg3 progressHandler:(CDUnknownBlockType)arg4;
+ (id)buildMergedZipPathWithMsgList:(id)arg1 cancelChecker:(CDUnknownBlockType)arg2 progressHandler:(CDUnknownBlockType)arg3;
+ (id)buildMergedZipPathWithMsgList:(id)arg1;
+ (id)buildZipPathWithMsgList:(id)arg1 recordExpandMode:(long long)arg2 zipFileName:(id)arg3 cancelChecker:(CDUnknownBlockType)arg4 progressHandler:(CDUnknownBlockType)arg5;
+ (id)buildZipPathWithMsgList:(id)arg1 recordExpandMode:(long long)arg2 cancelChecker:(CDUnknownBlockType)arg3 progressHandler:(CDUnknownBlockType)arg4;
+ (_Bool)isValidZipPath:(id)arg1;
+ (id)validatedMsgList:(id)arg1;
+ (void)exportFileMessageWithMsgList:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)fileMessageWithZipPath:(id)arg1;
+ (void)exportFileItemProviderWithMsgList:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)exportZipItemProviderWithMsgList:(id)arg1 includeLegacyItems:(_Bool)arg2 recordExpandMode:(long long)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)exportZipItemProviderWithMsgList:(id)arg1 includeLegacyItems:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
+ (id)zipItemProviderWithZipPath:(id)arg1;
+ (id)fileItemProviderWithZipPath:(id)arg1;
+ (void)exportZipPathWithMsgList:(id)arg1 recordExpandMode:(long long)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)exportZipPathWithMsgList:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

