//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface WCFinderExtendedButton
{
    _Bool _disableHighlight;
}

@property(nonatomic) _Bool disableHighlight; // @synthesize disableHighlight=_disableHighlight;
- (void)setHighlighted:(_Bool)arg1;

@end

