//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCFinderExtPostPreCheckModel : NSObject
{
    NSString *_h5Wording;
    NSString *_h5Link;
}

+ (id)modelCustomPropertyMapperForConfigTag:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *h5Link; // @synthesize h5Link=_h5Link;
@property(copy, nonatomic) NSString *h5Wording; // @synthesize h5Wording=_h5Wording;

@end

