//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderMPVideoPlayStatus : NSObject
{
    _Bool _pauseVideo;
    double _startPlayVideoTime;
    double _playbackRate;
}

@property(nonatomic) double playbackRate; // @synthesize playbackRate=_playbackRate;
@property(nonatomic) _Bool pauseVideo; // @synthesize pauseVideo=_pauseVideo;
@property(nonatomic) double startPlayVideoTime; // @synthesize startPlayVideoTime=_startPlayVideoTime;

@end

