//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView, WCFinderMinimizePlayCtrl;
@protocol WCFinderMinimizeContentViewProtocol;

@protocol WCFinderMinimizePlayCtrlPlayDelegate <NSObject>
- (void)onMediaPlayContentViewSizeChanged:(UIView<WCFinderMinimizeContentViewProtocol> *)arg1;
- (void)onMediaPlayContentViewUpdated:(UIView<WCFinderMinimizeContentViewProtocol> *)arg1;
- (void)onMediaPlayInfoUpdate:(WCFinderMinimizePlayCtrl *)arg1;
- (void)onMediaPlayStateChanged:(WCFinderMinimizePlayCtrl *)arg1;
@end

