//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MMAssetInfo, OMCClipSegment, OMJClipSegment, OMJID;

@interface WCFinderVideoProducerAssetCellViewModel : NSObject
{
    _Bool _isSegmentModified;
    _Bool _isSelected;
    _Bool _isEditing;
    MMAssetInfo *_assetInfo;
    long long _segmentType;
    OMJClipSegment *_clipSegment;
    OMCClipSegment *_composingClipSegment;
    OMJID *_composingSegmentID;
    unsigned long long _editCount;
    unsigned long long _modifyCount;
    long long _cellOrder;
    CDStruct_e83c9415 _modifiedAssetTimeRangeInSegment;
}

+ (id)sectionId;
- (void).cxx_destruct;
@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(nonatomic) CDStruct_e83c9415 modifiedAssetTimeRangeInSegment; // @synthesize modifiedAssetTimeRangeInSegment=_modifiedAssetTimeRangeInSegment;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) long long cellOrder; // @synthesize cellOrder=_cellOrder;
@property(nonatomic) unsigned long long modifyCount; // @synthesize modifyCount=_modifyCount;
@property(nonatomic) unsigned long long editCount; // @synthesize editCount=_editCount;
@property(nonatomic) _Bool isSegmentModified; // @synthesize isSegmentModified=_isSegmentModified;
@property(retain, nonatomic) OMJID *composingSegmentID; // @synthesize composingSegmentID=_composingSegmentID;
@property(retain, nonatomic) OMCClipSegment *composingClipSegment; // @synthesize composingClipSegment=_composingClipSegment;
@property(retain, nonatomic) OMJClipSegment *clipSegment; // @synthesize clipSegment=_clipSegment;
@property(nonatomic) long long segmentType; // @synthesize segmentType=_segmentType;
@property(retain, nonatomic) MMAssetInfo *assetInfo; // @synthesize assetInfo=_assetInfo;
- (CDStruct_e83c9415)_getFixedTimeRangeWithPreferedStartTime:(double)arg1;
- (id)generateClipAssetInfoMapWithTimeScale:(unsigned int)arg1;
- (id)generateClipAssetInfoMap;
- (CDStruct_e83c9415)getSegmentCurrentTimeRange;
- (void)applyModifiedSegment;
- (void)resetDefaultSegmentTimeRange;
- (void)modifySegmentStartTimeSec:(double)arg1;
- (void)onEditingSegmentStartTimeSec:(double)arg1;
- (_Bool)supportsTimeRangeEditing;
- (void)configureWithAssetInfo:(id)arg1 segmentType:(long long)arg2;
- (id)initWithAssetInfo:(id)arg1 composingClipSegment:(id)arg2;
- (id)initWithAssetInfo:(id)arg1 clipSegment:(id)arg2;

@end

