//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface WCFinderLandscapeBackButton
{
}

- (void)hideSelfWithDelayTime:(double)arg1;
- (void)hideSelf;

@end

