//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCFinderPostMediaLivePhotoVideoModel : NSObject
{
    NSString *_path;
    unsigned long long _durationMs;
    unsigned long long _fileSize;
    struct CGSize _size;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(nonatomic) unsigned long long durationMs; // @synthesize durationMs=_durationMs;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
- (id)initWithLivePhotoVideoPath:(id)arg1;

@end

