//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderFullScreenAvatarConfig : NSObject
{
    unsigned long long _configFlag;
}

+ (id)defaultConfig;
@property(nonatomic) unsigned long long configFlag; // @synthesize configFlag=_configFlag;

@end

