//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WCFinderHalfScreenCreateUserViewController;

@protocol WCFinderHalfScreenCreateUserViewControllerDelegate <NSObject>

@optional
- (void)finderHalfScreenCreateUserVCDidCreateSuccess:(WCFinderHalfScreenCreateUserViewController *)arg1;
- (void)finderHalfScreenCreateUserVCDidClickEditBtn:(WCFinderHalfScreenCreateUserViewController *)arg1;
@end

