//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface WCFinderTemplateLegalTipsView
{
}

- (id)attributedTextForMessage:(id)arg1 alignment:(long long)arg2;
- (id)init;

@end

