//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WCFinderMinimizeAnimatorContext, WCFinderTransitionUserInfo, WCPlayerView;
@protocol WCFinderTrailingAnimator;

@protocol WCFinderTrailingAnimator <NSObject>

@optional
- (_Bool)shouldForceNotStartAnimation;
- (double)customAnimationDuration:(double)arg1 progress:(double)arg2;
- (void)onAnimationCleanUp:(_Bool)arg1;
- (void)onAnimationPrepare:(long long)arg1 userInfo:(WCFinderTransitionUserInfo *)arg2;
- (NSString *)enterPassPlayerTid;
- (_Bool)closureTakePlayer;
- (_Bool)shouldPinBackView;
- (_Bool)shouldDragDownAsCard;
- (_Bool)shouldGestureClosureAsCard;
- (_Bool)invalidWithIsClosure:(_Bool)arg1 userInfo:(WCFinderTransitionUserInfo *)arg2;
- (id <WCFinderTrailingAnimator>)chooseAnimatorWithOther:(id <WCFinderTrailingAnimator> (^)(void))arg1 context:(WCFinderMinimizeAnimatorContext *)arg2;
- (void)onAnimationComplete:(_Bool)arg1 context:(WCFinderMinimizeAnimatorContext *)arg2;
- (void)beforeAnimation:(WCFinderMinimizeAnimatorContext *)arg1 takeVideoPlayer:(WCPlayerView *)arg2;
- (void)beforeAnimiation:(WCFinderMinimizeAnimatorContext *)arg1;
- (void)startAnimation:(WCFinderMinimizeAnimatorContext *)arg1;
- (void)startAnimation:(WCFinderMinimizeAnimatorContext *)arg1 withoutAnimationBlockComplete:(void (^)(void))arg2;
@end

