//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCFinderFullImgBrowseActionSheetItemInfo : NSObject
{
    unsigned long long _type;
}

@property(nonatomic) unsigned long long type; // @synthesize type=_type;

@end

