//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol WCPaySingleDownloadLogicExt <NSObject>
- (void)onDownloadTaskCompletion:(long long)arg1 taskUrl:(NSString *)arg2 extraInfo:(id)arg3 filePath:(NSString *)arg4 totalLength:(unsigned long long)arg5;
@end

