//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCTagsRegister : NSObject
{
}

+ (void)registerBuildInTagItems:(id)arg1;
+ (void)registerNetTagItems:(id)arg1;
+ (void)registerTagItems:(id)arg1;

@end

