//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@interface WCWebviewNavigationEvent
{
    unsigned int _eventValue;
}

@property(nonatomic) unsigned int eventValue; // @synthesize eventValue=_eventValue;
- (id)eventDescription;
- (unsigned long long)eventHashValue;
- (id)initWithEventValue:(unsigned int)arg1;

@end

