//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class WeDropReceiveEventSharedData;
@protocol WeDropReceiveFullscreenViewProvider, WeDropReceiveModuleViewProvider, WeDropReceiveViewFullscreenLifeCycleHelper, WeDropReceiveViewModuleLifeCycleHelper;

@interface WeDropReceiveStatusMachine
{
    WeDropReceiveEventSharedData *_sharedData;
    id <WeDropReceiveModuleViewProvider> _moduleViewProvider;
    id <WeDropReceiveFullscreenViewProvider> _fullscreenViewProvider;
    id <WeDropReceiveViewFullscreenLifeCycleHelper> _fullscreenViewLifeCycleHelper;
    id <WeDropReceiveViewModuleLifeCycleHelper> _moduleViewLifeCycleHelper;
}

+ (id)machine;
- (void).cxx_destruct;
@property(nonatomic) __weak id <WeDropReceiveViewModuleLifeCycleHelper> moduleViewLifeCycleHelper; // @synthesize moduleViewLifeCycleHelper=_moduleViewLifeCycleHelper;
@property(nonatomic) __weak id <WeDropReceiveViewFullscreenLifeCycleHelper> fullscreenViewLifeCycleHelper; // @synthesize fullscreenViewLifeCycleHelper=_fullscreenViewLifeCycleHelper;
@property(nonatomic) __weak id <WeDropReceiveFullscreenViewProvider> fullscreenViewProvider; // @synthesize fullscreenViewProvider=_fullscreenViewProvider;
@property(nonatomic) __weak id <WeDropReceiveModuleViewProvider> moduleViewProvider; // @synthesize moduleViewProvider=_moduleViewProvider;
@property(retain, nonatomic) WeDropReceiveEventSharedData *sharedData; // @synthesize sharedData=_sharedData;
- (_Bool)tryEnterStatus:(unsigned long long)arg1;
- (id)initWithDefaultEvent:(id)arg1;

@end

