//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITextField.h>

@class MISSING_TYPE;

@interface _TtC9WeSwiftUIP33_004FB5E4CA810B3796715F05CA0311BC17PlatformTextField : UITextField
{
    MISSING_TYPE *isFirstResponderBinding;
    MISSING_TYPE *onDeleteBackward;
    MISSING_TYPE *textRect;
    MISSING_TYPE *editingRect;
    MISSING_TYPE *clearButtonRect;
    MISSING_TYPE *$__lazy_storage_$_clearButton;
}

- (void).cxx_destruct;
- (struct CGRect)clearButtonRectForBounds:(struct CGRect)arg1;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (void)deleteBackward;
- (_Bool)resignFirstResponder;
- (_Bool)becomeFirstResponder;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

