//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC6WeChat28MagicSclEcsBaseFlutterPlugin
{
    MISSING_TYPE *biz;
}

- (void).cxx_destruct;
- (void)onAttachedToViewController:(id)arg1;
- (void)onDetachedFromEngine:(id)arg1;
- (id)provideBiz;
- (void)onAttachedToEngine:(id)arg1;

@end

