//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIResponder.h>

@class MISSING_TYPE;

@interface _TtC6WeChat27BrandProfileMenuCoordinator : UIResponder
{
    MISSING_TYPE *currentConfig;
    MISSING_TYPE *currentContext;
    MISSING_TYPE *highlightedCell;
    MISSING_TYPE *menuHideNotification;
}

- (void).cxx_destruct;
- (id)init;
- (void)onMenuHide;
- (void)onDelete;
- (void)onMore;
- (void)onEdit;
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;

@end

