//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC6WeChat25KaraLiveEnergyStepFeature : _TtCs12_SwiftObject
{
    MISSING_TYPE *_currentStep;
    MISSING_TYPE *_timeIntervalSinceLastStep;
    MISSING_TYPE *_isFirstStep;
    MISSING_TYPE *_batteryLevel;
    MISSING_TYPE *_batteryState;
    MISSING_TYPE *_network;
    MISSING_TYPE *_screenBrightness;
    MISSING_TYPE *_lowPowerMode;
    MISSING_TYPE *_thermalState;
    MISSING_TYPE *metrics;
    MISSING_TYPE *statusCollection;
    MISSING_TYPE *eventCollection;
}

@end

