//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIViewController;

@protocol _TtP4Hero26HeroViewControllerDelegate_

@optional
- (void)heroDidCancelAnimatingToViewController:(UIViewController *)arg1;
- (void)heroDidEndAnimatingToViewController:(UIViewController *)arg1;
- (void)heroWillStartAnimatingToViewController:(UIViewController *)arg1;
- (void)heroDidCancelTransition;
- (void)heroDidEndTransition;
- (void)heroWillStartTransition;
- (void)heroDidCancelAnimatingFromViewController:(UIViewController *)arg1;
- (void)heroDidEndAnimatingFromViewController:(UIViewController *)arg1;
- (void)heroWillStartAnimatingFromViewController:(UIViewController *)arg1;
@end

