//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface AffRoamTaskErrorList_AffRoamTaskErrorLog : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *convId; // @dynamic convId;
@property(nonatomic) unsigned long long count; // @dynamic count;
@property(retain, nonatomic) NSString *detail; // @dynamic detail;
@property(nonatomic) int subType; // @dynamic subType;
@property(nonatomic) unsigned long long time; // @dynamic time;
@property(nonatomic) int type; // @dynamic type;

@end

