//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GetProfileEcCardResp_ProductCard, MMUILabel, UIImageView, UIView;

@interface BrandProfileProductCardView
{
    UIImageView *_productImageView;
    UIView *_textInfoView;
    MMUILabel *_productNameLabel;
    MMUILabel *_priceLabel;
    MMUILabel *_priceStartLabel;
    MMUILabel *_recommendLabel;
    MMUILabel *_commentLabel;
    UIView *_recommendSeparator;
    GetProfileEcCardResp_ProductCard *_productCardInfo;
}

- (void).cxx_destruct;
@property(retain, nonatomic) GetProfileEcCardResp_ProductCard *productCardInfo; // @synthesize productCardInfo=_productCardInfo;
@property(retain, nonatomic) UIView *recommendSeparator; // @synthesize recommendSeparator=_recommendSeparator;
@property(retain, nonatomic) MMUILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) MMUILabel *recommendLabel; // @synthesize recommendLabel=_recommendLabel;
@property(retain, nonatomic) MMUILabel *priceStartLabel; // @synthesize priceStartLabel=_priceStartLabel;
@property(retain, nonatomic) MMUILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) MMUILabel *productNameLabel; // @synthesize productNameLabel=_productNameLabel;
@property(retain, nonatomic) UIView *textInfoView; // @synthesize textInfoView=_textInfoView;
@property(retain, nonatomic) UIImageView *productImageView; // @synthesize productImageView=_productImageView;
- (double)layoutSubviewsAndReturnHeight;
- (void)layoutSubviews;
- (void)initSubViews;
- (void)renderWithProfileProductInfo:(id)arg1;
- (id)initWithProductCardInfo:(id)arg1;

@end

