//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface C2CVideoUtils : NSObject
{
}

+ (void)preloadSvrRecallRawVideoWhenCompressVStartDownload:(id)arg1;
+ (_Bool)syncWriteAIGCTag:(id)arg1 toVideoPath:(id)arg2;
+ (void)asyncWriteAIGCTag:(id)arg1 toVideoPath:(id)arg2 complete:(CDUnknownBlockType)arg3;
+ (id)getAIGCTagFromVideoPath:(id)arg1;
+ (_Bool)isMetadataAIGCEnable;
+ (_Bool)changeVideoMsgWrap:(id)arg1 toDownloadStaus:(unsigned int)arg2;
+ (id)tryGetImgFromVideoPath:(id)arg1 thumbImagePath:(id)arg2 maskedThumbImagePath:(id)arg3;
+ (id)generateC2CVideoPreviewDataArgsWrap:(id)arg1 aeskey:(id)arg2 url:(id)arg3 filesize:(unsigned long long)arg4 savepath:(id)arg5;
+ (id)generateC2CVideoPreviewMetaArgsWrap:(id)arg1 aeskey:(id)arg2 filesize:(unsigned long long)arg3 savepath:(id)arg4;
+ (id)generateRawDownloadArgsWrap:(id)arg1;
+ (unsigned long long)getRawVideoRecallSize:(id)arg1 recallDuration:(unsigned int)arg2 recallPercent:(unsigned int)arg3;
+ (struct basic_string<char, std::char_traits<char>, std::allocator<char>>)generateRawVideoRecallBizReqPayloadContent:(id)arg1;
+ (struct basic_string<char, std::char_traits<char>, std::allocator<char>>)getRawRecallBizReqPayloadWhenRVDownloading:(id)arg1;
+ (id)generateDownloadArgsWrap:(id)arg1;
+ (_Bool)IsOpenRawPreloadSvrRecall;

@end

