//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary, NSString;

@interface CBTAsstNoteViewModel
{
    _Bool _isDataFromNative;
    NSString *_title;
    NSString *_content;
    unsigned long long _favId;
    NSString *_cardActionKey;
    NSDictionary *_cardData;
    NSString *_cardId;
    NSString *_cardName;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *cardName; // @synthesize cardName=_cardName;
@property(copy, nonatomic) NSString *cardId; // @synthesize cardId=_cardId;
@property(retain, nonatomic) NSDictionary *cardData; // @synthesize cardData=_cardData;
@property(nonatomic) _Bool isDataFromNative; // @synthesize isDataFromNative=_isDataFromNative;
@property(copy, nonatomic) NSString *cardActionKey; // @synthesize cardActionKey=_cardActionKey;
@property(nonatomic) unsigned long long favId; // @synthesize favId=_favId;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)getCellReuseId;
- (double)mesureContentViewHeightWithWidth:(double)arg1;
- (void)parseCardData;
- (id)initWithCardWrap:(id)arg1 delegate:(id)arg2;

@end

