//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CBTMomentCPP2NativeCaller, ChatBotMomentDramaInfo, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface CBTMomentMgr
{
    _Bool _isSupportMoment;
    ChatBotMomentDramaInfo *_dramaInfo;
    CBTMomentCPP2NativeCaller *_nativeHelper;
    NSObject<OS_dispatch_queue> *_serialQueue;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) CBTMomentCPP2NativeCaller *nativeHelper; // @synthesize nativeHelper=_nativeHelper;
@property(retain, nonatomic) ChatBotMomentDramaInfo *dramaInfo; // @synthesize dramaInfo=_dramaInfo;
@property(nonatomic) _Bool isSupportMoment; // @synthesize isSupportMoment=_isSupportMoment;
- (void)onGetBizId1:(long long)arg1 data:(id)arg2;
- (void)clearRedDot:(id)arg1 sinceSeqId:(unsigned long long)arg2;
- (unsigned int)getRedDotCountForType:(id)arg1;
- (id)getLastestInteractionInfo:(id)arg1;
- (id)loadMoreInteractionInfo:(id)arg1 sinceTime:(unsigned long long)arg2 isHistoryList:(_Bool)arg3 limite:(unsigned int)arg4;
- (void)setMainFrameRedDot:(_Bool)arg1;
- (_Bool)needMainFrameRedDot;
- (_Bool)GetNeedTimeLineTabRedDot;
- (void)SetNeedTimeLineTabRedDot:(_Bool)arg1;
- (void)setTimelineEntry:(_Bool)arg1;
- (_Bool)enableTimelineEntry;
- (unsigned int)getTimelineType;
- (void)setTimelineType:(unsigned int)arg1;
- (id)generateDramaInfoString;
- (void)reportReadMoment;
- (void)commentPost:(id)arg1 commentQuery:(id)arg2 replyComment:(id)arg3 userInfo:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)uninterestedPost:(_Bool)arg1 objectId:(id)arg2 interactionScene:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
- (void)likePost:(_Bool)arg1 objectId:(id)arg2 interactionScene:(unsigned int)arg3 completion:(CDUnknownBlockType)arg4;
@property(nonatomic) long long switchMode;
- (void)checkAndUpdateMainFrameLeftTopBtn;
- (void)onRecvNotify:(id)arg1;
- (void)onServiceClearData;
- (void)postChatBotMoment:(id)arg1 withType:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)batchGetMoments:(id)arg1 type:(unsigned int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)loadMomentData:(int)arg1 withCursorid:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)preloadMomentItemList:(id)arg1;
- (void)preloadMomentVideo;
- (void)onServiceInit;
- (void)onRecvNewInteraction;
- (void)onMomentItemUpdate:(id)arg1;
- (void)onLoadMoments:(int)arg1 momentModel:(id)arg2 isFirstLoad:(_Bool)arg3 cursorId:(id)arg4;
- (void)refreshBadge:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

