//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface Channel : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *cantSendReason; // @dynamic cantSendReason;
@property(nonatomic) unsigned int channelId; // @dynamic channelId;
@property(retain, nonatomic) NSString *desc; // @dynamic desc;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) _Bool readOnly; // @dynamic readOnly;
@property(nonatomic) unsigned long long unreadMsgCount; // @dynamic unreadMsgCount;

@end

