//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CMessageWrap, NSString;

@interface ChatBotTaskInfo : NSObject
{
    CMessageWrap *_m_wrapMsg;
    NSString *_m_nsClientMsgID;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *m_nsClientMsgID; // @synthesize m_nsClientMsgID=_m_nsClientMsgID;
@property(retain, nonatomic) CMessageWrap *m_wrapMsg; // @synthesize m_wrapMsg=_m_wrapMsg;

@end

