//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class MMWebImageView, NSURL;

@interface ChatBotImageCell : UICollectionViewCell
{
    MMWebImageView *_imageView;
    NSURL *_imageURL;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) MMWebImageView *imageView; // @synthesize imageView=_imageView;
- (void)prepareForReuse;
- (void)setImagePath:(id)arg1;
- (void)layoutSubviews;
- (void)layoutImageView;

@end

