//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class EcsFinderFeedPopupViewModel, NSString;

@interface EcsFinderFeedPopupAngel
{
    EcsFinderFeedPopupViewModel *_dataVM;
}

- (void).cxx_destruct;
@property(retain, nonatomic) EcsFinderFeedPopupViewModel *dataVM; // @synthesize dataVM=_dataVM;
- (void)resetCellsAlpha:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollToIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)reloadData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

