//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface EcsJumpInfo_EcsHtml5Info_HalfPageConfig : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int backMode; // @dynamic backMode;
@property(nonatomic) _Bool disableClickBgMaskToClose; // @dynamic disableClickBgMaskToClose;
@property(nonatomic) _Bool forcePortrait; // @dynamic forcePortrait;
@property(nonatomic) double heightPercent; // @dynamic heightPercent;
@property(nonatomic) _Bool hideBgMask; // @dynamic hideBgMask;
@property(nonatomic) _Bool naviNonTransparent; // @dynamic naviNonTransparent;
@property(nonatomic) _Bool showRefreshButton; // @dynamic showRefreshButton;
@property(nonatomic) _Bool showShareButton; // @dynamic showShareButton;

@end

