//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface EcsMidasPayLogger : NSObject
{
}

- (void)logWithLevelName:(id)arg1 moduleName:(id)arg2 log:(id)arg3;
- (void)startLogger;

@end

