//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface EcsOpenContextData_WxaExtraData : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *extraParamInfo; // @dynamic extraParamInfo;
@property(nonatomic) _Bool finderStopPlaybackAfterOpenLiteApp; // @dynamic finderStopPlaybackAfterOpenLiteApp;
@property(nonatomic) int forceAppVersion; // @dynamic forceAppVersion;
@property(nonatomic) _Bool forceAutoFullScreenWhenTap; // @dynamic forceAutoFullScreenWhenTap;
@property(nonatomic) _Bool forceEnableExpandToStatusBarTop; // @dynamic forceEnableExpandToStatusBarTop;
@property(nonatomic) _Bool forceForbidExpandGesture; // @dynamic forceForbidExpandGesture;
@property(nonatomic) _Bool forceHalfPage; // @dynamic forceHalfPage;
@property(nonatomic) _Bool forceHalfPageTransparent; // @dynamic forceHalfPageTransparent;
@property(nonatomic) _Bool forceSilentLaunch; // @dynamic forceSilentLaunch;
@property(retain, nonatomic) NSString *referrerInfoExtraData; // @dynamic referrerInfoExtraData;
@property(retain, nonatomic) NSString *sceneNote; // @dynamic sceneNote;

@end

