//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CAGradientLayer, CAReplicatorLayer, EmoticonCustomOriginImgUploadTask, MMUIView, NSMutableArray, NSString;

@interface EmoticonCustomEditImageLayoutView
{
    _Bool _hasCroped;
    _Bool _hasAddText;
    _Bool _hasRemoveBg;
    _Bool _hasDeleteAsset;
    _Bool _needRemoveBg;
    NSMutableArray *_assetsEditTracker;
    NSMutableArray *_originImages;
    NSMutableArray *_originImageDatas;
    NSMutableArray *_removeBgImages;
    NSMutableArray *_currentImageAttrArray;
    CAReplicatorLayer *_replicatorLayer;
    CAGradientLayer *_animateMaskLayer;
    MMUIView *_animateMaskView;
    EmoticonCustomOriginImgUploadTask *_uploadTask;
}

- (void).cxx_destruct;
@property(retain, nonatomic) EmoticonCustomOriginImgUploadTask *uploadTask; // @synthesize uploadTask=_uploadTask;
@property(retain, nonatomic) MMUIView *animateMaskView; // @synthesize animateMaskView=_animateMaskView;
@property(retain, nonatomic) CAGradientLayer *animateMaskLayer; // @synthesize animateMaskLayer=_animateMaskLayer;
@property(retain, nonatomic) CAReplicatorLayer *replicatorLayer; // @synthesize replicatorLayer=_replicatorLayer;
@property(retain, nonatomic) NSMutableArray *currentImageAttrArray; // @synthesize currentImageAttrArray=_currentImageAttrArray;
@property(retain, nonatomic) NSMutableArray *removeBgImages; // @synthesize removeBgImages=_removeBgImages;
@property(retain, nonatomic) NSMutableArray *originImageDatas; // @synthesize originImageDatas=_originImageDatas;
@property(retain, nonatomic) NSMutableArray *originImages; // @synthesize originImages=_originImages;
@property(nonatomic) _Bool needRemoveBg; // @synthesize needRemoveBg=_needRemoveBg;
@property(nonatomic) _Bool hasDeleteAsset; // @synthesize hasDeleteAsset=_hasDeleteAsset;
@property(nonatomic) _Bool hasRemoveBg; // @synthesize hasRemoveBg=_hasRemoveBg;
@property(nonatomic) _Bool hasAddText; // @synthesize hasAddText=_hasAddText;
@property(nonatomic) _Bool hasCroped; // @synthesize hasCroped=_hasCroped;
@property(retain, nonatomic) NSMutableArray *assetsEditTracker; // @synthesize assetsEditTracker=_assetsEditTracker;
- (void)onEmoticonUploadFailWithImg:(id)arg1;
- (void)onEmoticonUploadSuccessWithImg:(id)arg1 url:(id)arg2;
- (void)runOnMainThread:(CDUnknownBlockType)arg1;
- (void)dealWithRemoveBgImage:(id)arg1;
- (void)dealWithRemoveBgUrl:(id)arg1;
- (void)requestRemoveBackgroundImage:(id)arg1;
- (void)removeBackgroundFail;
- (void)stopBorderAnimation;
- (void)startBorderAnimation;
- (void)startGetRemoveBgImage;
- (void)showOriginImageWithArray:(id)arg1;
- (void)recoverToOriginImage;
- (id)getOriginalImage:(long long)arg1;
- (void)setRemoveBgBtnWithColor:(id)arg1;
- (void)onImageRemoveBg:(id)arg1;
- (void)doActionTraceWithType:(unsigned long long)arg1 type:(unsigned long long)arg2;
- (void)onCropEditImage:(id)arg1;
- (void)onTextEditImage:(id)arg1;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (void)endEditImageView;
- (void)OnClickEditImageDoneBarButton;
- (void)OnCancel;
- (void)OnClickEditImageBackBarButton;
- (_Bool)currentImageFirstToSquare;
- (void)onCropDone;
- (void)confirmEditText:(id)arg1 withColor:(id)arg2 style:(unsigned long long)arg3 backgroundColor:(id)arg4;
- (void)onMoveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)onClickItemFromIndex:(long long)arg1 toIndex:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)initGifImageView;
- (void)initMaskLayer;
- (void)reloadBottomEditImageBar;
- (void)reloadTopEditImageBar;
- (void)initNextBtn;
- (void)deleteCrtAsset:(unsigned long long)arg1 sender:(id)arg2;
- (void)OnSelectedButtonClicked:(id)arg1;
- (void)initSelectBtn;
- (void)initTopEditImageBar;
- (void)initSelectedCollectionView;
- (void)onEditImage:(unsigned long long)arg1 withEditEntrance:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

