//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface F2FDoodleDataStart : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int actionType; // @dynamic actionType;
@property(nonatomic) float left; // @dynamic left;
@property(nonatomic) unsigned long long timestamp; // @dynamic timestamp;
@property(nonatomic) float top; // @dynamic top;

@end

