//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderPopupDisplayTimingConfig, FinderPopupShowInfo_ShowInfoItem;

@interface FinderPopupShowInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) FinderPopupShowInfo_ShowInfoItem *bubbleShowInfo; // @dynamic bubbleShowInfo;
@property(retain, nonatomic) FinderPopupShowInfo_ShowInfoItem *cardShowInfo; // @dynamic cardShowInfo;
@property(nonatomic) unsigned long long displayTabFlag; // @dynamic displayTabFlag;
@property(retain, nonatomic) FinderPopupDisplayTimingConfig *displayTiming; // @dynamic displayTiming;

@end

