//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface FinderObjectWordingInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;
+ (unsigned long long)columnTypeForWCDB;
+ (id)unarchiveWithWCTValue:(id)arg1;
- (id)archivedWCTValue;

// Remaining properties
@property(retain, nonatomic) NSString *wording; // @dynamic wording;
@property(nonatomic) unsigned int wordingType; // @dynamic wordingType;

@end

