//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderLiteAppParam, NSMutableArray;

@interface FinderSectionQAInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *answerContentList; // @dynamic answerContentList;
@property(retain, nonatomic) FinderLiteAppParam *qaTabLiteApp; // @dynamic qaTabLiteApp;
@property(nonatomic) unsigned int qaTotalCount; // @dynamic qaTotalCount;

@end

