//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class FinderLiveAnchorClosePageDataInfo, NSMutableArray;

@interface FinderLiveAnchorCloseLivePageData : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) FinderLiveAnchorClosePageDataInfo *closePageInfo; // @dynamic closePageInfo;
@property(retain, nonatomic) NSMutableArray *unitList; // @dynamic unitList;

@end

