//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@interface FinderObjectOriginalInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int originalAuditStatus; // @dynamic originalAuditStatus;
@property(nonatomic) unsigned int originalPlanVer; // @dynamic originalPlanVer;

@end

