//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface GameIndexMyGameRelated_IndexMyGameVideoCenterTpl_IndexMyGameVideoItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *desc; // @dynamic desc;
@property(retain, nonatomic) NSString *detailDesc; // @dynamic detailDesc;
@property(retain, nonatomic) NSString *externInfo; // @dynamic externInfo;
@property(retain, nonatomic) NSString *jumpUrl; // @dynamic jumpUrl;
@property(retain, nonatomic) NSString *picUrl; // @dynamic picUrl;
@property(retain, nonatomic) NSString *tagColor; // @dynamic tagColor;
@property(retain, nonatomic) NSString *tagName; // @dynamic tagName;
@property(retain, nonatomic) NSString *title; // @dynamic title;

@end

