//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface IamBizPersonalCenterRedDotManager : NSObject
{
    TaskIdConvertor_b0147701 task_id_convertor;
    struct shared_ptr<biz::IamBizPersonalCenterRedDotManagerCppCover> cpp_cover;
    struct weak_ptr<biz::IamBizPersonalCenterRedDotManagerDispatcher> cpp_dispatcher;
}

+ (id)buildZidlObjForHolder:(const void *)arg1 svrIdentity:(const void *)arg2 refCntManager:(void *)arg3;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (void)unsubscribeCreatorTextRedDotUpdatedEvent:(id)arg1;
- (void)subscribeCreatorTextRedDotUpdatedEvent:(id)arg1 eventBlock:(CDUnknownBlockType)arg2;
- (void)subscribeCreatorTextRedDotUpdatedEvent:(id)arg1 on:(id)arg2 eventBlock:(CDUnknownBlockType)arg3;
- (void)notifyCreatorTextRedDotUpdated:(id)arg1;
- (void)unsubscribeRedDotUpdatedEvent:(id)arg1;
- (void)subscribeRedDotUpdatedEvent:(id)arg1 eventBlock:(CDUnknownBlockType)arg2;
- (void)subscribeRedDotUpdatedEvent:(id)arg1 on:(id)arg2 eventBlock:(CDUnknownBlockType)arg3;
- (void)getRedDotInfoAsync:(int)arg1 on:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getRedDotInfoAsync:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getRedDotUpdateInfoAsync:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getRedDotUpdateInfoAsync:(CDUnknownBlockType)arg1;
- (void)notifyRedDotInfoUpdated:(id)arg1;
- (void)getRedDotUpdateTimestampAsync:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getRedDotUpdateTimestampAsync:(CDUnknownBlockType)arg1;
- (void)setRedDotEnable:(int)arg1 enable:(_Bool)arg2;
- (void)getRedDotEnableAsync:(int)arg1 on:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getRedDotEnableAsync:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)unsubscribeEnterWorksEntryTimestampChangedEvent:(id)arg1;
- (void)subscribeEnterWorksEntryTimestampChangedEvent:(id)arg1 eventBlock:(CDUnknownBlockType)arg2;
- (void)subscribeEnterWorksEntryTimestampChangedEvent:(id)arg1 on:(id)arg2 eventBlock:(CDUnknownBlockType)arg3;
- (void)notifyEnterWorksEntryTimestampChanged:(unsigned long long)arg1;
- (void)getLastEnterWorksEntryTimestampAsync:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getLastEnterWorksEntryTimestampAsync:(CDUnknownBlockType)arg1;
- (void)recordEnterWorksEntryTimestamp;
- (void)updateConsumerNotifyRedDotCount:(int)arg1;
- (void)updateFansMsgRedDotCount:(id)arg1 count:(int)arg2 incrementCount:(int)arg3 incrementWording:(id)arg4 shouldUpdateIncrementTimestamp:(_Bool)arg5;
- (void)updateRedDotInfo:(_Bool)arg1;
- (void)cleanRedDot:(int)arg1;
- (void)getCreatorWxaDataAsync:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getCreatorWxaDataAsync:(CDUnknownBlockType)arg1;
- (void)getCreatorTextRedDotAsync:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getCreatorTextRedDotAsync:(CDUnknownBlockType)arg1;
- (void)getRedDotBufferAsync:(int)arg1 on:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getRedDotBufferAsync:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getRedDotCountAsync:(int)arg1 on:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getRedDotCountAsync:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setServiceProxyType:(int)arg1;
- (id)init;
- (id)zidlObjToHolder;
- (id)init:(id)arg1 createName:(const void *)arg2 svrIdentity:(const void *)arg3;
- (id)initForZidlPrivate;
- (void)setDispatcher:(const void *)arg1;
- (shared_ptr_2223d118)getDispatcher;

@end

