//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class TPPlaybackInfo, TPStrategyContext;

@protocol ITPStrategy <NSObject>
- (void)addStrategyContext:(TPStrategyContext *)arg1;
- (long long)playerTypeForRetry:(TPPlaybackInfo *)arg1;
- (long long)playerTypeForOpen:(TPPlaybackInfo *)arg1;
@end

