//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@protocol IUiUtilExt <NSObject>

@optional
- (void)onTabBarRootViewControllerDidAppear;
- (void)onNavigationBarAlphaChanged;
- (void)onNavigationBarHiddenChanged;
- (void)onNavigationBarFrameChanged;
- (void)onStatusBarHiddenChanged:(long long)arg1;
- (void)onTopBarFrameChanged;
- (void)onMainWindowFrameChangedFrom:(struct CGRect)arg1 to:(struct CGRect)arg2;
- (void)onMainWindowFrameChanged;
@end

