//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@protocol IWAJSContextWifiProtocol

@optional
- (void)onWifiConfigDone:(int)arg1 errMsg:(NSString *)arg2;
@end

