//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@protocol MagicPkgDownloadExt

@optional
- (void)onPkgUpdateFail:(NSString *)arg1 reason:(unsigned long long)arg2;
- (void)onPkgUpdateSuccess:(NSString *)arg1 pkgVersion:(NSString *)arg2;
@end

