//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MJSegmentSpeedInspectorView;

@protocol MJSegmentSpeedInspectorViewDelegate <NSObject>

@optional
- (void)speedInspector:(MJSegmentSpeedInspectorView *)arg1 didSelectRawSpeedRatio:(long long)arg2;
- (void)speedInspector:(MJSegmentSpeedInspectorView *)arg1 willSelectRawSpeedRatio:(long long)arg2;
@end

