//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CMessageWrap, ThumbImageUploader;

@interface MMAppMsgThumbTask : NSObject
{
    _Bool _isCancelled;
    CDUnknownBlockType _completion;
    CMessageWrap *_message;
    ThumbImageUploader *_thumbUploader;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ThumbImageUploader *thumbUploader; // @synthesize thumbUploader=_thumbUploader;
@property(retain, nonatomic) CMessageWrap *message; // @synthesize message=_message;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool isCancelled; // @synthesize isCancelled=_isCancelled;
- (_Bool)canGenerateThumb;
- (void)cancel;
- (void)startUpload;
- (void)generateAndUploadThumb:(CDUnknownBlockType)arg1;
- (void)uploadThumb:(CDUnknownBlockType)arg1;
- (id)initWithMessage:(id)arg1;

@end

