//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface MMAssetFetchError : NSObject
{
    long long _code;
    NSDictionary *_errorInfo;
}

+ (id)errorWithCode:(long long)arg1 info:(id)arg2;
+ (id)errorWithCode:(long long)arg1;
+ (id)defaultError;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *errorInfo; // @synthesize errorInfo=_errorInfo;
@property(nonatomic) long long code; // @synthesize code=_code;

@end

