//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MMBGMPanelPublishContext, MMBGMSelectedTabViewModel, NSString, UILabel, UITableView, UITableViewDiffableDataSource, WCFinderAnimationLoadingView, WCTimeLineFooterView;
@protocol MMBGMSelectedTabManagerDelegate;

@interface MMBGMSelectedTabManager : NSObject
{
    _Bool _isAutoStopped;
    id <MMBGMSelectedTabManagerDelegate> _delegate;
    MMBGMSelectedTabViewModel *_viewModel;
    MMBGMPanelPublishContext *_publishContext;
    long long _snsEditSource;
    long long _currentIndex;
    UITableView *_tableView;
    WCTimeLineFooterView *_footerView;
    UITableViewDiffableDataSource *_diffDataSource;
    UILabel *_noMusicTipsLabel;
    WCFinderAnimationLoadingView *_loadingView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isAutoStopped; // @synthesize isAutoStopped=_isAutoStopped;
@property(retain, nonatomic) WCFinderAnimationLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UILabel *noMusicTipsLabel; // @synthesize noMusicTipsLabel=_noMusicTipsLabel;
@property(retain, nonatomic) UITableViewDiffableDataSource *diffDataSource; // @synthesize diffDataSource=_diffDataSource;
@property(retain, nonatomic) WCTimeLineFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) long long snsEditSource; // @synthesize snsEditSource=_snsEditSource;
@property(retain, nonatomic) MMBGMPanelPublishContext *publishContext; // @synthesize publishContext=_publishContext;
@property(retain, nonatomic) MMBGMSelectedTabViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <MMBGMSelectedTabManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)genReportDict;
- (void)setupCellRemoveActionReportInfoWithEventID:(id)arg1 musicData:(id)arg2;
- (void)setupTabReportInfoWithEventID:(id)arg1;
- (void)forceDeselectAllVisibleCells;
- (void)setAllCellUnSelected;
- (id)bgmSelectedTabTableViewCellGetPanelConfig:(id)arg1;
- (id)bgmSelectedTabTableViewCellGetSearchWord:(id)arg1;
- (unsigned long long)bgmSelectedTabTableViewCellGetTabType:(id)arg1;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (id)currentSelectedMusicData;
- (unsigned long long)musicTabVMGetMaterialDuration:(id)arg1;
- (void)handleMusicTabVMDataChange:(id)arg1;
- (void)musicTabVMDataChange:(id)arg1;
- (void)onBgmCell:(id)arg1 didUnfavMusicData:(id)arg2;
- (void)onBgmCell:(id)arg1 didFavMusicData:(id)arg2;
- (void)onBgmCell:(id)arg1 didClickEditMusic:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 trailingSwipeActionsConfigurationForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)applyDiffSnapshot;
- (void)reloadTableViewCellAtIndex:(unsigned long long)arg1;
- (void)reloadTableView;
- (void)updateTableViewFrame:(struct CGRect)arg1;
- (void)setSelfViewWithFrame:(struct CGRect)arg1 toSuperView:(id)arg2;
- (_Bool)isLyricsCellType;
- (struct CGRect)viewFrame;
- (void)onSwitchToThisPage;
- (void)manualSetCellAtIndex:(unsigned long long)arg1 isSelected:(_Bool)arg2;
- (void)startLoadingAnimation;
- (id)musicDataAtIndex:(unsigned long long)arg1;
- (void)selectMusicAtIndex:(unsigned long long)arg1 shouldInvokeSelectedFunc:(_Bool)arg2;
- (void)selectMusicAtIndex:(unsigned long long)arg1;
- (void)selectFirstMusicIfNeeded;
- (void)autoStopSelectedCellPlayingState;
- (void)autoSetSelectedCellPlayingState;
- (id)initWithTabModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

