//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FinderLiveBattleSettingInfo, NSArray;

@interface MMFinderLiveFeedTransferData : NSObject
{
    FinderLiveBattleSettingInfo *_battleSettings;
    NSArray *_comments;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *comments; // @synthesize comments=_comments;
@property(retain, nonatomic) FinderLiveBattleSettingInfo *battleSettings; // @synthesize battleSettings=_battleSettings;
- (id)useComments;

@end

