//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MMFinderLiveActivityTaskId, RefreshCommentResponse;

@protocol MMFinderLiveOlyBarrageDataExt <NSObject>

@optional
- (void)onFinderLiveOlyBarrageDataUpdate:(RefreshCommentResponse *)arg1 taskId:(MMFinderLiveActivityTaskId *)arg2;
@end

