//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface MMFinderLiveGiftAttackRewardPlayContext : NSObject
{
    NSMutableDictionary *_renderContextDict;
    long long _renderEnv;
}

- (void).cxx_destruct;
@property(nonatomic) long long renderEnv; // @synthesize renderEnv=_renderEnv;
@property(retain, nonatomic) NSMutableDictionary *renderContextDict; // @synthesize renderContextDict=_renderContextDict;
- (_Bool)isValid;

@end

