//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class FinderBulkBuyInfo, MMFinderLiveBulkBuyPromoteContentView, NSString;

@interface MMFinderLiveBulkBuyPromotePubbleContentView
{
    _Bool _closeBySelf;
    unsigned int _startExposingTime;
    MMFinderLiveBulkBuyPromoteContentView *_bulkBuyView;
    FinderBulkBuyInfo *_bulkBuyInfo;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool closeBySelf; // @synthesize closeBySelf=_closeBySelf;
@property(nonatomic) unsigned int startExposingTime; // @synthesize startExposingTime=_startExposingTime;
@property(retain, nonatomic) FinderBulkBuyInfo *bulkBuyInfo; // @synthesize bulkBuyInfo=_bulkBuyInfo;
@property(retain, nonatomic) MMFinderLiveBulkBuyPromoteContentView *bulkBuyView; // @synthesize bulkBuyView=_bulkBuyView;
- (void)startHideAnimationWithPart1Duration:(double)arg1 part2Duration:(double)arg2;
- (void)startDisplayAnimationWithPart1Duration:(double)arg1 part2Duration:(double)arg2;
- (void)onWebImageGetDifferentSize;
- (void)onShowed;
- (void)onDismissed;
- (void)onClosed;
- (void)reportForExpose;
- (void)onBulkBuyPromoteContentViewActionButtonClicked:(id)arg1;
- (void)handleSingleTapGesture:(id)arg1;
- (void)updateFromSyncPromoteResp:(id)arg1;
- (void)updatepromoteBuffer:(id)arg1;
- (void)updatePromoteItem:(id)arg1;
- (_Bool)isCurrentPromoteItem:(id)arg1;
- (void)refreshData;
- (void)layoutUI;
- (void)convertPromoteMsgInfo:(id)arg1;
- (id)initWithPromoteMsgInfo:(id)arg1 taskId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

