//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "MMLiveOnlineUserLogicDelegate-Protocol.h"

@class NSArray, NSError, NSString;

@protocol MMGroupLiveOnlineUserLogicDelegate <MMLiveOnlineUserLogicDelegate>
- (void)onKickAudienceForGroupLiveWithError:(NSError *)arg1 userName:(NSString *)arg2;
- (void)onFetchGroupOnlineUserListWithError:(NSError *)arg1 userList:(NSArray *)arg2;
@end

