//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class MMListenItem, NSString;

@interface MMListenMusicChatRoomInfo_PlayingItemInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) _Bool isFromAiHelper; // @dynamic isFromAiHelper;
@property(retain, nonatomic) MMListenItem *listenItem; // @dynamic listenItem;
@property(nonatomic) unsigned long long startTime; // @dynamic startTime;
@property(retain, nonatomic) NSString *uuid; // @dynamic uuid;

@end

