//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MMFinderLiveRewardGiftItem, MMLiveRewardGiftPreviewWindow;

@protocol MMLiveRewardGiftPreviewWindowDelegate <NSObject>

@optional
- (void)onClickAIGCGiftJumpAction:(MMLiveRewardGiftPreviewWindow *)arg1 giftItem:(MMFinderLiveRewardGiftItem *)arg2;
- (void)onClickActivityUnlockGiftJumpAction:(MMLiveRewardGiftPreviewWindow *)arg1 giftItem:(MMFinderLiveRewardGiftItem *)arg2;
- (void)onSendButtonClickedForGiftItem:(MMFinderLiveRewardGiftItem *)arg1;
@end

