//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface MMListenItemCoverColor : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *darkColorRgb; // @dynamic darkColorRgb;
@property(retain, nonatomic) NSString *lightColorRgb; // @dynamic lightColorRgb;

@end

