//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class CAGradientLayer, MMScreenShotForwardButton;

@interface MMScreenShotForwardView : UIView
{
    double _keyboardHeight;
    double _toolViewHeight;
    CDUnknownBlockType _onClickForwardButton;
    MMScreenShotForwardButton *_forwardButton;
    UIView *_bottomBkgView;
    CAGradientLayer *_bottomGradientLayer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CAGradientLayer *bottomGradientLayer; // @synthesize bottomGradientLayer=_bottomGradientLayer;
@property(retain, nonatomic) UIView *bottomBkgView; // @synthesize bottomBkgView=_bottomBkgView;
@property(retain, nonatomic) MMScreenShotForwardButton *forwardButton; // @synthesize forwardButton=_forwardButton;
@property(copy, nonatomic) CDUnknownBlockType onClickForwardButton; // @synthesize onClickForwardButton=_onClickForwardButton;
@property(nonatomic) double toolViewHeight; // @synthesize toolViewHeight=_toolViewHeight;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
- (_Bool)isLandScape;
- (void)stopLoading;
- (void)startLoading;
- (id)getTopVisibleViewController;
- (double)additionalHeight;
- (void)layoutUI;
- (void)layoutSubviews;
- (void)initViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

