//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface NSObject (GCThrottle)
- (void)checkNil;
- (void)checkShouldDeallocAfterTime:(double)arg1;
- (void)checkShouldDeallocAfter5;
- (_Bool)performSelector:(SEL)arg1 withObject:(id)arg2 withMinInterval:(double)arg3;
@end

