//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface OpenApiVideoFileMsgParam : NSObject
{
    NSString *_appId;
    long long _maxVideoTime;
    NSString *_videoCompressParams;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *videoCompressParams; // @synthesize videoCompressParams=_videoCompressParams;
@property(nonatomic) long long maxVideoTime; // @synthesize maxVideoTime=_maxVideoTime;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;

@end

