//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ActionBase, MMWebImageView, UIButton;
@protocol ProductMediaItemViewDelegate;

@interface ProductMediaItemView
{
    id <ProductMediaItemViewDelegate> _delegate;
    ActionBase *_actionBase;
    MMWebImageView *_imageView;
    UIButton *_playBtn;
    unsigned long long _actionListCount;
}

- (void).cxx_destruct;
- (void)onMediaPlayBtnClicked;
- (void)layoutSubviews;
- (id)initWithDelegate:(id)arg1 actionBase:(id)arg2 actionListCount:(unsigned long long)arg3;

@end

