//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "MMUIViewControllerDelegate-Protocol.h"

@class CContact;

@protocol RecommendAlreadyHadGroupListViewControllerDelegate <MMUIViewControllerDelegate>
- (void)pushPageSheetMsgControllerInRecommendAlreadyHadGroup:(CContact *)arg1 groupIndex:(unsigned int)arg2;
@end

