//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class UIView;

@protocol RecordInfoContentViewDelegate <NSObject>

@optional
- (void)onWorldTranslateButtonTap:(_Bool)arg1;
- (double)getVoiceViewBottomPadding;
- (double)getContentYOffset;
- (double)getParentViewWidth;
- (double)getVisibleHeight;
- (void)onStopSimplifyText;
- (void)onStartSimplifyText;
- (void)onTransFail;
- (void)onTransSuccess;
- (void)onReTrans;
- (void)onCommitText;
- (void)onInputViewChangedWithInputBar:(UIView *)arg1;
- (void)onEndEditing;
- (void)onBeginEditWithInputBar:(UIView *)arg1;
@end

