//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol ShakeMgrExt

@optional
- (void)onShakeMsgUnreadCountChanged;
- (void)onShakeTvStorageChanged;
- (void)onShakeMusicStorageChanged;
- (void)OnShakeShareCountChanged;
- (void)onShakePageStorageChanged;
- (void)onShakePeopleStorageChanged;
- (void)onShakeStatusChanged;
@end

