//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSSet, NSString;

@interface SWMidasGetPromotionalOfferEligibleInfoResp : NSObject
{
    MISSING_TYPE *isEligibleForPromotionalOffer;
    MISSING_TYPE *purchasedAutoSubscriptionProductIDs;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) NSSet *purchasedAutoSubscriptionProductIDs;
@property(nonatomic, readonly) _Bool isEligibleForPromotionalOffer; // @synthesize isEligibleForPromotionalOffer;

@end

