//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TextStatePublishBlackListCache : NSObject
{
}

+ (id)keyForType:(long long)arg1 textStateId:(id)arg2;
+ (id)getItemForType:(long long)arg1 textStateId:(id)arg2;
+ (void)removeItemForType:(long long)arg1 textStateId:(id)arg2;
+ (void)setItem:(id)arg1 forType:(long long)arg2;

@end

