//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class AIGenerationBill;
@protocol TingAIGenerationBillListener;

@protocol TingAIGenerationBillService <NSObject>
- (void)removeListener:(id <TingAIGenerationBillListener>)arg1;
- (void)addListener:(id <TingAIGenerationBillListener>)arg1;
- (AIGenerationBill *)getBill;
- (int)getStatus;
@end

