//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class TingWeCoinConsumeError, TingWeCoinConsumeSuccessResult;

@interface TingWeCoinConsumeResult : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) TingWeCoinConsumeSuccessResult *data; // @dynamic data;
@property(retain, nonatomic) TingWeCoinConsumeError *error; // @dynamic error;
@property(nonatomic) int status; // @dynamic status;

@end

