//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TPStrategyUtil : NSObject
{
}

+ (_Bool)canDecodeBySoftwareForVideo:(id)arg1;
+ (_Bool)canDecodeByHadrwareForVideo:(id)arg1;
+ (id)convertPlayerSceneToString:(long long)arg1;
+ (id)convertPlayerTypeToString:(long long)arg1;
+ (_Bool)canUseSystemPlayerForVideo:(id)arg1;
+ (_Bool)canUseThumbPlayerForVideo:(id)arg1;

@end

