//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TXCBGRADrawer
{
    struct __CVBuffer *_textureRef;
    _Bool _swapColorChannels;
    _Bool _enablePerspective;
    unsigned int _rgbaTextureUniform;
    unsigned int _textureTarget;
    unsigned int _rgbaTexture;
}

@property(nonatomic) _Bool enablePerspective; // @synthesize enablePerspective=_enablePerspective;
@property(readonly, nonatomic) _Bool swapColorChannels; // @synthesize swapColorChannels=_swapColorChannels;
@property(nonatomic) unsigned int rgbaTexture; // @synthesize rgbaTexture=_rgbaTexture;
@property(readonly, nonatomic) unsigned int textureTarget; // @synthesize textureTarget=_textureTarget;
@property(readonly, nonatomic) unsigned int rgbaTextureUniform; // @synthesize rgbaTextureUniform=_rgbaTextureUniform;
- (void)setupCoordsAndDraw;
- (void)draw;
- (void)setupProgramIfNeed:(unsigned int)arg1 swapColorChannels:(_Bool)arg2;
- (_Bool)drawTexture:(unsigned int)arg1 width:(double)arg2 height:(double)arg3;
- (_Bool)drawPixelBuffer:(struct __CVBuffer *)arg1;
- (unsigned long long)getType;
- (void)dealloc;
- (id)initWithContext:(id)arg1 coords:(id)arg2;

@end

