//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class TXCVideoCaptureConfig;
@protocol TXIScreenCaptureDelegate, TXIVideoBindable;

@protocol TXIVideoCaptureInterface <NSObject>
@property(nonatomic) __weak id <TXIScreenCaptureDelegate> delegate;
@property(readonly, nonatomic) int captureType;
@property(readonly) _Bool isRunning;
- (void)stop;
- (void)start;
- (void)captureFrame:(void (^)(TXCVideoFrame *))arg1;
- (void)setFrameRate:(long long)arg1;
- (void)applyConfigs:(TXCVideoCaptureConfig *)arg1;
- (void)removeObserver:(id <TXIVideoBindable>)arg1;
- (void)addObserver:(id <TXIVideoBindable>)arg1;
@end

