//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@interface UIView (AppStandardContent)
- (void)setExternalDidLoadFail;
- (void)setExternalDidLoadDone;
- (_Bool)getExternalDidLoadFail;
- (_Bool)getExternalDidLoadDone;
- (void)onExternalImageLoadFail;
- (void)onExternalImageLoadDone;
- (id)getExtenalLoadImageDelegate;
- (void)setExternalLoadImageDelegate:(id)arg1;
@end

