//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface VoicePrintResourceItem : NSObject
{
    unsigned int _scene;
    unsigned int _resourceId;
    NSString *_resource;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *resource; // @synthesize resource=_resource;
@property(nonatomic) unsigned int resourceId; // @synthesize resourceId=_resourceId;
@property(nonatomic) unsigned int scene; // @synthesize scene=_scene;
- (id)description;

@end

