//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray, NSObject;
@protocol OS_dispatch_queue;

@interface WAJSEventHandler_detectImageCode
{
    NSMutableArray *_detectResults;
    NSObject<OS_dispatch_queue> *_getA8KeyQueue;
}

- (void).cxx_destruct;
- (id)convertQBarInfo2Result:(const void *)arg1;
- (_Bool)scanImage:(id)arg1 imageSize:(struct CGSize)arg2 codeType:(long long)arg3 outResults:(id)arg4;
- (id)getImageGrayDataWithUrl:(id)arg1 size:(struct CGSize *)arg2;
- (void)checkGetA8KeyFinish;
- (void)batchGetA8KeyForResults:(id)arg1;
- (void)handleJSEvent:(id)arg1;

@end

