//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface WAVoIPIntentHandler : NSObject
{
}

+ (_Bool)handleContent:(id)arg1 withUserInfo:(id)arg2 identifer:(id)arg3 soundName:(id)arg4 trigger:(id)arg5 completion:(CDUnknownBlockType)arg6;

@end

