//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray, NSMutableSet, NSObject, NSString, WCCommentContentCgiHelper;
@protocol OS_dispatch_queue;

@interface WCCommentRequestQueueManager
{
    _Bool _isProcessing;
    NSMutableArray *_requestQueue;
    WCCommentContentCgiHelper *_currentCgiHelper;
    NSMutableSet *_requestSnsEmojiInfoObjSet;
    NSObject<OS_dispatch_queue> *_syncQueue;
}

+ (id)sharedQueue;
- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *syncQueue; // @synthesize syncQueue=_syncQueue;
@property(retain, nonatomic) NSMutableSet *requestSnsEmojiInfoObjSet; // @synthesize requestSnsEmojiInfoObjSet=_requestSnsEmojiInfoObjSet;
@property(nonatomic) _Bool isProcessing; // @synthesize isProcessing=_isProcessing;
@property(retain, nonatomic) WCCommentContentCgiHelper *currentCgiHelper; // @synthesize currentCgiHelper=_currentCgiHelper;
@property(retain, nonatomic) NSMutableArray *requestQueue; // @synthesize requestQueue=_requestQueue;
- (void)_safeOperate:(CDUnknownBlockType)arg1;
- (void)updateCommentInfoWithContentResults:(id)arg1;
- (void)processNextBatch;
- (void)removeMd5FromRequestSnsEmojiInfoObjSet:(id)arg1;
- (void)addMd5ToRequestSnsEmojiInfoObjSet:(id)arg1;
- (_Bool)isRequestingSnsEmojiInfoObjWithMd5:(id)arg1;
- (void)enqueueSingleCommentRequest:(id)arg1;
- (void)enqueueCommentRequests:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

