//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class UIView;

@interface WCEdgeList : NSObject
{
    UIView *_view;
}

- (void).cxx_destruct;
- (id)right;
- (id)hCenter;
- (id)left;
- (id)bottom;
- (id)vCenter;
- (id);
- (id)initWithView:(id)arg1;

@end

