//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSMutableArray, WCFinderPlaybackSpeedAnimationView;

@interface WCFinderPlaybackSpeedSegmentView : UIView
{
    UIView *_highlightView;
    WCFinderPlaybackSpeedAnimationView *_animationIconView;
    NSMutableArray *_labels;
    long long _currentRateType;
}

+ (id)createLabel;
- (void).cxx_destruct;
@property(nonatomic) long long currentRateType; // @synthesize currentRateType=_currentRateType;
@property(retain, nonatomic) NSMutableArray *labels; // @synthesize labels=_labels;
@property(retain, nonatomic) WCFinderPlaybackSpeedAnimationView *animationIconView; // @synthesize animationIconView=_animationIconView;
@property(retain, nonatomic) UIView *highlightView; // @synthesize highlightView=_highlightView;
- (void)resetEnhanceAnimation;
- (void)doEnhanceAnimation;
- (void)stopAnimation;
- (void)startAnimation;
- (void)layoutSubviews;
- (void)updateLabelAlpha;
- (id)labelForRateType:(long long)arg1;
- (void)updateWithSelectedRate:(long long)arg1;
- (void)setupWithItems:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 items:(id)arg2;

@end

