//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSString, WCFinderFeedFriendsLikeListTableViewCell;

@protocol WCFinderFeedFriendsLikeListTableViewCellDelegate <NSObject>

@optional
- (NSString *)likeListTableCellGetSessionBuffer:(WCFinderFeedFriendsLikeListTableViewCell *)arg1;
- (_Bool)likeListTableViewCell:(WCFinderFeedFriendsLikeListTableViewCell *)arg1 shouldInterceptThanksButtonTapWithActionBlock:(void (^)(void))arg2;
- (void)likeListTableViewCell:(WCFinderFeedFriendsLikeListTableViewCell *)arg1 iconFrame:(struct CGRect)arg2 animStyle:(unsigned long long)arg3;
- (void)likeListTableViewCell:(WCFinderFeedFriendsLikeListTableViewCell *)arg1 thankState:(_Bool)arg2;
- (_Bool)supportShowThankButton;
- (void)likeListTableViewCell:(WCFinderFeedFriendsLikeListTableViewCell *)arg1 onClickMore:(unsigned long long)arg2 notSee:(_Bool)arg3;
@end

