//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class UIView;
@protocol WCFinderTabViewProtocol;

@protocol WCFinderTabViewDelegate <NSObject>
- (void)finderTabPageTabView:(UIView<WCFinderTabViewProtocol> *)arg1 changeToWidth:(double)arg2;
@end

