//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface WCFinderDelGlobalFavCgi
{
    int _favType;
    NSString *_feedId;
    unsigned long long _collectionId;
    CDUnknownBlockType _sucBlock;
    CDUnknownBlockType _failBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType sucBlock; // @synthesize sucBlock=_sucBlock;
@property(nonatomic) int favType; // @synthesize favType=_favType;
@property(nonatomic) unsigned long long collectionId; // @synthesize collectionId=_collectionId;
@property(copy, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
- (void)finderCgiDidFailWithError:(id)arg1 response:(id)arg2;
- (void)didGetResponse:(id)arg1;
- (void)createRequest;
- (id)logKey;
- (id)initWithDelGlobalFeedId:(id)arg1 collectionId:(unsigned long long)arg2 favType:(int)arg3 sucBlock:(CDUnknownBlockType)arg4 failBlock:(CDUnknownBlockType)arg5;

@end

