//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class WCFinderChooseFeedTabViewModel;

@protocol WCFinderChooseFeedTabViewModelDelegate <NSObject>
- (void)finderChooseFeedTabVMDataChange:(WCFinderChooseFeedTabViewModel *)arg1 hasMore:(_Bool)arg2;
@end

