//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FinderGetCommentListCtx, NSString, UIImage, UIView, WCFinderCommentImageBrowseDataReportParams, WCFinderContact, WCFinderDataItem;

@interface WCFinderCommentImageBrowseConfig : NSObject
{
    _Bool _notTriggerParentVCLifeCycleFunc;
    _Bool _isMemberQA;
    int _viewScene;
    int _pullScene;
    UIView *_startView;
    UIImage *_startImage;
    unsigned long long _commentStyleType;
    unsigned long long _initRefCommentID;
    WCFinderDataItem *_dataItem;
    NSString *_enterSessionId;
    FinderGetCommentListCtx *_commentCtx;
    unsigned long long _sortType;
    unsigned long long _selectedType;
    WCFinderContact *_currentFinderContact;
    unsigned long long _replyScene;
    WCFinderCommentImageBrowseDataReportParams *_dataReportParams;
    CDUnknownBlockType _getLastBufferRequest;
    CDUnknownBlockType _getRootCommentRequest;
    CDUnknownBlockType _updateIdentityCallback;
    CDUnknownBlockType _exitCallback;
}

- (void).cxx_destruct;
@property(copy) CDUnknownBlockType exitCallback; // @synthesize exitCallback=_exitCallback;
@property(copy) CDUnknownBlockType updateIdentityCallback; // @synthesize updateIdentityCallback=_updateIdentityCallback;
@property(copy) CDUnknownBlockType getRootCommentRequest; // @synthesize getRootCommentRequest=_getRootCommentRequest;
@property(copy) CDUnknownBlockType getLastBufferRequest; // @synthesize getLastBufferRequest=_getLastBufferRequest;
@property(retain) WCFinderCommentImageBrowseDataReportParams *dataReportParams; // @synthesize dataReportParams=_dataReportParams;
@property(nonatomic) unsigned long long replyScene; // @synthesize replyScene=_replyScene;
@property(retain) WCFinderContact *currentFinderContact; // @synthesize currentFinderContact=_currentFinderContact;
@property(nonatomic) _Bool isMemberQA; // @synthesize isMemberQA=_isMemberQA;
@property(nonatomic) unsigned long long selectedType; // @synthesize selectedType=_selectedType;
@property(nonatomic) unsigned long long sortType; // @synthesize sortType=_sortType;
@property(retain) FinderGetCommentListCtx *commentCtx; // @synthesize commentCtx=_commentCtx;
@property(nonatomic) int pullScene; // @synthesize pullScene=_pullScene;
@property(nonatomic) int viewScene; // @synthesize viewScene=_viewScene;
@property(retain) NSString *enterSessionId; // @synthesize enterSessionId=_enterSessionId;
@property(retain) WCFinderDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(nonatomic) unsigned long long initRefCommentID; // @synthesize initRefCommentID=_initRefCommentID;
@property(nonatomic) unsigned long long commentStyleType; // @synthesize commentStyleType=_commentStyleType;
@property(nonatomic) _Bool notTriggerParentVCLifeCycleFunc; // @synthesize notTriggerParentVCLifeCycleFunc=_notTriggerParentVCLifeCycleFunc;
@property __weak UIImage *startImage; // @synthesize startImage=_startImage;
@property __weak UIView *startView; // @synthesize startView=_startView;
- (void)fillWithCommentDetailVM:(id)arg1;
- (void)checkParams;

@end

