//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface WCMomentsCommentBrowseAggreReport : NSObject
{
    NSObject<OS_dispatch_queue> *_syncQueue;
    _Bool _enableUploadByGroup;
    long long _snsScene;
    NSString *_sessionId;
    NSMutableDictionary *_cmtBrowseListDict;
}

+ (id)sharedQueue;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *cmtBrowseListDict; // @synthesize cmtBrowseListDict=_cmtBrowseListDict;
@property(nonatomic) _Bool enableUploadByGroup; // @synthesize enableUploadByGroup=_enableUploadByGroup;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) long long snsScene; // @synthesize snsScene=_snsScene;
- (void)clearALLCmtData;
- (void)reportCmtListStr:(id)arg1;
- (void)report;
- (void)recordPicClickForFeed:(id)arg1 comment:(id)arg2;
- (void)recordEmoticonClickForFeed:(id)arg1 comment:(id)arg2;
- (void)recordClickForFeed:(id)arg1 comment:(id)arg2;
- (void)recordExposureForFeed:(id)arg1 comment:(id)arg2;
- (void)_safeAccessStorage:(CDUnknownBlockType)arg1;
- (id)init;

@end

