//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "WCPayBaseCgiDelegate-Protocol.h"

@class QryHoneyPayCardDetailResp, WCPayBaseNetworkingError, WCPayQryHoneyPayCardDetailCgi;

@protocol WCPayQryHoneyPayCardDetailCgiDelegate <WCPayBaseCgiDelegate>
- (void)qryHoneyPayCardDetailCgi:(WCPayQryHoneyPayCardDetailCgi *)arg1 didFailWithError:(WCPayBaseNetworkingError *)arg2;
- (void)qryHoneyPayCardDetailCgi:(WCPayQryHoneyPayCardDetailCgi *)arg1 didGetResponse:(QryHoneyPayCardDetailResp *)arg2;
@end

