//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSDictionary;

@protocol WCPayCollectPalmControlLogicDelegate <NSObject>

@optional
- (void)onWCPayCollectPalmControlLogicEndWithFail:(NSDictionary *)arg1;
- (void)onWCPayCollectPalmControlLogicEndWithCancel:(NSDictionary *)arg1;
- (void)onWCPayCollectPalmControlLogicEndWithOK:(NSDictionary *)arg1;
@end

