//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol WCPayCreditPayIncreaseLimitSucViewControllerDelegate;

@interface WCPayCreditPayIncreaseLimitSucViewController
{
    id <WCPayCreditPayIncreaseLimitSucViewControllerDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)initHeaderView;
- (void)initNavigationBar;
- (void)viewDidLayoutSubviews;
- (void)onBack;
- (void)setDelegate:(id)arg1;
- (id)init;

@end

