//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCTBridgeProperty : NSObject
{
    const void *m_innerProperty;
}

+ (id)creatBridgeProperty:(const void *)arg1;
- (const void *)tableBinding;
- (const void *)wctProperty;
@property(readonly, nonatomic) NSString *propertyName;

@end

