//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSSet, NSString, WCAdFlipCardInfo, WCAdvertiseAnimationDisplayLink, WCDataItem, WCTimeLineAdFlipCardMediaCollectionView;
@protocol WCTimeLineAdFlipCardMediaHolderViewDelegate;

@interface WCTimeLineAdFlipCardMediaHolderView : UIView
{
    _Bool _bTimelineScene;
    _Bool _isVideoReadyToPlay;
    WCAdFlipCardInfo *_adFlipCardInfo;
    WCDataItem *_dataItem;
    double _currentRotationAngle;
    WCTimeLineAdFlipCardMediaCollectionView *_rotationCollectionView;
    id <WCTimeLineAdFlipCardMediaHolderViewDelegate> _delegate;
    WCAdvertiseAnimationDisplayLink *_mediaHolderDisplayLink;
    unsigned long long _mediaHolderAnimationStatus;
    unsigned long long _mediaHolderBackMediaStatus;
    NSSet *_lastTouchesLocations;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSSet *lastTouchesLocations; // @synthesize lastTouchesLocations=_lastTouchesLocations;
@property(nonatomic) _Bool isVideoReadyToPlay; // @synthesize isVideoReadyToPlay=_isVideoReadyToPlay;
@property(nonatomic) unsigned long long mediaHolderBackMediaStatus; // @synthesize mediaHolderBackMediaStatus=_mediaHolderBackMediaStatus;
@property(nonatomic) unsigned long long mediaHolderAnimationStatus; // @synthesize mediaHolderAnimationStatus=_mediaHolderAnimationStatus;
@property(retain, nonatomic) WCAdvertiseAnimationDisplayLink *mediaHolderDisplayLink; // @synthesize mediaHolderDisplayLink=_mediaHolderDisplayLink;
@property(nonatomic) __weak id <WCTimeLineAdFlipCardMediaHolderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WCTimeLineAdFlipCardMediaCollectionView *rotationCollectionView; // @synthesize rotationCollectionView=_rotationCollectionView;
@property(nonatomic) double currentRotationAngle; // @synthesize currentRotationAngle=_currentRotationAngle;
@property(nonatomic) _Bool bTimelineScene; // @synthesize bTimelineScene=_bTimelineScene;
@property(retain, nonatomic) WCDataItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain, nonatomic) WCAdFlipCardInfo *adFlipCardInfo; // @synthesize adFlipCardInfo=_adFlipCardInfo;
- (void)reportIntroduceAnimationDone;
- (void)reportIncreaseTouchCount;
- (id)reportItemForIndex:(unsigned long long)arg1;
- (id)reportInfo;
- (id)onMediaBaseViewFetchReportItemFor:(unsigned long long)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)onMediaCollectionViewDidMoveToWindow;
- (void)onMediaCollectionViewDidMoveToSuperview;
- (void)onMediaCollectionViewTouchesLocationsUpdated:(id)arg1;
- (void)onMediaCollectionViewTouchesEnded;
- (void)onMediaCollectionViewTouchesBegan;
- (void)onAnimationDisplayLinkAnimationDone:(id)arg1;
- (void)resetBackTVCAnimation;
- (void)showBackTVCAnimation;
- (id)mediaHolderBackTVCAnimationObjectLearnMoreShow;
- (id)mediaHolderBackTVCAnimationObjectSubTitleHide;
- (id)mediaHolderBackTVCAnimationObjectTitleOpacity;
- (id)mediaHolderBackTVCAnimationObjectTitlePosition;
- (id)mediaHolderBackTVCAnimationObjectTopMaskHeight;
- (id)mediaHolderBackTVCAnimationObjectTopMaskWidth;
- (id)mediaHolderBackTVCAnimationObjectMidScale;
- (id)generateMediaHolderAnimationObjectMediaPinToTop;
- (id)mediaHolderBackTVCAnimationObjectBottomPosition;
- (id)mediaHolderBackTVCAnimationObjectMidPosition;
- (id)mediaHolderBackTVCAnimationObjectTopPosition;
- (void)checkIfMediaViewTurnedToBackSide;
- (void)scheduleResumeIntroduceAnimation;
- (void)cancelIntroduceAnimation;
- (void)showIntroduceTwoAnimation;
- (void)showIntroduceAnimation;
- (id)mediaHolderIntroduceTwoAnimationObjectUpdatePage;
- (id)mediaHolderIntroduceTwoAnimationObject;
- (id)mediaHolderIntroduceOneAnimationObject;
- (void)cellsExposureProcess;
- (void)checkCellsState;
- (void)shutdownAllVideos;
- (void)autoplayVideoProcess;
- (void)setVideosWithPlayState:(_Bool)arg1;
- (void)onMediaAutoPause;
- (void)onMediaAutoPlay;
- (void)onMediaBecomeInvisible;
- (void)onMediaDidEndDisplaying;
- (void)onMediaWillDisplay;
- (_Bool)isClickAvailableFor:(id)arg1 points:(id)arg2 bExpended:(_Bool)arg3;
- (unsigned long long)decideClickTypeWithSideIndex:(long long)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)resetCollectionViewFromInteraction;
- (void)scheduleResetCollectionViewFromInteraction;
- (_Bool)isIntroduceAnimationCancelled;
- (void)onMediaHolderFlippedWithScrollView:(id)arg1 contentOffset:(struct CGPoint)arg2;
- (void)resetCollectionView;
- (long long)fetchPendingIndexWithScrollView:(id)arg1 contentOffset:(struct CGPoint)arg2;
- (long long)fetchPendingIndexWithScrollView:(id)arg1;
- (long long)fetchSideIndexWithScrollView:(id)arg1;
- (double)fetchOffsetXWith:(id)arg1 forDegree:(double)arg2;
- (long long)fetchSafeIndex:(long long)arg1;
- (void)prepareCollectionViewForInfinityLoop;
- (void)onScrollViewDidEndDecelerating:(id)arg1;
- (double)getCurrentDistance:(id)arg1;
- (double)getOriginContentOffsetX:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionLayout;
- (id)backVideoView;
- (id)frontVideoView;
- (id)safeFetchMediaBaseTitleViewForTag:(long long)arg1;
- (id)safeFetchMediaBaseContainerViewForTag:(long long)arg1;
- (id)safeFetchMediaBaseViewForTag:(long long)arg1;
- (void)safeUpdateTransformForTag:(long long)arg1 transform:(struct CATransform3D)arg2;
- (void)updateAllMediaViewsLayout;
- (void)updateAllMediaViewsWithAngle:(double)arg1;
- (void)resetAllMediaViewsLayout;
- (void)setupAllMediaViewsLayout;
- (id)generateMediaViewWithMediaData:(id)arg1 index:(unsigned long long)arg2;
- (void)generateSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 adFlipCardInfo:(id)arg2 dataItem:(id)arg3 bTimelineScene:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

