//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface WCWebSameLayerUtil : NSObject
{
}

+ (id)objDescriptionForLog:(id)arg1;
+ (id)makeViewDesc:(id)arg1;
+ (void)printView:(id)arg1 linePrefix:(id)arg2 buffer:(id)arg3;
+ (void)printTreeView:(id)arg1;
+ (void)reportIdKey:(unsigned int)arg1;
+ (id)sameLayerSwitchDictForAllScene;
+ (_Bool)isSameLayerSwitchOpenWithScene:(unsigned long long)arg1;

@end

