//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface WebviewJSEventHandler_getClipboardData
{
}

- (double)getRemindAminitionDuration;
- (_Bool)iOSReadPasteBaordRemindOpen;
- (void)fetchClipBoardContentWithTextPtr:(id *)arg1 htmlPtr:(id *)arg2 hasContentPtr:(_Bool *)arg3;
- (void)readPasteBoardWithEvent:(id)arg1 hasContentPtr:(_Bool *)arg2;
- (void)handleJSEventInMainThread:(id)arg1;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;

@end

