//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface WebViewSanboxSessionTaskEventInfo : NSObject
{
    NSString *_name;
    unsigned long long _eventTime;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long eventTime; // @synthesize eventTime=_eventTime;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (id)descriptionWithStartTime:(unsigned long long)arg1;

@end

