//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class JSEvent, NSString, WCFinderPostMgr;

@interface WebviewJSEventHandler_openFinderCamera
{
    JSEvent *_event;
    WCFinderPostMgr *_postMgr;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WCFinderPostMgr *postMgr; // @synthesize postMgr=_postMgr;
@property(retain, nonatomic) JSEvent *event; // @synthesize event=_event;
- (id)postMgrGetVideoTemplateInfo:(id)arg1;
- (id)postMgrSourceInfo:(id)arg1;
- (void)returnResult:(id)arg1 code:(long long)arg2 message:(id)arg3;
- (void)handleJSEvent:(id)arg1 HandlerFacade:(id)arg2 ExtraData:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"NSString",?,R,C

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

