//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface WebViewSanboxTaskGcdTimerUserInfo : NSObject
{
    _Bool _bRepeat;
    unsigned int _timerId;
}

@property(nonatomic) _Bool bRepeat; // @synthesize bRepeat=_bRepeat;
@property(nonatomic) unsigned int timerId; // @synthesize timerId=_timerId;

@end

