//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface WeVisUDRService
{
}

+ (id)debugDescription;
+ (id)postPathOfResource:(id)arg1;
+ (id)pathOfResource:(id)arg1;
+ (_Bool)checkResourcesWithNamesAndVersions:(id)arg1;
+ (id)pathOfResourceWithName:(id)arg1 version:(long long)arg2;
+ (void)requestResourcesWithNames:(id)arg1;
+ (id)resourceWithName:(id)arg1;
+ (id)allResources;
+ (id)UDRProjectCheckParameter;
+ (id)UDRProjectId;
- (void)onCallBackSuccessAsync:(unsigned long long)arg1 projectId:(id)arg2 name:(id)arg3 version:(int)arg4 scene:(int)arg5;
- (id)getParameter;
- (id)getProjectId;

@end

