//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIAccessibilityElement.h>

@interface WNAccessibilityMenuElement : UIAccessibilityElement
{
    CDUnknownBlockType _handle;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType handle; // @synthesize handle=_handle;
- (_Bool)accessibilityActivate;

@end

