//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class BaseRequest, NSMutableArray, ReportDeviceInfo;

@interface WxaAppIDKeyBatchReportRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(retain, nonatomic) NSMutableArray *recordList; // @dynamic recordList;
@property(retain, nonatomic) ReportDeviceInfo *reportDeviceInfo; // @dynamic reportDeviceInfo;

@end

