//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtobufLite/WXPBGeneratedMessage.h>

@class NSString;

@interface WxaCommentInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *darkModeIconUrl; // @dynamic darkModeIconUrl;
@property(retain, nonatomic) NSString *iconUrl; // @dynamic iconUrl;
@property(retain, nonatomic) NSString *scoreStr; // @dynamic scoreStr;
@property(nonatomic) unsigned int showDuration; // @dynamic showDuration;
@property(nonatomic) unsigned int showTime; // @dynamic showTime;

@end

