//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface YTFaceFastDetector : NSObject
{
}

+ (unsigned long long)getFaceCountFromImage:(id)arg1;
- (unsigned long long)getImageFaceCount:(id)arg1;
- (struct Mat)getCvRgbFromCGImageRef:(struct CGImage *)arg1;
- (int)globalReleaseDetector;
- (int)globalInitDetector;
- (id)init;
- (void)dealloc;

@end

